### PR TITLE
apparmor profile for coolwsd

### PR DESCRIPTION
**Pull request by caolanm**
See: https://wiki.debian.org/AppArmor/Contribute/FirstTimeProfileImport

Change-Id: I2451cfc222b6745307554fde37870717204e8a99

* Resolves: # 
* Target version: master 

### TODO

- [ ] ...

### Checklist

- [ ] I have run `make prettier-write` and formatted the code.
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by caolanm** [comment]
In a Ubuntu 24.04 virtualbox install manually installing these rules was sufficient to get coolwsd with namespaces allowed to get past https://bugs.launchpad.net/ubuntu/+source/apparmor/+bug/2046844

The actual generation of .deb is untested however

**Review by mmeeks — APPROVED** [review]
Looks great to me =) thanks Caolan.

**Comment by mmeeks** [comment]
I wonder if we can add some helpful docs to the configure.ac to get people to detect Ubuntu and/or this problem and get them to set that up ? =)

**Comment by caolanm** [comment]
The catch with the apparmor profile is that it's tied to the install location, so the above should be fine for the install from .deb but leave the dev self-build make run case as a problem.

It's probably possible to use setfattr to tag a self-build coolwsd to use some existing profile that is allowed to do usernamespaces, but that needs root, so it's back to using sudo then.

But I see that Ubuntu podman (unsurprisingly) has apparmor permission to create these namespaces. So what works for me is to leverage Ubuntu podman with "podman unshare ./coolwsd" to launch a self-build coolwsd in an env where it is allowed to use namespaces by apparmor with a default Ubuntu 24.04 install in VirtualBox.

https://github.com/CollaboraOnline/online/pull/9716 for that idea

**Pull request merged**
