### PR TITLE
Create new top bar comment icon

### LINKED ISSUE #202: Mobile: Create new top bar comment icon
**This is an [Easy Hack](https://collaboraonline.github.io/post/easyhacks/).**

The current icon used in the mobile for comment is with a plus denoting the "insert comment" but now @lpranam is working on a way to also use it to trigger to view comments (it will open the bottom wizard displaying existent comments and with possibility to insert from there) 

:point_right: : Create new icon that replaces the existent "insert comment" asset
:round_pushpin: : `images/lc_insertcomment.svg`
:page_facing_up: : assigned in toolbar.css:765

### PR DESCRIPTION
**Pull request by umutbayramoglu**
* Resolves: # 
* Target version: master 

### Summary
Create new comment icon that replaces the 'insert comment' icon.
Fixes #202 

### TODO

- [ ] ...

### Checklist

- [x] Code is properly formatted
- [x] All commits have Change-Id
- [x] I have run tests with `make check`
- [x] I have issued `make run` and manually verified that everything looks okay
- [x] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by pedropintosilva** [comment]
Thanks for this PR @umutbayramoglu !
I like how easy it is to recognize the outer shape : )

PR870

Do you think you could iterate on this PR so 
* The outer shape is more similar to the neighbour icons for example sharing the same radius. But if you don't feel like it, no problem we can always merge it and then re-think/re-iterate the outer shape : )
* The inner elements of the icon are not that similar with the Hamburger menu. Maybe we can turn the 3 lines into 3 dots either vertically aligned to the left (so it contra-balances nicely with the outer shape tail) or horizontally. What do you think?

**Comment by umutbayramoglu** [comment]
Thanks for your review @pedropintosilva.
I will iterate on my PR  in line with your suggestions. About the inner elements of the icon, I think horizontal three dots (ellipsis) refers to more '_text content_' than vertical three dots. So I can change the lines into horizontal dots.

**Comment by umutbayramoglu** [comment]
Thanks for your review @pedropintosilva.
I will iterate on my PR in line with your suggestions. About the inner elements of the icon, I think horizontal three dots (ellipsis) refer to more 'text content' than vertical three dots. So I can change the lines into horizontal dots.

**Review by pedropintosilva — CHANGES_REQUESTED** [review]
polite ping : )

**Review by lpranam — CHANGES_REQUESTED** [review]
hello, @umutbayramoglu thank you for amazing work. But I think a round icon does not go well with the other icons here. maybe if we use a solid rectangle with rounded corners then it would match better with other icons. What do you think?

**Comment by umutbayramoglu** [comment]
Thanks for your review @lpranam. I think you are right, I updated the icon to _solid-rectangle_ style. Can you check it?

**Comment by pedropintosilva** [comment]
Thanks @umutbayramoglu ! I will merge it and then would be good if you could add another exact icon but for insert comments (with plus instead of the 3 dots) for the new Insert row element :

image

**Review by pedropintosilva — APPROVED** [review]

**Comment by pedropintosilva** [comment]
wit that in mind I sent #963

**Comment by pedropintosilva** [comment]
done : ) you can now open a new PR and modify the respective [icon](https://github.com/CollaboraOnline/online/blob/17dc3b23fd484f088f263ff15b60e57ad3bdad5e/loleaflet/images/lc_insertcomment.svg)

**Pull request merged**
