### PR TITLE
Calc grouping: find parent groups correctly

### PR DESCRIPTION
**Pull request by bayramcicek**
- groups was using indexes to find their parent groups.
  - this does not work properly and causes following issues: 
    - some groups are created but not drawn (so they are invisible)
    - some parent groups does not hide their child groups

- this patch:
  - removes the index-based search of parent groups.
  - implements startPos and endPos based search.

Change-Id: Ia3b85f3d9a032008f8abbc7b38ad2417aa0ec6c8

* Resolves: #7811
* Target version: master 

### TODO

- [ ] ...

### Checklist

- [x] Code is properly formatted
- [x] All commits have Change-Id
- [ ] I have run tests with `make check`
- [x] I have issued `make run` and manually verified that everything looks okay
- [x] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by bayramcicek** [comment]
some recordings after the patch:

https://github.com/CollaboraOnline/online/assets/24255179/af829248-1cf8-4a6c-8af8-bebfc042e52c

https://github.com/CollaboraOnline/online/assets/24255179/c8ba9ea3-8349-4f48-b7e3-ecebd284685a

https://github.com/CollaboraOnline/online/assets/24255179/c3166b22-67bc-40e5-b8d5-4baf3fbb984f

**Comment by gokaysatir** [comment]
Some part of this looks like regression. Anyway, 2 suggestions:
* I strongly recommend to simplify the "_isPreviousGroupVisible" and "_isParentGroupVisible" functions.
    * There is group-index property, which distinguishes the groups of the same level. I think we can make use of it, to avoid the issue in the images.
* We need Cypress tests for this feature. If it can cover some of the issues solved here, that'd be great.

There is an issue with the behaviour, please check the screen shots and let me know if anything is unclear.
* First 2 are from your PR.
* Last 2 are from desktop build.

**Review by gokaysatir — CHANGES_REQUESTED** [review]
Please see my first comment.

**Comment by bayramcicek** [comment]
(if I am not mistaken) I see that the issue on the screenshots are "overlapping issue" that is known issue - but I didn't report it yet. The issue is already exist on online master:

https://github.com/CollaboraOnline/online/assets/24255179/cdf6628d-0ea9-4c02-aab4-28b72a4cfbac

---

and I don't see any plus sign when I create the same groups as in the screenshots you've shared:
 (probably I followed the wrong steps?)

(we can also see the overlap issue here - which is not related to my patch)

https://github.com/CollaboraOnline/online/assets/24255179/23975089-8443-4e8a-a1db-29e7ca13661c

Thanks!

**Comment by gokaysatir** [comment]
Okay, please add 2 groups to the same level and collapse the upper one. Then the drawing is faulty i think.

**Comment by gokaysatir** [comment]
The 2 groups should touch btw. Like "A1:A20" and "A21:A40" etc.

**Comment by bayramcicek** [comment]
> Okay, please add 2 groups to the same level and collapse the upper one. Then the drawing is faulty i think.

Ok. Thanks. Then I'm working on the overlapping issue...

**Comment by bayramcicek** [comment]
about commit: https://github.com/CollaboraOnline/online/pull/7961/commits/ab306916d7ca78809e1e483593211a14fcd670d3 (Calc grouping: fix overlapping issue)

Behavior on Online vs LO:

**Online**: expanding order starts with the **first** group.
**LibreOffice**: expanding order starts with the **latest** group.

Both of them seem plausible for me. So IMHO, there is no problem about the expanding order.


https://github.com/CollaboraOnline/online/assets/24255179/3a57823e-1b31-46c4-8033-12289b7408dc

https://github.com/CollaboraOnline/online/assets/24255179/c4aa372f-9152-44ae-89a4-057b186ce393

**Review by gokaysatir — APPROVED** [review]
Thanks for the fixes @bayramcicek :)

**Review by pedropintosilva — APPROVED** [review]
Tested :+1: Thanks!

**Pull request merged**
