### PR TITLE
jsdialog: use unique ids for unobuttons

### PR DESCRIPTION
**Pull request by eszkadev**
now all uno buttons with the same command will share class not id:
.unoXXX  not  #XXX

this is needed for a11y

### CODE REVIEW

**Comment by eszkadev** [comment]
@pedropintosilva FYI
What I see is that we don't use too much of css rules for specific uno buttons using ids.
(one I can see is InsertGraphic in branding). Worth checking if everything looks ok.

**Review by gokaysatir — DISMISSED** [review]
Thanks for the fix :)

**Comment by eszkadev** [comment]
but we have to fix cypress, it uses old ids...

**Review by pedropintosilva — APPROVED** [review]
Thanks @eszkadev !

**Pull request merged**
