### PR TITLE
Variable names for the color-palette

### PR DESCRIPTION
**Pull request by Andreas-Kainz**
there are 4 type of color sections:
1. text
2. background
3. border
4. primary

and for each section there are
1. without extension for default color usage
2. -dark suffix for selected
3. -darker suffix for hover
4. -lighter for non available

with this setting the developer can choose
easy the section and the -suffix.

In addition there is primary color
which bring color the the apps and should depend
on the app so
- writer = LibO brand color blue,
- calc = LibO brand color green,
- ...

Signed-off-by: andreas kainz <kainz.a@gmail.com>
Change-Id: I668b5505abd5d70345221bc79d921071c4a49cd7

* Resolves: #3772

### CODE REVIEW

**Comment by Andreas-Kainz** [comment]
@pedropintosilva the first old section will be removed (with separate PR's). I have a nearly complete PR for most var changes, but as always I would like to make small changes so first let's finalize the var's number and name than edit the css files.

open questions:
- the sections for text, background, border and primary are ok for me and easy to understand. But should I write as comment to the color-palette.css file that -dark is for select, -darker for hover, ... ? So should I add commends as description?
- How can I use in the color-palette file for the primary color an app specific color?

**Comment by Andreas-Kainz** [comment]
Don't care about the colors, they will be adjusted when everything use var's.

**Comment by pedropintosilva** [comment]
> @pedropintosilva the first old section will be removed (with separate PR's). I have a nearly complete PR for most var changes, but as always I would like to make small changes so first let's finalize the var's number and name than edit the css files.
> 
> open questions:
> 
>     * the sections for text, background, border and primary are ok for me and easy to understand. But should I write as comment to the color-palette.css file that -dark is for select, -darker for hover, ... ? So should I add commends as description?

Yes I think indeed that could be helpful : )

> 
>     * How can I use in the color-palette file for the primary color an app specific color?

**Comment by pedropintosilva** [comment]
merging thanks!

**Comment by pedropintosilva** [comment]
just a reminder of the lack of contrast that is not present in the menus https://github.com/CollaboraOnline/online/commit/c60a563379126483dfcce900a6f11f800af7649e#commitcomment-64740505
image

**Pull request merged**
