### PR TITLE
Fix app.sectionContainer being null

### PR DESCRIPTION
**Pull request by tcitworld**
Similar to 4764937ad44a5cca99a7d5b962e661f491d18cb1

* Resolves: #4264
* Target version: master 

### Summary
Should avoid issues like
```
Uncaught TypeError: app.sectionContainer.getSectionWithName(...) is null
    _hideWizard https://coolwsd.xxx.org/browser/e4d06c2/bundle.js:1
[bundle.js:1:2264150](https://coolwsd.framasoft.org/browser/e4d06c2/bundle.js)
    _hideWizard https://coolwsd.xxx.org/browser/e4d06c2/bundle.js:1
    _hideWizard self-hosted:1184
```

### Checklist

- [ ] Code is properly formatted
- [x] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Review by eszkadev — APPROVED** [review]
Thanks, looks good :)

**Comment by pedropintosilva** [comment]
So cool @tcitworld creating an issue and solve it, perfect thanks! (thanks @eszkadev for reviewing )

**Comment by webartifex** [comment]
Hi,
I am new to Nextcloud and Collabora Online.
I keep getting the same error (also with Firefox) although I am already running the packaged version with this fix.
So, to me it seems as this bug still persists in the latest version.
Not sure, how I can help further.
Cheers,
Alex

**Comment by XueSheng-GIT** [comment]
I'm also getting this error:
> Uncaught TypeError: app.sectionContainer.getSectionWithName

I'm using firefox 99 on WIn10 and Ubuntu 22.04
Collabora version 21.11.3.3 (official collabora repo)

**Comment by XueSheng-GIT** [comment]
Just saw that there's an update available (collabora 21.11.3.6). Issue still persists.

**Pull request merged**
