### PR TITLE
Add rename document to notebookbar and menubar

### PR DESCRIPTION
**Pull request by NickWingate**
Change-Id: Iec25de88aa3e7089af102dd9f4bda6507308c215

Related: [#6989](https://github.com/CollaboraOnline/online/pull/6989)

Add button to notebookbar and menubar to rename document.

* Resolves: # 
* Target version: master 

### TODO

- [x] Test with integrator (nextcloud)
- [ ] Get icon
- [x] Test menubar

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by pedropintosilva** [comment]
@NickWingate the following is not produced by this PR but it's emphasise with it:

Right now ``documentNameConfirm`` function requires the extension to be passed. If the extension is not passed (user doesn't type it in the dialog or removes it in the input field (toolbar) before pressing enter : **Nothing happens**, nothing is renamed, no error is triggered. Could you please adjust that function?  If no extension is passed, we should just use the existent document's extension and rename it. Right now it never enters ``if (value.lastIndexOf('.') > 0) {``

**Comment by NickWingate** [comment]
@pedropintosilva 
Done, if the user doesn't specify extension we use the `map.rename` function (`Control.DocumentNameInput.js:34`) which just takes filename without an extension and preserves the original extension

**Review by pedropintosilva — APPROVED** [review]

**Comment by pedropintosilva** [comment]
waiting for another +1

**Review by eszkadev — APPROVED** [review]
code looks good

**Pull request merged**
