### PR TITLE
Add FreeBSD case to autogen.sh

### PR DESCRIPTION
**Pull request by arrowd**
Change-Id: Ib0e1cb3f34099a46e34e17a23e38d1c4bdb7dec9

* Target version: master 

### Checklist

- [x] Code is properly formatted
- [x] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [x] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by tml1024** [comment]
Is this an initial commit of a work in progress, or do you actually have "make run" already working on FreeBSD? Have you attempted to compile the code and noticed how much Linux-specific things there might be there?

**Comment by arrowd** [comment]
> Is this an initial commit of a work in progress, or do you actually have "make run" already working on FreeBSD? If not, h you attempted to compile the code and noticed how much Linux-specific things there might be there?

Yep, I saw that. I plan to gradually fight through all these Linuxisms and submit PRs.

**Comment by tml1024** [comment]
I guess one fundamental issue here is that Collabora Online takes security seriously; thus the use of chroot "jails" for the kit proceses, and restricting what system calls the kit processes are allowed to perform (see common/Seccomp.cpp). Does the latter possibility exist on FreeBSD? If not, do we want to encourage (in some sense) running Collabora Office on a system where it doesn't offer the same level of security as on Linux? I don't know. We do have a configure option --disable-seccomp already, though...

**Comment by arrowd** [comment]
> We do have a configure option --disable-seccomp already, though...

Yes, and I had to enable it.

> Does the latter possibility exist on FreeBSD?

We do have Capsicum - a capability and sandbox framework, which seem to do what you are describing.

We also have Jails (literally, without quotes) - a mechanism for creating light-weight isolated environments. I actually planned to run whole Online inside such jail.

> If not, do we want to encourage (in some sense) running Collabora Office on a system where it doesn't offer the same level of security as on Linux?

What are these kit processes? What security implications may arise when we run them on a system? I had an impression that Online consists of one or more network services like FTP server, HTTP server and so on. What's so special about them?

**Comment by mmeeks** [comment]
Each document is handled in it's own 'Kit' process - forked from the 'forkit' which then locks that process down hard. Seccomp-bpf, chroot, almost nothing in there (a few required device nodes like /dev/random for SSL etc.) - we need that to protect us from vulnerabilities in each Kit process - 8million lines of code - we do a ton of hardening of that all the time, but with the best will in the world: we try not to trust the kit process once it has user data inside.

I'm excited to get partial *BSD support, the perfect is by far the enemy of the good - lets get it in, and iterate it to harden it. I believe we log something scary in the logs if seccomp is not enabled; if not we should - but ... =) for the AppImage / hoome stuff we do something similar - so no problem getting it in.

Thanks for your work arrowd ! =)

**Review by mmeeks — APPROVED** [review]
Lets get it in for now; thanks =)

**Comment by arrowd** [comment]
Great, thanks!

For now I plan to mostly ifdef out Linux bits until I get the whole bits compile. After that, I'll look into reimplementing ifdef'ed parts for FreeBSD.

**Comment by mrkara** [comment]
@arrowd Thank you for your contribution, and congratulations on your first merged PR! :)

We're looking forward to the next one. ;)

Please feel free to drop by one of our [communication channels](https://collaboraonline.github.io/post/communicate/) ([#cool-dev on Freenode](https://webchat.freenode.net/#cool-dev) is recommended for developers) if you have any questions.

**Pull request merged**
