### PR TITLE
[docker] Porting to Debian 11 (stable) #4695

### PR DESCRIPTION
**Pull request by callmetushar123**
* Resolves: #4695 
* Target version: master 

### Summary
I have resolved the docker issue for porting to Debian 11. I have removed certain module that was creating issue while building the docker image

### TODO

- [ ] ...

### Checklist

- [x] Code is properly formatted
- [x] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [x] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by callmetushar123** [comment]
@pedropintosilva can you please review it?

**Comment by callmetushar123** [comment]
@thebearon can you guide me how to do that? I am doing it for the first time

**Comment by callmetushar123** [comment]
@thebearon Can I close this PR, delete my branch and then create a new branch and then create a PR?

PS: The changes from https://github.com/CollaboraOnline/online/pull/5319 were merged and it doesn't seem to appear here except for the commit message. Since I couldn't perform another fork of the same repo, I intentionally created a new branch to push the changes for this issue.

**Comment by thebearon** [comment]
@callmetushar123 Sure, feel free to create a new PR. We'd like to avoid having merge commits, they are unnecessary and adds noise to the commit history.

**Comment by callmetushar123** [comment]
@thebearon Will deleting my forked repo affect my contribution history in anyway?

**Pull request closed without merging**
