### PR TITLE
private/pedro/nb file tab id capitalize

### PR DESCRIPTION
**Pull request by pedropintosilva**
- Notebookbar: Fix SaveAs Id, Capitalize Each Word
- Notebookbar: Fix rev-history Id, Capitalize Each Word

### CODE REVIEW

**Comment by pedropintosilva** [comment]
have no idea why cypress fails..

```bash
Build timed out (after 60 minutes). Marking the build as aborted.
Build was aborted
[PostBuildScript] - [INFO] Executing post build scripts.
[github_online_master_debug_vs_co-22.05] $ /bin/bash /tmp/jenkins13354190020139035627.sh
INFO : AFTER ABORT or FAILURE CLEAN UP STARTED
INFO : Running `git clean -ffd` ...
INFO : Running `make distclean` ...
INFO : Cleaning stuck jails on the slave if there is any
umount: /home/collabora/jenkins/workspace/github_online_master_debug_vs_co-22.05/jails/TCIkT91yM2ewyA3X/tmp: target is busy.
umount: /home/collabora/jenkins/workspace/github_online_master_debug_vs_co-22.05/jails/TCIkT91yM2ewyA3X/lo: target is busy.
umount: /home/collabora/jenkins/workspace/github_online_master_debug_vs_co-22.05/jails/TCIkT91yM2ewyA3X: target is busy.
umount: /home/collabora/jenkins/workspace/github_online_master_debug_vs_co-22.05/jails/RNW41gRNXD0mJXVX: target is busy.
INFO : Cleaning hanged build processes on the slave if there is any
Makefile:4574: recipe for target 'check-recursive' failed
Makefile:664: recipe for target '/home/collabora/jenkins/workspace/github_online_master_debug_vs_co-22.05/cypress_test/workdir/track/mobile/calc/bottom_toolbar_spec.js.done' failed
make: *** [check-recursive] Killed
```

from that ^ the only thing I see is `spec=calc/bottom_toolbar_spec.js` but I ran the test and it passes...

**Comment by pedropintosilva** [comment]
it says it fails on `make -C cypress_test run-desktop spec=writer/annotation_spec.js`

but locally it passes : 
image

**Comment by pedropintosilva** [comment]
This is the 6th time I retrigger with rebase ..

**Comment by eszkadev** [comment]
> Build timed out (after 60 minutes). Marking the build as aborted.

time out

**Review by eszkadev — APPROVED** [review]
looks ok

**Comment by eszkadev** [comment]
now it had real error wrt formulabar: you need to rebase

**Pull request merged**
