### PR TITLE
Notebookbar Selected Command visibility fix #2126

### LINKED ISSUE #2126: Notebookbar selected item layout
If there is an command selected at the notebookbar, the icon background is gray and the label is black

2021-04-24 00_41_44-ws-cdb0e9e9-e710-4615-863b-cac4f19fb659_0 - noVNC
Automatic Spell Check is selected and Word Count not

I suggested to a better layout for selected items

### PR DESCRIPTION
**Pull request by Andreas-Kainz**
Signed-off-by: andreas kainz <kainz.a@gmail.com>
Change-Id: Id3c4f4051894d89d2ba6d416825bcce9b73c424a

### Before
Screenshot_20210427_010803
Screenshot_20210427_010810

### After
Screenshot_20210427_012922
Screenshot_20210427_012942

The Label also has a background color AND a defined font color. In addition an outline give the selection some space.

### CODE REVIEW

**Comment by Andreas-Kainz** [comment]
@pedropintosilva as it's a visual change, I will wait here for your feedback.

**Comment by pedropintosilva** [comment]
- I have rebased with master
- I have targeted those switcher buttons

**Comment by pedropintosilva** [comment]
now @Andreas-Kainz you could add commit to this with your idea from https://github.com/CollaboraOnline/online/issues/2126 targetting buttons that are not global switchers

**Comment by pedropintosilva** [comment]
Thanks!

**Pull request merged**
