### PR TITLE
Text droplet (Teardrop): hide it when on desktop

### PR DESCRIPTION
**Pull request by pedropintosilva**
Signed-off-by: Pedro Pinto Silva <pedro.silva@collabora.com>
Change-Id: I6544845526c2e70bee7d6e3b193e9fb4931422c6

### CODE REVIEW

**Comment by thebearon** [comment]
I wanted to check this by emulating a desktop-sized touch device, and used the Asus Zenbook Fold preset in Chrome.
What I saw:
- the caret had a teardrop marker, (expected)
- the selection had no teardrop markers. (**not** expected)

Not sure if the device emulator works properly, but would be worth to double-check this (and I wonder how we differentiate between touch vs. non-touch compared to the usual desktop-mobile segmentation).

**Comment by thebearon** [comment]
I guess the touch part can be handled in a follow-up some other time. However, there seem to be tests depending on the droplet that are now failing.

**Comment by pedropintosilva** [comment]
> I guess the touch part can be handled in a follow-up some other time. However, there seem to be tests depending on the droplet that are now failing.

Good catch, thanks! I have forced pushed and rectified that.

**Review by thebearon — APPROVED** [review]
Works well, thanks!

**Pull request merged**
