### PR TITLE
Shortcuts-bar remove menubar

### PR DESCRIPTION
**Pull request by Andreas-Kainz**
all commands from menubar was added to the notebookbar
so no need for the hamburger menubar button

Signed-off-by: andreas kainz <kainz.a@gmail.com>
Change-Id: Icb283b40c269d2f92a29ad16dba8dda9d0f860d2

I didn't remove the code from getShortcutsBarData cause there are 3rd party apps that use this Shortcuts-bar to add there commands there. 

@pedropintosilva I checked all commands. All commands are available somewhere else. So it's possible to hide the hamburger menubar button.

### CODE REVIEW

**Comment by Andreas-Kainz** [comment]
image

**Comment by Andreas-Kainz** [comment]
The `.uno:Save` command I would suggest to move to the last-mod string #4070

**Comment by eszkadev** [comment]
nice, we can also remove widget implementation for that menu:
from `browser/src/control/Control.NotebookbarBuilder.js`
line: `this._toolitemHandlers['.uno:Menubar'] = this._menubarControl;`
and whole: `_menubarControl` function

**Review by pedropintosilva — APPROVED** [review]
it seems good, thansk @Andreas-Kainz

**Pull request merged**
