### PR TITLE
Copy loleaflet-api.html into code: cursorURL and Copy loleaflet-api.html into code: autoFitWidth

### PR DESCRIPTION
**Pull request by siddharth25pandey**
* Resolves: # [loleaflet-api.html: Copy documentation into source code as comments](https://github.com/CollaboraOnline/online/issues/2160#issue-867760580)
* Target version: master

### CODE REVIEW

**Review by pedropintosilva — CHANGES_REQUESTED** [review]
Welcome @siddharth25pandey and thanks for opening your first pull request : )

It seems that your text editor / IDE has changed all the indentation (it replaced tabs with spaces) and that, was pushed together with your changes to this pull request (as you can see when analysing the [files' diff](https://github.com/CollaboraOnline/online/pull/3120/files)

What's your text editor? Could you please

1. Fix those (either in the same PR or in a new one)
2. Check its settings  and make sure it respects:
  - `loleaflet/.eslintrc` for JS
  - `loleaflet/.stylelintrc.json` for CSS
3. Force push

**Comment by siddharth25pandey** [comment]
> Welcome @siddharth25pandey and thanks for opening your first pull request : )
> 
> It seems that your text editor / IDE has changed all the indentation (it replaced tabs with spaces) and that, was pushed together with your changes to this pull request (as you can see when analysing the [files' diff](https://github.com/CollaboraOnline/online/pull/3120/files)
> 
> What's your text editor? Could you please
> 
> 1. Fix those (either in the same PR or in a new one)
> 2. Check its settings  and make sure it respects:
> 
> * `loleaflet/.eslintrc` for JS
> * `loleaflet/.stylelintrc.json` for CSS
> 
> 1. Force push

@pedropintosilva I am using VS Code. It might caused due to code formatter extension was installed on my editor. Lemme try by creating a new PR

**Comment by siddharth25pandey** [comment]
@pedropintosilva Created a new [PR](https://github.com/CollaboraOnline/online/pull/3121)

**Comment by pedropintosilva** [comment]
@siddharth25pandey cool thanks, I will review that. Meanwhile and for future contributions you might want to install:
- https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint so it can read and follow `loleaflet/.eslintrc` for JS
- https://marketplace.visualstudio.com/items?itemName=whosydd.stylelint-config so it can read and follow `loleaflet/.stylelintrc.json` for CSS

**Comment by siddharth25pandey** [comment]
> @siddharth25pandey cool thanks, I will review that. Meanwhile and for future contributions you might want to install:
> 
> * https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint so it can read and follow `loleaflet/.eslintrc` for JS
> * https://marketplace.visualstudio.com/items?itemName=whosydd.stylelint-config so it can read and follow `loleaflet/.stylelintrc.json` for CSS

@pedropintosilva Sure, I will install the extensions.

**Pull request closed without merging**
