### PR TITLE
cool.html: append WOPISrc parameter to all JS, CSS & SVG loads

### PR DESCRIPTION
**Pull request by Rash419**
Change-Id: I1dd3902403a93914a8ad03b24bed5524a59e5aca

* Target version: master

### CODE REVIEW

**Review by mmeeks — APPROVED** [review]
Looks great to me - thanks Rash =) Did you check we clobber every URL by checking in the browser Network tab as things load ? =)

**Comment by Rash419** [comment]
> Looks great to me - thanks Rash =) Did you check we clobber every URL by checking in the browser Network tab as things load ? =)

@mmeeks I did. Do icons url also needs to be appended with WOPISrc  ?

**Comment by mmeeks** [comment]
Re: icons - yes, all URLs should have that.

**Comment by Rash419** [comment]
> Re: icons - yes, all URLs should have that.

OK, done

**Review by mmeeks — CHANGES_REQUESTED** [review]
So - I think we should abandon this for now - I suspect this will break browser caching; and that we should come up with a better approach & design here.

**Comment by mmeeks** [comment]
Also a duplicate pull request it seems; lets abandon this one for now.

**Pull request closed without merging**
