### PR TITLE
Update dependencies.

### PR DESCRIPTION
**Pull request by gokaysatir**
Signed-off-by: Gökay Şatır <gokaysatir@collabora.com>
Change-Id: I1ce4c803dd29f65a12f3ed8de323f131353c77cd

* Resolves: # 
* Target version: master 

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by timar** [comment]
@arrowd do you know what's wrong the FreeBSD CI?

**Comment by arrowd** [comment]
`image_family` should be changed to `freebsd-13-1-snap`, because 13.0 isn't supported anymore. Let's see if this fix the issue.

**Comment by gokaysatir** [comment]
Okay @arrowd thanks for checking :)

**Comment by arrowd** [comment]
This is a bug on our side, which is already fixed in Ports: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=268098

It'd take several days for this fix to reach binary packages, though, so the CI will stay broken for some time.

**Comment by gokaysatir** [comment]
> This is a bug on our side, which is already fixed in Ports: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=268098
> 
> It'd take several days for this fix to reach binary packages, though, so the CI will stay broken for some time.

Okay we will ignore this error until then. Thank you.

**Comment by arrowd** [comment]
This should be fixed now. Try re-running FreeBSD CI.

**Comment by timar** [comment]
My PR https://github.com/CollaboraOnline/online/pull/5582 passed the FreeBSD 13 check.

**Comment by arrowd** [comment]
Ah, this is an old CI run that is shown there. It should also pass now.

**Comment by gokaysatir** [comment]
I rebased the commit, yes then this should also pass. Thank you @arrowd.

**Comment by arrowd** [comment]
In its current form this PR only bumps FreeBSD version from 13.0 to 13.1. Your first version was also adding some dependencies.

**Comment by gokaysatir** [comment]
That's right, after you told that the bug is on FreeBSD side, i removed them. Those dependencies were for checking to see if there is a missing dependency.

**Pull request merged**
