### PR TITLE
calc: fix: named-range can't be used in function like SUM

### PR DESCRIPTION
**Pull request by Rash419**
Change-Id: Ia07c579b3bc81ce73f40e86e6e07a02098e7bf4c

* Target version: master 

- I tested the following with following partial test cases:
1. =SUM(te;te)
2. =SUM(te
3. =SUM(te; MAX(testrangename1;testrangename2)
4. = SUM(te; test1)

### CODE REVIEW

**Review by gokaysatir — CHANGES_REQUESTED** [review]
The second use of the named range seems to be wrong. Maybe we can use something like checking the chars from the end, one by one and then find the mismatching char etc?

Anyway, can you check the issue and if it's a real one, find another way, thanks :)

**Comment by Rash419** [comment]
Hey @gokaysatir, its working perfectly fine for check this out:
[Uploading Screencast from 2024-08-30 15-56-18.webm…]()

**Comment by Rash419** [comment]
@gokaysatir There are lot of cases your approach might not work as well
For example:
present partial formula: `=SUM(te; tes)`
functionName: `test4`
if user edit the first argument according to your approach checking from the last will  autocomplete on 2nd argument instead of first. I think we need think of different approach

**Comment by gokaysatir** [comment]
> @gokaysatir There are lot of cases your approach might not work as well For example: present partial formula: `=SUM(te; tes)` functionName: `test4` if user edit the 1st argument according to your approach checking from the last will autocomplete on 2nd argument instead of 1st. I think we need think of different approach

Agreed, thanks for evaluating it :)

**Review by gokaysatir — APPROVED** [review]
Thank you for the improvements. There is also one more use case:
* User can set a cell's value to a constant, say "lambda" for an engineering formula.
* Then they can pick that cell value and add it. They will be free from writing its value every time.
* Can you check the image below?




Since this improves the infrastructure here and solves the issues partially, let me approve. We will need a follow up for the remaining things.

Thanks :)

**Review by gokaysatir — APPROVED** [review]
Works with commands like below:
=SUM(test;   test2) / (MAX(test3;10) + test3)

I think it's ready. Thanks @Rash419 :)

**Pull request merged**
