### PR TITLE
Mobile: Writer context bottom toolbar

### PR DESCRIPTION
**Pull request by Andreas-Kainz**
there are context related commands at the mobile UI of writer
at the bottom toolbar.

the following context- related toolbars are available

- always
  Showsearchbar

- default, Text, DrawText
  B/I/U, Text Colors, Alignment, Bullets, increment decrement

- Table
  same as Text and in addition
  borderstyle, InsertRow menu, InsertColumn menu, MergeCells

- Draw, DrawLine, 3DObject, Multiobject, Graphic, DrawFontwork
  Wrap menu, Align Object menu, Arrange menu
  FlipVertical, FlipHorizontal

All commands are working and were tested.

## Screenshots

**default, Text, DrawText**
Screenshot_20211209_173016

**Table**
Screenshot_20211209_173148

**Draw, DrawLine, 3DObject, Multiobject, Graphic, DrawFontwork**
Screenshot_20211209_173047

Signed-off-by: andreas kainz <kainz.a@gmail.com>
Change-Id: I7f71cdf8b229a1120b1edc9d2d3cf3f0c0cad064

* Resolves: #2393
* Target version: master

### CODE REVIEW

**Comment by Andreas-Kainz** [comment]
@pedropintosilva I hake separate PR's for writer, calc and impress/draw. I think it's easier to review and for example calc has an open task. So I start with writer cause there everything work very well.

**Review by pedropintosilva — APPROVED** [review]
Perfect! We can then maybe think to expose actions in the cases where the toolbar gets blank, for example when a chart is selected we could expose "Area"; "wrap"; "Position and Size" from the top level mobilewizard (properties)

**Comment by pedropintosilva** [comment]
_checking cypress test locally_

**Comment by pedropintosilva** [comment]
@Rash419 I'm merging this because the failing test `calc/top_toolbar_spec.js` is not related to this PR or any change from it (since it only acts upon doctype text)

**Pull request merged**
