### PR TITLE
Fix black flashing when resizing the canvas

### PR DESCRIPTION
**Pull request by Cwiiis**
* Resolves: #10436
* Target version: master 

### Summary

With workers enabled, drawing is sometimes not synchronous. This causes a problem when resizing, which clears the canvas entirely and expects tile rehydration to happen synchronously afterwards. Work around this by redrawing the old canvas contents when resizing.

I considered more comprehensive fixes, but they all added a lot of complexity and used more memory than this. I think there's probably a better possible fix here of doing less work when resizing, but how to do that wasn't immediately obvious.

I've also bundled a much smaller fix which is the more common case, where we were dumping the old canvas contents and redrawing everything even when the canvas size wasn't changed (for example, copy/paste from another open sheet causes two null resizes to happen in both sheets).

### Checklist

- [x] I have run `make prettier-write` and formatted the code.
- [x] All commits have Change-Id
- [ ] I have run tests with `make check`
- [x] I have issued `make run` and manually verified that everything looks okay
- [x] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Review by caolanm — APPROVED** [review]

**Comment by caolanm** [comment]
I suspect the mocha_tests/CanvasSectionContainer.test.js failure in https://cpci.cbg.collabora.co.uk:8080/job/github_online_master_debug_vs_co-24.04/3334/console is triggered by this change?

**Comment by Cwiiis** [comment]
> I suspect the mocha_tests/CanvasSectionContainer.test.js failure in https://cpci.cbg.collabora.co.uk:8080/job/github_online_master_debug_vs_co-24.04/3334/console is triggered by this change?

Yes, the setup helper is using onResize as an initialisation function and I guess it's calling it with the default canvas width/height so it isn't doing the things that it expects to be done. I think I probably need an initialised flag or some such...

**Comment by Cwiiis** [comment]
I've changed the check to use `this.right` and `this.bottom`, which I assume are initialised to zero, instead of `this.canvas.width` and `this.canvas.height` - hopefully this will fix the tests.

**Comment by Cwiiis** [comment]
Looks like the alteration fixed the problem, the test failures now look unrelated to this change.

**Comment by caolanm** [comment]
I find I can reproduce (after a side journey of discovering my cypress always failed on --enable-debug https://github.com/CollaboraOnline/online/pull/10570) that the cypress failure here is triggered by the first patch.

I find that:
cd cypress_test && make check-desktop spec=calc/cell_cursor_spec.js

fails reproducibly but that moving the "this.clearMousePositions" in onResize before the early return make it pass

**Comment by Cwiiis** [comment]
> I find I can reproduce (after a side journey of discovering my cypress always failed on --enable-debug #10570) that the cypress failure here is triggered by the first patch.
> 
> I find that: cd cypress_test && make check-desktop spec=calc/cell_cursor_spec.js
> 
> fails reproducibly but something like
> 
> ```
>                 if (this.right === newWidth && this.bottom === newHeight) {
>                         this.clearMousePositions();
>                         this.reNewAllSections();
>                         return;
>                 }
> ```
> 
> passes, though probably negates the point of the patch then?

Yes, certainly the `reNewAllSections()` does a lot of work - I'll take a look at the test and see what's going on. If things are relying on a null resize just refreshing a bunch of unrelated stuff, that definitely sounds like a bad thing (and if they need that refresh, they should just call refresh - which at least wouldn't unnecessarily wipe the canvas contents).

**Comment by Cwiiis** [comment]
From what I can tell, the only difference with that small optimisation is now when `CalcTileLayer._handleSheetGeometryDataMsg` calls `_syncTileContainerSize`, which in turn calls `CanvasSectionContainer.onResize`, that last `onResize` gets short-circuited because the size hasn't changed. When I watch the test run, I don't see a problem, but then it's a 2-pixel difference, so I probably wouldn't... I kind of wonder if the test is well-crafted and this isn't some kind of race, but I have to assume it is and that it's a real problem. One thing I notice is that the other calls to `_syncTileContainerSize` in CalcTileLayer are preceded by a call to reNewAllSections - possibly this is just an ommission and that will fix this?

**Comment by Cwiiis** [comment]
> From what I can tell, the only difference with that small optimisation is now when `CalcTileLayer._handleSheetGeometryDataMsg` calls `_syncTileContainerSize`, which in turn calls `CanvasSectionContainer.onResize`, that last `onResize` gets short-circuited because the size hasn't changed. When I watch the test run, I don't see a problem, but then it's a 2-pixel difference, so I probably wouldn't... I kind of wonder if the test is well-crafted and this isn't some kind of race, but I have to assume it is and that it's a real problem. One thing I notice is that the other calls to `_syncTileContainerSize` in CalcTileLayer are preceded by a call to reNewAllSections - possibly this is just an ommission and that will fix this?

Yes, this appears to be the case, at least locally.

**Comment by Cwiiis** [comment]
I can reproduce the writer/searchbar_spec.js failure locally too, looking into it now. I hope/expect it'll be something similar.

**Comment by Cwiiis** [comment]
Just debugging this test - if I short-circuit the test so that it just loads the document and types 'sit' in the search field, for whatever reason, it doesn't highlight the first match, it goes to the third. On the other hand, if short-circuit the test just before it searches and search for 'sit' myself, it does go to the first. Maybe something up with `searchHelper.typeIntoSearchField`? Or some kind of race condition on load?

**Comment by Cwiiis** [comment]
I think this failure is likely a pre-existing race condition on load that the second patch in this PR exacerbates... I could be completely wrong of course :) Still digging...

**Comment by caolanm** [comment]
yeah, I've seen this test fail in other prs so I believe it is preexisting.

**Pull request merged**
