### PR TITLE
feat(helm): Add PodDisruptionBudget

### PR DESCRIPTION
**Pull request by alexstojda**
* Target version: master 

### Summary

Adds an optional [PodDisruptionBudget](https://kubernetes.io/docs/tasks/run-application/configure-pdb/) manifest to the chart

### Checklist

- [x] Code is properly formatted
- [x] All commits have Change-Id
- [x] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by alexstojda** [comment]
Build failure seems unrelated to my changes

```
1) Joining a document should not trigger an invalidation
       "before each" hook for "Join after document save and modify":
     CypressError: `cy.visit()` failed trying to load:

http://localhost:9900/browser/e87fe3843a/cypress-multiuser.html?lang=en-US&file_path=/home/collabora/jenkins/workspace/github_online_master_debug_vs_co-24.04_cypress_multi_user/cypress_test/workdir/data/multiuser/writer/invalidations-Join-after-document-save-and-modify-83t0c.odt

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > Error: connect ECONNREFUSED 127.0.0.1:9900
```

**Comment by mmeeks** [comment]
Yep; CI is not your issue - we're nursing that after a lot of changes towards the end of the red merge window =) Thanks for the change - Rash is the right person to review :-)

**Review by Rash419 — APPROVED** [review]
Works as expected, thanks

**Comment by alexstojda** [comment]
Amazing, thanks y'all! 

Whats the release schedule looking like for the helm chart?

**Comment by Rash419** [comment]
@alexstojda we can do it right now. Let me bump the chart version and CD pipeline should take care of it.
https://github.com/CollaboraOnline/online/pull/9417

**Pull request merged**
