### PR TITLE
feat(helm): dynconfig upload

### PR DESCRIPTION
**Pull request by genofire**
### Summary
config uploader on dynconfig (for allow lists over 1MB usefull)

### Checklist

- [x] Code is properly formatted
- [x] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [x] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by genofire** [comment]
i will and update, i just like to remove my "fork" after #5371 is solved:
https://github.com/genofire/collaboraonline-helm

**Comment by genofire** [comment]
Is ready to merge, now.

Maybe the next PullRequest adds languagetool support (if i found a nice image for it):
i have test it: https://github.com/genofire/collaboraonline-helm/pull/1

**Comment by Rash419** [comment]
Thanks I will review it : )

**Comment by Rash419** [comment]
@genofire can you please explain bit more about this feature ? AFAIK dynconfig is used to update wopi host/aliases without editing the COOL configuration file. What does this dynconfig upload mean ? Now you can upload the file to dynconfig server ?

**Comment by Rash419** [comment]
@genofire I see, configmap cannot store data more that 1 MB. So you file feature to upload the data to dync config server ?

**Comment by genofire** [comment]
exactly k8s / etcd kann only store a 1MB big file, so we host an special upload server on an pvc (with default 1Gi) for this file.


then we need to update the dynamic-config file, we just need an POST request like:
```bash
curl -XPOST -F 'data=@config.json' ingress-uploadserver/upload?key=TESTKEY
```

**Review by Rash419 — APPROVED** [review]
Thanks, Looks good to me

**Pull request merged**
