### PR TITLE
Toolbar/Notebookbar scroll-left/right use var's

### PR DESCRIPTION
**Pull request by Andreas-Kainz**
the buttons use the buttons look and hover effect.
Also an image was used, that can be themed.

image

See #4302

Signed-off-by: andreas kainz <kainz.a@gmail.com>
Change-Id: Ida8cc19cefa0fc8ff17e5f9d0b14869a313a4d25

### CODE REVIEW

**Comment by Andreas-Kainz** [comment]
This PR isn't finished. In addition to the new design, I suggest to arrange both buttons next to each other.

The existing solution has the disadvantage that when you want to scroll left/right you have to navigate with the mouse a lot.

I suggest that both buttons are right aligned so you can easier scroll left/right. At notebookbar you have space in the height, so you can have the buttons in two rows.

**Comment by Andreas-Kainz** [comment]
@pedropintosilva any feedback here?

**Comment by pedropintosilva** [comment]
> This PR isn't finished. In addition to the new design, I suggest to arrange both buttons next to each other.

I think it makes sense : ) and it would be a nice improvement, let me know once is finished or if you need any help here

> At notebookbar you have space in the height, so you can have the buttons in two rows.

Agreed :)

**Comment by Andreas-Kainz** [comment]
> and maybe we can make it more "embed" in the interface so it does still attention from the buttons that trigger actions image

good idea!

**Comment by Andreas-Kainz** [comment]
I add a new PR #4615

**Pull request closed without merging**
