### PR TITLE
cool#10630 doc electronic sign: improve error handling on bad client ID

### PR DESCRIPTION
**Pull request by vmiklos**
- **cool#10630 doc electronic sign: improve error handling on bad client ID**
- **common: fix clang 18 -Werror,-Wvla-cxx-extension**

### CODE REVIEW

**Comment by vmiklos** [comment]
https://cpci.cbg.collabora.co.uk:8080/job/github_online_master_debug_vs_co-24.04/3571/console failed in:

> unit-storage
> unit-initial-load-fail

retry to see if this is persistent.

**Comment by vmiklos** [comment]
https://cpci.cbg.collabora.co.uk:8080/job/github_online_master_debug_vs_co-24.04_cypress_desktop/3029/console failed in:

> writer/invalidations_spec.js

retry to see if this is persistent.

**Comment by vmiklos** [comment]
@caolanm could you please review this? Thanks.

My actual goal is the redirect method (vs the already working in-context one), but I found these in the meantime.

**Review by caolanm — APPROVED** [review]
In the error case I wonder if those those apis using RFC 7807/RFC 9457 or something totally unrelated?

**Comment by vmiklos** [comment]
Unfortunately seems unrelated; so far I only see a single "message" field in the JSON when we get a 404. I kept this as a console log, but perhaps in the future we want to rather show a popup, to be decided later.

**Pull request merged**
