### PR TITLE
avoid logging user content from spreadsheet cells

### PR DESCRIPTION
**Pull request by caolanm**
when anonymization is enabled

Change-Id: I0aee79411b79745078f98581094d2ddb1638fad6

* Resolves: # 
* Target version: master 

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Review by mmeeks — COMMENTED** [review]
Looks ok - but I'd really prefer cropping the user data (except in trace mode) at or near the logging site of a specific problematic message - to avoid having lots of re-parsing code for messages we generated ourselves around the place :-)

**Comment by cosminh11** [comment]
Should I open a fresh pull request for that, or one that would go into this PR's branch?

**Comment by caolanm** [comment]
making changes to this one is fine by me

**Comment by cosminh11** [comment]
opened #7212

**Pull request merged**
