### PR TITLE
Make sure that double fits into uint64_t

### PR DESCRIPTION
**Pull request by vmiklos**
Signed-off-by: Miklos Vajna <vmiklos@collabora.com>
Change-Id: Ic521383f71c1865ae18fc880b79493c52285e29b

### CODE REVIEW

**Comment by vmiklos** [comment]
writer/hamburger_menu_spec.js failed, let's try again.

**Comment by tml1024** [comment]
Looks OK to me. So this fixes a problem that shows up when the fuzzer intentionally feeds garbage to this, not in actual use, right? (I don't mean that it shouldn't be fixed anyway.)

**Comment by vmiklos** [comment]
> So this fixes a problem that shows up when the fuzzer intentionally feeds garbage to this, not in actual use, right?

Yes, this is about "don't crash on garbage input". I'll push it once CI passes.

**Comment by vmiklos** [comment]
Now writer/shape_properties_spec.js failed. (Just logging these here to see if there is a pattern or not.)

**Pull request merged**
