### PR TITLE
Calc: update geometry and position on new sheet insertion

### PR DESCRIPTION
**Pull request by eszkadev**
calc: use hashes for parts
    
part number is not enough when adding/deleting/moving the sheets

fixes regression from commit 703dae0ea2322cee3f7af3d293f6ab7307f4d91a
Don't save position data when not switching sheets

1. Open Calc
2. in the current sheet scroll down a but and make some rows bigger
3. right-click on the sheet tab, insert sheet before

Result: resized rows are still visible
Expected: new sheet has equal small rows

---------------------------------------

impress: move part hashes to the docstate

// unify code with calc

### CODE REVIEW

**Review by gokaysatir — CHANGES_REQUESTED** [review]
When there is only one sheet and if user adds a sheet before that one, grid is not updated.

* Open a spreadsheet with one sheet-tab.
* Resize a column
* Add a sheet before that one.
* The resized column is preserved in the new sheet.

Can you have a look?

**Comment by eszkadev** [comment]
Sorry, I didn't comment. If tested together with https://github.com/CollaboraOnline/online/pull/9784 then it works.
Now rebased.

**Comment by thebearon** [comment]
https://github.com/CollaboraOnline/online/pull/9784 has been reverted via #9793.

**Comment by eszkadev** [comment]
Sorry, I didn't comment. If tested together with https://github.com/CollaboraOnline/online/pull/9784 then it works.
Now rebased.

> When there is only one sheet and if user adds a sheet before that one, grid is not updated.
> 
>     * Open a spreadsheet with one sheet-tab.
> 
>     * Resize a column
> 
>     * Add a sheet before that one.
> 
>     * The resized column is preserved in the new sheet.
> 
> 
> Can you have a look?

this issue is fixed now, PR ready for review

**Review by gokaysatir — APPROVED** [review]
Thanks for the improvements :)

**Comment by thebearon** [comment]
> Sorry, I didn't comment. If tested together with #9784 then it works. Now rebased.

Let me note that this was reverted via #9793, and reapplied via #9853.

**Pull request merged**
