### PR TITLE
Presenter console:Add tooltip to all btns

### PR DESCRIPTION
**Pull request by Darshan-upadhyay1110**
* Resolves: # 
* Target version: master 

### TODO

- [ ] ...

### Checklist

- [ ] I have run `make prettier-write` and formatted the code.
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by hcvcastro** [comment]
Please simplify code using class src/control/Control.Tooltip.js

**Comment by hcvcastro** [comment]
to follow up patch, It looks Ok

**Comment by Darshan-upadhyay1110** [comment]
> Please simplify code using class src/control/Control.Tooltip.js

@hcvcastro i tried but it seems all tooltip shows on main screen and not on presenter console so for a quick thing i have to do this patch

**Review by hcvcastro — APPROVED** [review]

**Comment by hcvcastro** [comment]
I see, perhaps you can add options to improve the use case

**Comment by hcvcastro** [comment]
anyway let's focus on priority, we can improve later

**Comment by Darshan-upadhyay1110** [comment]
> anyway let's focus on priority, we can improve later

Sure thanks for the review

**Pull request merged**
