### PR TITLE
Private/timar/coolkitconfig

### PR DESCRIPTION
**Pull request by timar**
* Resolves: #3491 
* Target version: master

### CODE REVIEW

**Comment by vmiklos** [comment]
It looks like this means you can't do `coolconfig.xcu` edits locally without those changes showing up in `git diff` output. Is this a problem, or people never customize this in practice and we can just 'not care'?

**Comment by timar** [comment]
> It looks like this means you can't do `coolconfig.xcu` edits locally without those changes showing up in `git diff` output. Is this a problem, or people never customize this in practice and we can just 'not care'?

I did not think about this use case. Do you use this file that way?

**Comment by vmiklos** [comment]
> I did not think about this use case. Do you use this file that way?

No, I was just considering this a possibility. If we say that developers should not use custom coolwsd.xml settings for a longer period of time, then this is fine.

**Review by caolanm — APPROVED** [review]
looks reasonable to me

**Pull request merged**
