### PR TITLE
debug.html:use iframe as a target after submiting form

### PR DESCRIPTION
**Pull request by Rash419**
Signed-off-by: Rash419 <rashesh.padia@collabora.com>
Change-Id: I4b4e59721fb1deec709bc778a8e59a52fb466a3a

* Target version: master

### CODE REVIEW

**Review by kendy — APPROVED** [review]
The code looks great, thank you!  Would be good to improve the commit message though - instead of describing what the patch does (can be read from the code), focus on what issue it is solving.  Can you update that please?

**Comment by Rash419** [comment]
@kendy done : )

**Comment by Rash419** [comment]
> @kendy done : )



> The code looks great, thank you! Would be good to improve the commit message though - instead of describing what the patch does (can be read from the code), focus on what issue it is solving. Can you update that please?

@kendy done

**Review by kendy — APPROVED** [review]
Approving, thank you! :-)

**Comment by thebearon** [comment]
@Rash419 could you please also check the SSL disabled case? (one option is to use the `--disable-ssl` configure parameter, but it's easier to just switch the `enable` config item in `loolwsd.xml` to `false`)

**Pull request merged**
