### PR TITLE
Improve the scrollbars

### PR DESCRIPTION
**Pull request by Minion3665**
- Draw the railway for vertical and horizontal scrollbars
    - The railway should be 50% transparent on all apps, except for calc which should have a fully opaque railway

Signed-off-by: Skyler Grey <skyler3665@gmail.com>
Change-Id: I57975e52700f3b91782f9be40ad9864fc8c3baf2

* Target version: master 

### TODO
- [x] Display railways
- [x] Make the scrollbars attach to the side of the window (particularly in calc where a small part of the spreadsheet displays past the scrollbar railway)
- [x] Make the scrollbar railway have lower opacity on apps other than calc
- [x] Rewrite the writer/scrolling_spec cypress test
- [ ] ~~Make thumbs thinner when the scrollbar is not being used~~
- [ ] ~~(possibly) Make the trail thinner when the scrollbar is not being used~~
- [ ] ~~Fix the animating scrollbar resizing~~
- [ ] ~~Don't let the railway overflow the bounds (i.e. clip onto the column/row headers in calc)~~
- [ ] ~~Write new cypress tests for scrollbars (copy writer test over to calc to check the scrollbar is opaque etc.)~~

*Note: Crossed out tasks were planned but have (on request) been moved to be in a later PR [not yet opened]*

### Checklist

- [x] Code is properly formatted
- [x] All commits have Change-Id
- [x] I have run tests with `make check`
- [x] I have issued `make run` and manually verified that everything looks okay
- [x] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by Minion3665** [comment]
The failing test is one to test the scrollbars, so the reason it fails is fairly obvious. This test will need to be rewritten along with this PR
image

**Comment by Minion3665** [comment]
@pedropintosilva

**Review by pedropintosilva — CHANGES_REQUESTED** [review]
Thanks!

* Opacity is working: 
image

* It is opaque when on calc, thanks.
* Scrollbars should share the same colour (lighter one): 
image
* Also any element of the scrollbar should stop right before cell headers start
  * Right now it goes beyond that
  * This will automatically the switching between header and scrollbar in layer order. Example on hover cell header gets raised: 
image

**Review by gokaysatir — APPROVED** [review]
Thanks for the improvements, looks great :)

**Review by pedropintosilva — APPROVED** [review]
Thanks it looks good :) I still see some offset going on as if scrollbar is unable to reach position 0: 
image

**Review by pedropintosilva — APPROVED** [review]

**Comment by Minion3665** [comment]
@pedropintosilva the CI timed out, can you restart it please?

**Comment by pedropintosilva** [comment]
It seems Cypress has timed out on the CI side. I have re-triggered it.

**Comment by pedropintosilva** [comment]
> @pedropintosilva the CI timed out, can you restart it please?

I just noticed after I answered :p , sure

**Comment by eszkadev** [comment]
cypress test `destkop/calc/scrolling_spec.js` has to be checked and adjusted

**Comment by pedropintosilva** [comment]
Makes sense ^ now that we have changed offsets and change scrollbars on calc to start to be drawn after the cells all those cypress coordinates are probably wrong

**Pull request merged**
