### PR TITLE
wsd: disable ssl by default, enable ssl termination by default

### PR DESCRIPTION
**Pull request by vmiklos**
Signed-off-by: Miklos Vajna <vmiklos@collabora.com>
Change-Id: I7fd725a83b0e9ca1012f2c0e0c3bf038e5fa0059

### CODE REVIEW

**Comment by vmiklos** [comment]
Let's see if CI has any problems with this. A normal Linux make check passes; the intention is to have defaults which are close to how people typically use Online in production.

**Comment by mmeeks** [comment]
Looks good to me, but is 'make run' happy with this ? =)

**Comment by vmiklos** [comment]
> Looks good to me, but is 'make run' happy with this ? =)

Yes, it is, however there is an interesting trade-off here. On one hand, we want to use the non-ssl codepath in wsd for make run if the production scenario uses non-ssl as well. On the other hand, we want to use the ssl codepath for make run, so the browser gets https, similar to the production scenario.

The above version does non-ssl codepath for both cases, but now that you asked, it's probably more important to have https in the browser for make run, to be able to hit the tricky "js problem with ssl" cases with make run. Let me update the patch accordingly. (I.e. the config change is still the same, but explicitly request ssl for make run and disable ssl termination for cypress.)

**Comment by mmeeks** [comment]
Sounds fine - I think the SSL code-paths are more 'hairy' than the plain socket ones - so we should prolly be testing those as developers too =) thanks !

**Pull request merged**
