### PR TITLE
Calc: add commands to calc menubar view and insert

### PR DESCRIPTION
**Pull request by Andreas-Kainz**
Signed-off-by: andreas kainz <kainz.a@gmail.com>
Change-Id: I340474fba3cd61a3635ab9b657dc0ff358c08da8

* Resolves: # 
* Target version: master 

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by Andreas-Kainz** [comment]
Format menu will get also an update, but in a separate PR.

**Comment by Andreas-Kainz** [comment]
The test fail for top_toolbar_spec.js writer modul. This patch is for menubar calc only so I don't think that the failure is related to my patch.

**Comment by tzolnai** [comment]
> The test fail for top_toolbar_spec.js writer modul. This patch is for menubar calc only so I don't think that the failure is related to my patch.

Yes, it's unrelated. That failure was fixed in the meantime in the code. You can rebase your patch to make Jenkins pass the tests.

**Comment by pedropintosilva** [comment]
- I have review and it looks good @Andreas-Kainz
- Thanks for your newly merged pull-request @tzolnai 
- @Andreas-Kainz : I have rebased by:
  - `git fetch`
  - Checking out this pull request: either by `gh pr checkout 539` or by `git checkout calc-menubar`
  - `git rebase github/master` since in this we only have one clean commit so no need to do interactively etc
  - `git push -f` 

upon passing the tests I will merge it, thanks :+1:

**Pull request merged**
