### PR TITLE
tsc can report an error but create js output, so 2nd make's 'succeed'

### PR DESCRIPTION
**Pull request by caolanm**
so on failure remove the output so a second attempt doesn't appear to succeed

Change-Id: Ibc1f7d46c2946cdc6a4dbcd6181872fb12e19fb6

* Resolves: # 
* Target version: master 

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by caolanm** [comment]
I expect this to fail until https://github.com/CollaboraOnline/online/pull/8018 gets merged

**Comment by caolanm** [comment]
I expect this to fail until https://github.com/CollaboraOnline/online/pull/8018 gets merged

**Comment by caolanm** [comment]
failed as hoped for, so now rebased on top of the fix and hopefully we pass cleanly

**Comment by caolanm** [comment]
which it now does, so if something triggers a similar case again a rule like this would make it consistently fail

**Review by Minion3665 — APPROVED** [review]

**Pull request merged**
