### PR TITLE
Arrow keys traverse focus around notebookbar

### PR DESCRIPTION
**Pull request by CosmicOli**
* Resolves: #6960
* Target version: master 

### Summary
When focus is in the notebookbar, arrow keys allow focus to be moved.

Change-Id: Iccc9122f77c224e0190f25732ff9e4a24e4eab3e

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Review by gokaysatir — CHANGES_REQUESTED** [review]
This is a really beautiful solution :) A fresh idea that uses ray casting. Thank you for the PR.

* I think 1px of difference is a little to small. For example it takes 25 tries to find the next one. Maybe we can make it configurable, just to be safe. Then we can set it to at least 5 pixels - to be changed if causes some unwanted selections / behaviours.
* Also there are JS errors in the console - some null things etc.
* And if user presses down arrow when the bottom control is focused, map gets the focus. This may or may not be related to your changes but it'd be good to ask @pedropintosilva if we want it to behave like this.

Thanks for the improvements :)

**Comment by pedropintosilva** [comment]
yes I was aware of the initial report https://github.com/CollaboraOnline/online/issues/6960 and I agree

**Comment by pedropintosilva** [comment]
> And if user presses down arrow when the bottom control is focused, map gets the focus. This may or may not be related to your changes but it'd be good to ask @pedropintosilva if we want it to behave like this.

will check

**Comment by gokaysatir** [comment]
@CosmicOli thank you very much for the improvements :) I sent a small PR on top of this, in order to make this aligned with the latest changes.

**Review by gokaysatir — APPROVED** [review]

**Pull request merged**
