### PR TITLE
fix: changed "Twitter" to "𝕏 (Twitter)"

### PR DESCRIPTION
**Pull request by BandhiyaHardik**
Twitter is now known as 𝕏.

* Resolves: # https://github.com/CollaboraOnline/online/issues/7562
* Target version: master 

### Summary
It is updating Twitter to it's new name 𝕏.

### TODO

- [ ] ...

### Checklist

- [x] Code is properly formatted
- [x] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by Minion3665** [comment]
Heya, the change-id check is still failing, I think this is because of your merge commit (73c46843cddbef64b496c7184e2d4c57a403a2bb)

You probably wanted to rebase when you pulled, rather than just pulling... you probably want to do `git pull --rebase` to fix it (and then `push -f` again)

**Comment by BandhiyaHardik** [comment]
I will do it today.

**Comment by BandhiyaHardik** [comment]
@Minion3665 Thank You So Much for your help. Now it's passing change-id and DCO

**Review by Minion3665 — APPROVED** [review]
I'm confident checks will pass, when they do let's merge

**Pull request closed without merging**
