### PR TITLE
UI: PushButtonControl: Fix alignment in mobile

### PR DESCRIPTION
**Pull request by lpranam**
regression from b238f7e

Change-Id: Ide37eb5dddde34f7ccaf15858ca7b0e4069c0636

* Target version: master 

### Checklist

- [ ] I have run `make prettier-write` and formatted the code.
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by pedropintosilva** [comment]
Note: this fixes the following
image

**Review by pedropintosilva — APPROVED** [review]
Thanks

**Comment by pedropintosilva** [comment]
pressed retry on `COOL 24.04 unit tests w/o cypress`

**Comment by pedropintosilva** [comment]
this fix a regression and ultimately is not adding new css classes for the mobile case and it has passed cypress tests, so I think we can merge it

**Comment by lpranam** [comment]
more critical problem was with the dialogs

Screenshot_20240730_133945

**Pull request merged**
