### PR TITLE
Fix Issue #68 Ensure consistent function declaration

### PR DESCRIPTION
**Pull request by kandarppatel28**
I have done the code refactoring and removed all the function names for achieving constant function declaration as raised in the issue #68 .

### CODE REVIEW

**Comment by mrkara** [comment]
@kandarppatel28 Thank you for the patch! Could you please check the details of the failure (Change-Id check), and fix it?

A developer will review it after all checks are passed.

**Comment by kendy** [comment]
@kandarppatel28: Thanks so much :-)

Can you please update the patch that you have pushed to include the Change-Id:? To do that, you need to do:

cp .git/hooks/commit-msg .git/hooks/commit-msg # this installs the hook to add the Change-Id
git commit --amend # to update the commit miessage; on save, the hook will add the Change-Id

**Comment by kandarppatel28** [comment]
Thank you @mrkara and @kendy , I will update the patch, thanks @kendy for the guidance.

**Comment by kendy** [comment]
@kandarppatel28: Thank you so much for the update! I am sorry, I forgot to tell you to not touch the Vex parts, that is an external project :-(

Can you please update the patch the very last time to avoid touching the vex part?

Thank you in advance!

**Comment by kandarppatel28** [comment]
My bad @kendy, I didn't notice it, I will revert back the changes.

**Comment by kendy** [comment]
@kandarppatel28: I've squashed your 3 patches into one, and uploaded them as pull request 166 - hope that's fine for you? :-) - want to get your work in quickly...

In the meantime, let me close this one, because your work will get in under your name via the 166. Again - thanks so much for your work!

**Pull request closed without merging**
