### PR TITLE
remove-w2ui: css

### PR DESCRIPTION
**Pull request by eszkadev**
- remove w2ui css file
- remove w2ui-scroll-wrapper and replace with our scroll wrapper
- make separators and spacers not focusable when using Tab key

### CODE REVIEW

**Comment by eszkadev** [comment]
TODO: it requires some better   << , >>  icons in the buttons

**Comment by mmeeks** [comment]
Ooh - I thought we had this merged for 24.04 Szymon (?) =)

**Comment by eszkadev** [comment]
JS usage was completely removed. We only use few CSS rules.
This is safe change but I didn't merge it as it didn't look good due to poor icon

**Comment by mmeeks** [comment]
Would love to get this merged for the next 24.04 release in a couple of weeks(?)

**Comment by pedropintosilva** [comment]
Thanks, now pulling

**Comment by eszkadev** [comment]
@pedropintosilva updated the failing test and now it passed

**Review by pedropintosilva — APPROVED** [review]

**Pull request merged**
