### PR TITLE
Mobile Sidebar fix alignments

### PR DESCRIPTION
**Pull request by Andreas-Kainz**
header-left use max-width instead of min-width

image

Signed-off-by: andreas kainz <kainz.a@gmail.com>
Change-Id: Iebadf80864fb70e723bde9269a89d61ec43a2845

### CODE REVIEW

**Comment by Andreas-Kainz** [comment]
image

**Comment by Andreas-Kainz** [comment]
image

**Comment by eszkadev** [comment]
Hi, nice. Could you also test this with something with 3 tabs?
I think in Calc -> hamburger menu -> data -> validation   there are many tabs in mobile wizard

**Comment by Andreas-Kainz** [comment]
> Hi, nice. Could you also test this with something with 3 tabs? I think in Calc -> hamburger menu -> data -> validation there are many tabs in mobile wizard

Interested when I open an sidebar with more than 2 sections, there is first an overview page and you have to switch to one section. As I don't see that this issue is related to this PR I suggest to open an Issue and make a separate PR to fix it.

**Pull request merged**
