### PR TITLE
mutex and getMutex() removed

### PR DESCRIPTION
**Pull request by gozeloglu**
Signed-off-by: gozeloglu <gozeloglu@gmail.com>
Change-Id: I45e86d17c8c73787753245f95ef972a90893a305

* Resolves:  https://github.com/CollaboraOnline/online/issues/805
* Target version: master 

### Summary
I did changes in https://github.com/CollaboraOnline/online/issues/805 issue. 

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by gozeloglu** [comment]
Sorry for missing run `make check` command before creating pull request. I run `make check` command but I am getting following errors:

```
gitpod /workspace/online $ make check
Making check in .
make[1]: Entering directory '/workspace/online'
  CXX      kit/Kit.o
kit/Kit.cpp: In member function ‘bool Document::createSession(const string&, int)’:
kit/Kit.cpp:531:43: error: ‘_mutex’ was not declared in this scope
  531 |         std::unique_lock<std::mutex> lock(_mutex);
      |                                           ^~~~~~
kit/Kit.cpp: In member function ‘std::size_t Document::purgeSessions()’:
kit/Kit.cpp:574:47: error: ‘_mutex’ was not declared in this scope
  574 |             std::unique_lock<std::mutex> lock(_mutex, std::defer_lock);
      |                                               ^~~~~~
kit/Kit.cpp: In member function ‘virtual bool Document::onLoad(const string&, const string&, const string&, const string&
)’:
kit/Kit.cpp:878:43: error: ‘_mutex’ was not declared in this scope
  878 |         std::unique_lock<std::mutex> lock(_mutex);
      |                                           ^~~~~~
kit/Kit.cpp: In member function ‘virtual void Document::onUnload(const ChildSession&)’:
kit/Kit.cpp:944:47: error: ‘_mutex’ was not declared in this scope
  944 |             std::unique_lock<std::mutex> lock(_mutex);
      |                                               ^~~~~~
kit/Kit.cpp: In member function ‘virtual std::map<int, UserInfo> Document::getViewInfo()’:
kit/Kit.cpp:986:43: error: ‘_mutex’ was not declared in this scope
  986 |         std::unique_lock<std::mutex> lock(_mutex);
      |                                           ^~~~~~
kit/Kit.cpp: In member function ‘bool Document::forwardToChild(const string&, const std::vector<char>&)’:
kit/Kit.cpp:1318:47: error: ‘_mutex’ was not declared in this scope
 1318 |             std::unique_lock<std::mutex> lock(_mutex);
      |                                               ^~~~~~
In file included from /usr/include/x86_64-linux-gnu/c++/9/bits/c++allocator.h:33,
                 from /usr/include/c++/9/bits/allocator.h:46,
                 from /usr/include/c++/9/string:41,
                 from /usr/include/Poco/Bugcheck.h:22,
                 from /usr/include/Poco/Foundation.h:163,
                 from /usr/include/Poco/File.h:21,
                 from kit/Kit.cpp:12:
/usr/include/c++/9/ext/new_allocator.h: In instantiation of ‘void __gnu_cxx::new_allocator<_Tp>::construct(_Up*, _Args&& ...) [with _Up = Document; _Args = {std::shared_ptr<lok::Office>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::shared_ptr<TileQueue>&, std::shared_ptr<WebSocketHandler>, const unsigned int&}; _Tp = Document]’:
/usr/include/c++/9/bits/alloc_traits.h:482:2:   required from ‘static void std::allocator_traits<std::allocator<_CharT> >::construct(std::allocator_traits<std::allocator<_CharT> >::allocator_type&, _Up*, _Args&& ...) [with _Up = Document; _Args = {std::shared_ptr<lok::Office>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::shared_ptr<TileQueue>&, std::shared_ptr<WebSocketHandler>, const unsigned int&}; _Tp = Document; std::allocator_traits<std::allocator<_CharT> >::allocator_type = std::allocator<Document>]’
/usr/include/c++/9/bits/shared_ptr_base.h:548:39:   required from ‘std::_Sp_counted_ptr_inplace<_Tp, _Alloc, _Lp>::_Sp_counted_ptr_inplace(_Alloc, _Args&& ...) [with _Args = {std::shared_ptr<lok::Office>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::shared_ptr<TileQueue>&, std::shared_ptr<WebSocketHandler>, const unsigned int&}; _Tp = Document; _Alloc = std::allocator<Document>; __gnu_cxx::_Lock_policy _Lp = __gnu_cxx::_S_atomic]’
/usr/include/c++/9/bits/shared_ptr_base.h:679:16:   required from ‘std::__shared_count<_Lp>::__shared_count(_Tp*&, std::_Sp_alloc_shared_tag<_Alloc>, _Args&& ...) [with _Tp = Document; _Alloc = std::allocator<Document>; _Args = {std::shared_ptr<lok::Office>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::shared_ptr<TileQueue>&, std::shared_ptr<WebSocketHandler>, const unsigned int&}; __gnu_cxx::_Lock_policy _Lp = __gnu_cxx::_S_atomic]’
/usr/include/c++/9/bits/shared_ptr_base.h:1344:71:   required from ‘std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::_Sp_alloc_shared_tag<_Tp>, _Args&& ...) [with _Alloc = std::allocator<Document>; _Args = {std::shared_ptr<lok::Office>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::shared_ptr<TileQueue>&, std::shared_ptr<WebSocketHandler>, const unsigned int&}; _Tp = Document; __gnu_cxx::_Lock_policy _Lp = __gnu_cxx::_S_atomic]’
/usr/include/c++/9/bits/shared_ptr.h:359:59:   required from ‘std::shared_ptr<_Tp>::shared_ptr(std::_Sp_alloc_shared_tag<_Tp>, _Args&& ...) [with _Alloc = std::allocator<Document>; _Args = {std::shared_ptr<lok::Office>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::shared_ptr<TileQueue>&, std::shared_ptr<WebSocketHandler>, const unsigned int&}; _Tp = Document]’
/usr/include/c++/9/bits/shared_ptr.h:701:14:   required from ‘std::shared_ptr<_Tp> std::allocate_shared(const _Alloc&, _Args&& ...) [with _Tp = Document; _Alloc = std::allocator<Document>; _Args = {std::shared_ptr<lok::Office>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::shared_ptr<TileQueue>&, std::shared_ptr<WebSocketHandler>, const unsigned int&}]’
/usr/include/c++/9/bits/shared_ptr.h:717:39:   required from ‘std::shared_ptr<_Tp> std::make_shared(_Args&& ...) [with _Tp = Document; _Args = {std::shared_ptr<lok::Office>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::shared_ptr<TileQueue>&, std::shared_ptr<WebSocketHandler>, const unsigned int&}]’
kit/Kit.cpp:1919:36:   required from here
/usr/include/c++/9/ext/new_allocator.h:145:20: error: invalid new-expression of abstract class type ‘Document’
  145 |  noexcept(noexcept(::new((void *)__p)
      |                    ^~~~~~~~~~~~~~~~~~
  146 |        _Up(std::forward<_Args>(__args)...)))
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
kit/Kit.cpp:447:7: note:   because the following virtual functions are pure within ‘Document’:
  447 | class Document final : public DocumentManagerInterface
      |       ^~~~~~~~
In file included from kit/Kit.cpp:59:
kit/ChildSession.hpp:63:25: note:       ‘virtual std::mutex& DocumentManagerInterface::getMutex()’
   63 |     virtual std::mutex& getMutex() = 0;
      |                         ^~~~~~~~
make[1]: *** [Makefile:1983: kit/Kit.o] Error 1
make[1]: Leaving directory '/workspace/online'
make: *** [Makefile:3752: check-recursive] Error 1 
```


Can you guide me to solve that problem?

**Comment by mmeeks** [comment]
Please google / google-translate the error messages - which are there to help you =) hopefully if you do that, the solutions will become obvious.
Thanks !

**Comment by mmeeks** [comment]
Any joy with working ou twhat the error messages mean ? =) you need to remove the abstract getMutex() = 0; declaration in the  base class.

**Comment by mmeeks** [comment]
Thanks for attempting this one, someone else submitted a fix and I've done one on top of that here:     https://github.com/CollaboraOnline/online/pull/1232 - so lets close this for now.

Did you find something else to look at ?

**Pull request closed without merging**
