### PR TITLE
jsdialog: css: use CSS grid in icon view

### PR DESCRIPTION
**Pull request by eszkadev**
By default use well aligned 3 column grid.
In styles preview use old flex layout so
we don't change the behavior we had.

### CODE REVIEW

**Comment by eszkadev** [comment]
icongrid

**Review by codewithvk — DISMISSED** [review]
Can we add scrollbar like this ?

#transitions_icons {
    max-height: 40vh;
    overflow: scroll;
}

**Comment by eszkadev** [comment]
> Can we add scrollbar like this ?
> 
> #transitions_icons { max-height: 40vh; overflow: scroll; }

done, height limit to 40% of the screen

**Review by pedropintosilva — APPROVED** [review]
Tested, it seems good. Both on desktop and laptop (not possible to access this on mobile). I have also added additional transition thumbnails to, it works no matter the number even or uneven . Thanks

**Comment by pedropintosilva** [comment]
> > Can we add scrollbar like this ?
> > #transitions_icons { max-height: 40vh; overflow: scroll; }
> 
> done, height limit to 40% of the screen

also with this we avoid for the majority of cases 2 scroll bars which is awesome, thanks

**Pull request merged**
