### PR TITLE
common: avoid adding too large ints in the Rectangle ctor

### PR DESCRIPTION
**Pull request by vmiklos**
Signed-off-by: Miklos Vajna <vmiklos@collabora.com>
Change-Id: I17b5793c6a0d8a285f41af3846e7aacfc84f3c8c

### CODE REVIEW

**Comment by vmiklos** [comment]
<https://cpci.cbg.collabora.co.uk:8080/job/github_online_master_debug_vs_co-24.04_cypress_mobile/980/console> failed in impress/apply_font_shape_spec.js, retry.

**Comment by vmiklos** [comment]
https://cpci.cbg.collabora.co.uk:8080/job/github_online_master_debug_vs_co-24.04_cypress_multi_user/1043/console failed in sheet_operations_spec.js, retry.

**Comment by vmiklos** [comment]
https://cpci.cbg.collabora.co.uk:8080/job/github_online_master_debug_vs_co-24.04_cypress_mobile/984/console failed again in impress/apply_font_shape_spec.js, retry.

**Comment by vmiklos** [comment]
https://cpci.cbg.collabora.co.uk:8080/job/github_online_master_debug_vs_co-24.04_cypress_mobile/984/console fails in impress/apply_font_shape_spec.js for the 3rd time.

**Comment by vmiklos** [comment]
Rebased to be on top of f8a64d540786ceda706da45c094cc65bf6b57927

**Comment by vmiklos** [comment]
@caolanm could you please review this? Thanks.

I don't think there is sane way to get such input, so probably a "saturating add" is good enough here.

**Review by caolanm — APPROVED** [review]
ok by me I guess, though it isn't particularly aesthetically pleasing

**Comment by vmiklos** [comment]
> ok by me I guess, though it isn't particularly aesthetically pleasing

Fine, the next time I run into something like this, I'll extract this into some new `saturating_add()` in common/Util.hpp, I assume that would fit your taste better. :-)

**Pull request merged**
