### PR TITLE
private/pedro/cleanup buttons

### PR DESCRIPTION
**Pull request by pedropintosilva**
- Reduce CSS selectors targeting buttons
- Don't use vex btn default btn CSS classes (rename) 
- Remove master slides sidebar's btn CSS declarations
- Add mobile-wizard-titlebar-btn and remove hard coded rules
- Fix button order on newAnnotationVex
- Don't load btn hover status CSS rules when on mobile

### CODE REVIEW

**Review by eszkadev — COMMENTED** [review]
great! reduction of complex css rules is waht we need :)

I've only noticed one issue on mobile:
act_find_repl_mob

after I click active button (it is selected then?) in mobile find and replace dialog - it becomes white with white text

**Comment by eszkadev** [comment]
and cypress is looking for old classes: `AssertionError: Timed out retrying after 6000ms: Expected to find element: `.vex-dialog-form .vex-dialog-button-primary`, but never found it. Queried from element: <body.vex-open>`

**Comment by pedropintosilva** [comment]
> great! reduction of complex css rules is waht we need :)
> 
> I've only noticed one issue on mobile:

Thanks, and good catch I could only see that in chrome which led me to do a proper more generic fix for that (don;t use hover styles when not on desktop)

**Comment by pedropintosilva** [comment]
> and cypress is looking for old classes: `AssertionError: Timed out retrying after 6000ms: Expected to find element: `.vex-dialog-form .vex-dialog-button-primary`, but never found it. Queried from element: <body.vex-open>`

Yup I have rebase it and add the needed adjustments.

**Comment by pedropintosilva** [comment]
**NOT READY TO BE MERGED:** I need to test:
* Cypress locally
* Welcome Dialog, feature dialog, conflict dialog on desktop and mobile

**Comment by pedropintosilva** [comment]
Merging as this was approved already

**Pull request merged**
