### PR TITLE
Cleanup remote config

### PR DESCRIPTION
**Pull request by Rash419**
* Resolves: # 
* Target version: master

### CODE REVIEW

**Comment by genofire** [comment]
Could we put it outside of `ENABLE_FEATURE_LOCK` ?

**Comment by Rash419** [comment]
> Could we put it outside of `ENABLE_FEATURE_LOCK` ?

@genofire not really, to use feature locking COOL should be built with --enable-feature-lock flag ENABLE_FEATURE_LOCK is set based on the flag has been passed or not  : )

**Review by kendy — APPROVED** [review]
All looks good to me, thank you! :-)

**Pull request merged**
