### PR TITLE
improve HelmChart

### PR DESCRIPTION
**Pull request by genofire**
Make this HelmChart to state of the Art ;)

with nice optional Features:
- Monitoring with Prometheus:
  - ServiceMonitor
  - Alerting (with default PrometheusRules)
  - Grafana Dashboards

- Dynamic Config reloading:
   - extra nginx-pod (+service, + ingress)
   - json will be generated from values.yaml into a ConfigMap

---

After Merge, please Release it to https://artifacthub.io/

### CODE REVIEW

**Comment by pedropintosilva** [comment]
Thanks @genofire I think the issue with FreeBSD test has been fixed with https://github.com/CollaboraOnline/online/commit/b412d61ca862688c91ede459c80e98427002cac6 . Could you please rebase this PR?

**Comment by genofire** [comment]
Done

**Comment by lpranam** [comment]
@genofire I tried to reach the Collabora online on "http://chart-example.local:<port>/" it leads me to default haproxy backend. am I doing anything wrong here...?

**Comment by genofire** [comment]
@lpranam i do not know, what do you mean - do you have your `values.yml` for me to understand?

PS: We use nginx, because we need multiple LBs / Ingress-Pods (and thats works with the constant hash / the annotation `upstream-by-hash`).

**Comment by genofire** [comment]
Any update @lpranam ?

**Comment by genofire** [comment]
@mmeeks do you review?

**Comment by lpranam** [comment]
@genofire i will review sorry for the delay :)

**Comment by genofire** [comment]
@lpranam does we want to meet (in an jitsi) to review together?

**Comment by lpranam** [comment]
@genofire that sounds great. I'd be available throughout the week at whatever time is convenient for you. I have had a glance through the PR several times but couldn't review it thoroughly. Sorry for that.

**Comment by genofire** [comment]
I updated the README - here you see the result:
https://github.com/genofire/collabora-online/blob/feat/helm/kubernetes/helm/README.md

**Review by lpranam — APPROVED** [review]

**Comment by genofire** [comment]
I create a dedicate issue for creating an repository for helm:

#5371

**Pull request merged**
