### PR TITLE
browser: fix "Uncaught TypeError: getSectionWithName"

### PR DESCRIPTION
**Pull request by hcvcastro**
Change-Id: I660ca7cbc9e6ce6eaa3834ebd3c2829c606bc045
Signed-off-by: Henry Castro <hcastro@collabora.com>

### CODE REVIEW

**Review by caolanm — APPROVED** [review]
what was it actually an instanceof?

**Comment by hcvcastro** [comment]
>> what was it actually an instanceof?

It is something like dynamic_cast in C++, but Javascript called prototypes

**Comment by caolanm** [comment]
yeah, I get that :-). I mean it wasn't a CanvasSectionContainer so what was passed there?

**Comment by hcvcastro** [comment]
>> yeah, I get that :-). I mean it wasn't a CanvasSectionContainer so what was passed there?

I have checked all assignments, but somewhere the app.sectionContainer is assigned an empty object
or other type during certain condition (reloading, reconnecting document, etc)

**Pull request merged**
