### PR TITLE
Upgrade @braintree/sanitize-url to version 6.0.2

### PR DESCRIPTION
**Pull request by timar**
Change-Id: I7afa9596b31def59e0a151ddff437285d9b916ea

* Resolves: # 
* Target version: master 

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by timar** [comment]
@Rash419 what did I do wrong (if anything)? The sha512 check of the updated module fails on FreeBSD 13.

**Comment by Rash419** [comment]
> @Rash419 what did I do wrong (if anything)? The sha512 check of the updated module fails on FreeBSD 13.

@timar tbh no idea, everything looks fine .Why does freebsd generate different sha!

**Review by Rash419 — APPROVED** [review]
tbh no idea, everything looks fine .Why does freebsd generate different sha!

maybe this helps?
npm cache clean --force
npm cache verify

**Comment by timar** [comment]
https://github.com/CollaboraOnline/online/pull/6124 will be better.

**Pull request closed without merging**
