### PR TITLE
fix: metrics change doc_pid to doc_info use pid as label

### PR DESCRIPTION
**Pull request by genofire**
@mmeeks i like to have the pid value as an label so it would be use on the other metrics for lookup with [promql group_left](https://prometheus.io/docs/prometheus/latest/querying/operators/#group-modifiers)

i believe it is usefull to rename that metrics afterwards my suggestion `doc_info` as an representer for all the metrics

After this change i will enrich the PrometheusRules / Alerts to show more information (based on the instance and pid label) - current i believe the following should work:
`doc_active_views * group_left(doc_info)`

### Checklist

- [x] Code is properly formatted
- [x] All commits have Change-Id
- [x] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Review by mmeeks — APPROVED** [review]
Seems reasonable to me as/when it passes CI =) Not a huge fan of changing the interface here, but it was never that beautiful.
Depending on feedback we should consider versioning the URL we get the metrics from I think.

**Review by mmeeks — CHANGES_REQUESTED** [review]
So of course - the code also needs to compile =) 

wsd/AdminModel.cpp:1197:42: error: stray ‘\’ in program
                "pid=\"" << pid << "\"} 1"\n";
                                          ^
wsd/AdminModel.cpp:1197:44: error: missing terminating " character [-Werror]
                "pid=\"" << pid << "\"} 1"\n";

etc. ... =)

**Comment by genofire** [comment]
(or `doc_open`)

**Review by mmeeks — APPROVED** [review]
Well - of course, its not beautiful to have this dummy '1' value - and no doubt a prometheus purist would want us to generate gigabytes of duplicate data for no benefit here =) and I'm not interested in being pushed in that direction - but this seems to me a reasonable approach for now =)

Thanks !

**Comment by genofire** [comment]
it is very common in prometheus to have an info or up metric with the value if 1

the database / prometheus should compress it nice -but yes that is transmit some more bytes

**Comment by mmeeks** [comment]
Good to know - thanks =)

**Pull request merged**
