### PR TITLE
Read helper line styles from CSS vars.

### PR DESCRIPTION
**Pull request by gokaysatir**
So they are configurable.

Change-Id: I29f9944bc2d51e184b585ada7b5ac452fc379f38

* Resolves: # 
* Target version: master 

### TODO

- [ ] ...

### Checklist

- [ ] I have run `make prettier-write` and formatted the code.
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by pedropintosilva** [comment]
looks good but I'm getting 

```javascript
Exception TypeError: app.sectionContainer is undefined emitting event commandvalues: { "comments": { "comment16": { "id": 16, "author": "", "dateTime": "2024-05-14T09:07:40", "text": "A torchlight is tool used to emit light in dark environment\u000a", "parthash": 15, "rectangle": "0, 0, 450, 366"}, "comment17": { "id": 17, "author": "", "dateTime": "2024-05-14T09:08:22", "text": "Water is an essential item to energy\u000a", "parthash": 15, "rectangle": "567, 0, 450, 366"}, "comment18": { "id": 18, "author": "", "dateTime": "2024-05-14T13:03:12", "text": "Comments added\u000a", "parthash": 15, "rectangle": "1134, 0, 450, 366"}}}
_onCommandValuesMsg@http://localhost:9980/browser/e5908457/src/layer/tile/ImpressTileLayer.js:167:13
_onMessage@http://localhost:9980/browser/e5908457/src/layer/tile/CanvasTileLayer.js:1050:18
_onMessage@http://localhost:9980/browser/e5908457/src/core/Socket.js:1208:33
_emitSlurpedEvents@http://localhost:9980/browser/e5908457/src/core/Socket.js:342:30
_queueSlurpEventEmission/that._slurpTimer<@http://localhost:9980/browser/e5908457/src/core/Socket.js:299:22

```

**Comment by pedropintosilva** [comment]
_pulling core now_

**Comment by pedropintosilva** [comment]
still getting

```js
Exception TypeError: app.sectionContainer is undefined emitting event commandvalues: { "comments": { }}
_onCommandValuesMsg@http://192.168.100.6:9980/browser/e5908457/src/layer/tile/ImpressTileLayer.js:167:13
_onMessage@http://192.168.100.6:9980/browser/e5908457/src/layer/tile/CanvasTileLayer.js:1050:18
_onMessage@http://192.168.100.6:9980/browser/e5908457/src/core/Socket.js:1208:33
_emitSlurpedEvents@http://192.168.100.6:9980/browser/e5908457/src/core/Socket.js:342:30
_queueSlurpEventEmission/that._slurpTimer<@http://192.168.100.6:9980/browser/e5908457/src/core/Socket.js:299:22

```

**Comment by pedropintosilva** [comment]
* online at commit e5908457666665380cd01eb6c5c2418e4f6fe7be (HEAD -> private/gokay/styles-follow-up, origin/private/gokay/styles-follow-up)
* core at commit 42593961a79cbef130f2cf9823687d793b9bf47b (HEAD -> distro/collabora/co-24.04, origin/distro/collabora/co-24.04)

**Comment by eszkadev** [comment]
> still getting
> 
> ```js
> Exception TypeError: app.sectionContainer is undefined emitting event commandvalues: { "comments": { }}
> _onCommandValuesMsg@http://192.168.100.6:9980/browser/e5908457/src/layer/tile/ImpressTileLayer.js:167:13
> _onMessage@http://192.168.100.6:9980/browser/e5908457/src/layer/tile/CanvasTileLayer.js:1050:18
> _onMessage@http://192.168.100.6:9980/browser/e5908457/src/core/Socket.js:1208:33
> _emitSlurpedEvents@http://192.168.100.6:9980/browser/e5908457/src/core/Socket.js:342:30
> _queueSlurpEventEmission/that._slurpTimer<@http://192.168.100.6:9980/browser/e5908457/src/core/Socket.js:299:22
> ```

`make clean` probably is needed

**Review by eszkadev — APPROVED** [review]
didn't test, but looks good

**Comment by gokaysatir** [comment]
Thanks for checking :)

**Pull request merged**
