### PR TITLE
Dark mode integration and view separation

### PR DESCRIPTION
**Pull request by OFFTKP**
Needs patch https://gerrit.libreoffice.org/c/core/+/148615 to work

Should separate views based on formatting marks between multiple browsers

Tests are currently failing because the patch above hasn't been merged

### CODE REVIEW

**Comment by OFFTKP** [comment]
Set DCO to passing, it was failing pointing that commit "Fix UI selection bug" was not signed off correctly even though it was signed. If this is a mistake let me know.

**Review by eszkadev — COMMENTED** [review]
JS part looks good

**Comment by mmeeks** [comment]
Lets get this in then =)

**Comment by thebearon** [comment]
This needs the 22.05 backport of the following core gerrit patch to build, no?
https://gerrit.libreoffice.org/c/core/+/148776

**Comment by mmeeks** [comment]
We don't want dark mode in 22.05 - too risky.

**Comment by thebearon** [comment]
Oh, ok so online master doesn't build on core 22.05 anymore, got it.

**Pull request merged**
