### PR TITLE
Use package-lock.json instead of shrinkwrap

### PR DESCRIPTION
**Pull request by jblemee**
Signed-off-by: Jean-Baptiste Lemée <git@lemee.co>
Change-Id: I52f299b9b623e80383663111df3318881ec3d0ea

* Resolves: #4008
* Target version: master 

### TODO

- [x] Revert  #3815

### Checklist

- [x] Code is properly formatted
- [x] All commits have Change-Id
- [ ] I have run tests with `make check`
- [x] I have issued `make run` and manually verified that everything looks okay
- [x] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by pedropintosilva** [comment]
Hi @jblemee  and, albeit in draft state, thanks for pushing your first PR !

This seems a good idea, but somehow if I remember correctly there was something mentioned in one of the community meetings along the line of "we shouldn't pin versions by pushing shrinkwrap" but maybe I'm just confused. Could you check this @alessioalex-1and1 @timar ?

**Review by alessioalex-1and1 — APPROVED** [review]

**Comment by pedropintosilva** [comment]
Ah so I just talked with @gokaysatir and we cannot do this if we want to keep the possibility of building without internet

**Comment by pedropintosilva** [comment]
nevertheless this error should now be fixed with @lpranam 's commit: https://github.com/CollaboraOnline/online/pull/4146/files

**Comment by pedropintosilva** [comment]
@jblemee I noticed that your branch https://github.com/hyperlex/online/commits/chore/remove-shrinkwrap is not up to date and so it does not include that above commit mentioned. Could you test it again?

**Comment by jblemee** [comment]
> @jblemee I noticed that your branch https://github.com/hyperlex/online/commits/chore/remove-shrinkwrap is not up to date and so it does not include that above commit mentioned. Could you test it again?

I've test and it's works now with shrinkwrap. Maybe we should update shrinkwrap with a version compatible with lasts npm/node versions ?

**Pull request closed without merging**
