### PR TITLE
sync COOL icon path with LibO path #213

### PR DESCRIPTION
**Pull request by Andreas-Kainz**
Change-Id: I539fdb96f37036837a455badc4ab078954fc796d

### CODE REVIEW

**Comment by DarkknightAK** [comment]
@pedropintosilva be careful with this PR. In general it update all links to use

`images/colibre/LibO subfolder` instead of
`images/`

so it will be in the future way easier to sync icon work between COOL and LibO. In addition Icon Theme selection will be very easy with replace colibre with another folder name where another icon theme is.

**Comment by DarkknightAK** [comment]
In general it's a good foundation for future icon work.

**Comment by rizmut** [comment]
Just curious, why do you add a subdirectory `24` under `cmd`? LibO icon theme has no such additional directory except `32` and some more directories for localized icons

**Comment by DarkknightAK** [comment]
> Just curious, why do you add a subdirectory `24` under `cmd`? LibO icon theme has no such additional directory except `32` and some more directories for localized icons

cause I don't like it in LibO to have 2.000 images in one folder. Sepration there would be welcome to.

**Comment by tzolnai** [comment]
> > Just curious, why do you add a subdirectory `24` under `cmd`? LibO icon theme has no such additional directory except `32` and some more directories for localized icons
> 
> cause I don't like it in LibO to have 2.000 images in one folder. Sepration there would be welcome to.

This patch is about to be sync with LO and in the same patch, you introduce something new. It might be better to create two separate patches for that.
Also, did you tested the application, whether the icons are working everywhere? I'm not a big fan of this kind of huge change, hundreds of code lines, without actual testing. Who knows what is broken by this. There are no automatic tests for icons. I think it's would be better to do this step-by-step with smaller patches.

**Comment by tzolnai** [comment]
> I think it's would be better to do this step-by-step with smaller patches.

Under step-by-step I mean, you can start with the mobile wizard for example. You can change the icon paths related to the mobile wizard (see loleaflet/css/mobilewizard.css), you can test whether all icons on the mobile wizard is displayed correctly and then go on with other areas.

**Comment by Andreas-Kainz** [comment]
I only checked COOL cause I only build COOL.

I complete understood, that an structural change is always not nice, but COOL now hast 800 icons in LibO there are 4.000 icons and maintain two places will be a huge problem in the future.

**Comment by tzolnai** [comment]
> I only checked COOL cause I only build COOL.
> 
> I complete understood, that an structural change is always not nice, but COOL now hast 800 icons in LibO there are 4.000 icons and maintain two places will be a huge problem in the future.

Not that is the question here whether we need to change this or not. The question is how to do it without breaking anything. If it's so important to achieve, then we can invest the time to test this change right? Testing would need smaller patches because testing this huge patch is very hard. If I test it I find an issue in it, you update the patch, and then I need to check hundreds of lines again, and then I might find something again, you update the patch, and I need to check hundreds of code again. I think it's clear why it's hard to review this kind of change.
We are developing software here, so we can't just hope that this change does not break anything.

**Comment by Andreas-Kainz** [comment]
This is no huge patch, there are two options. It work to have the icons available or not.

**Comment by tzolnai** [comment]
> This is no huge patch, there are two options. It work to have the icons available or not.

You are 100% sure about this, right? OK. It was my opinion here, that it would be better to test it, but let's forget about it.

**Comment by Andreas-Kainz** [comment]
@kendy can you review this patch and check if the icon loading will work.

Thanks

**Comment by tzolnai** [comment]
> This is no huge patch, there are two options. It work to have the icons available or not.

I just had a quick look at the code. I found a getImageURL() method which assumes the images are directly under the 'images' folder.:
https://github.com/CollaboraOnline/online/blob/d0edfeabbdc969a9a66cf90976a63c2f4403a6d3/loleaflet/src/core/LOUtil.js#L99

I did not find in your commit, that it changed this method. So I assume everywhere where this method is used the icons won't be displayed. The code could do anything with the image path, that's why it might be a problem if you are not testing your changes.

**Comment by Andreas-Kainz** [comment]
Thanks for the feedback. will wait, maybe someone can help me with this patch, otherwise I will close it.

**Comment by rizmut** [comment]
> > Just curious, why do you add a subdirectory `24` under `cmd`? LibO icon theme has no such additional directory except `32` and some more directories for localized icons
> 
> cause I don't like it in LibO to have 2.000 images in one folder. Sepration there would be welcome to.

If you want to sync with LibO icon, please keep it the same without the change. Otherwise, we could propose this kind of change to LibO first. I am not a fan of directory change. Moreover, I prefer to change LibO icon directory and naming to follow FreeDesktop convention but sure it should be another topic for LibO not here

**Comment by Andreas-Kainz** [comment]
Thanks for the feedback. I'm thinking about and and the result is, that I will close the request, cause
- meeks prefer to have an script that generate a global svg image from the separate ones, so the icon loader need a change to load the "big" svg image instead of every single image. And if I would fix this patch an change for the icon loader is needed, so it would be only a change after a change. So better start with the script where the rearrangement is better suited.

**Pull request closed without merging**
