### PR TITLE
Fix Rename document button works only on tabbed view #7109

### PR DESCRIPTION
**Pull request by pedropintosilva**
We forgot to dispatch it

Signed-off-by: Pedro Silva <pedro.silva@collabora.com>
Change-Id: If1ae87ee8029d469d092680437023d389efcdec7

### CODE REVIEW

**Comment by pedropintosilva** [comment]
fixes #7109

**Review by Darshan-upadhyay1110 — APPROVED** [review]
Tetsed and working. thanks :)

**Comment by Darshan-upadhyay1110** [comment]
@pedropintosilva i saw bit strange thing there. if you do rename from compact mode focus does not goes into Textinput popup. can you confirm that ?

**Comment by pedropintosilva** [comment]
Oh so, please create an issue for that. Thanks for catching that

**Pull request merged**
