### PR TITLE
Add viewMode property to TileLocation to ensure that correct delta is…

### PR DESCRIPTION
**Pull request by gokaysatir**
… replaced with the new one.

Change-Id: I376563989cf58fdbddd65f73315d4a898ceac93c

* Resolves: # 
* Target version: master 

### TODO

- [ ] ...

### Checklist

- [ ] I have run `make prettier-write` and formatted the code.
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by gokaysatir** [comment]
@caolanm hello, can you have a look when you have time?

**Review by caolanm — APPROVED** [review]
This looks reasonable to me. How did the problem manifest, wrong tiles on switching in and out of master view in presentations?

**Comment by gokaysatir** [comment]
> This looks reasonable to me. How did the problem manifest, wrong tiles on switching in and out of master view in presentations?

Indeed i worked on a similar issue on Impress. I wanted to keep the previews on "standart" view while the page is at "notes" view. It was experimental. I couldn't succeed. This commit is for something i noticed while trying to understand the root cause.

**Comment by gokaysatir** [comment]
The tile painting request is sent to the core side with the correct info. Core side checks the view mode before painting the tile. If the current view mode is different than the requested tile's view mode, core side temporarily switches the view mode. Everything seems normal and the rendered tile is sent to the browser with the correct view mode. But the content is wrong. Content is from the current view mode, not from the requested one.

I hoped that core side doing right and server has an issue and tried this and some other things. Didn't work but still wanted to prepare this commit in case it may be helpful.

**Pull request merged**
