### PR TITLE
fix(helm): aliases is an regex

### PR DESCRIPTION
**Pull request by genofire**
### Checklist

- [x] Code is properly formatted
- [x] All commits have Change-Id
- [x] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Review by Rash419 — CHANGES_REQUESTED** [review]
for example if I have

```
collabora:
  aliasgroups:
    - host: "http://192.168.1.112"
      aliases: ["test.collabora.online", "test.integrator.online"]
```
The output as per the current patch is 
`aliasgroup1: http://192.168.1.112|test.collabora.online|test.nextcloud.online`

But we want
`aliasgroup1: http://192.168.1.112, http://test.collabora.online|text.nextcloud.online`

**Comment by Darshan-upadhyay1110** [comment]
Hi @genofire! I hope you're doing well. I noticed @Rash419 has suggested a few small changes on the patch. Could you kindly take a look at them when you have a moment? It would be wonderful to get this patch into master as soon as possible. Thanks a ton! 😊

**Comment by genofire** [comment]
hmm, maybe i have not try it with `protocol://` on aliases.

so an example like on @Rash419 does not work on my privat setup.

**Comment by eszkadev** [comment]
@Rash419 what should we do with this PR?

**Pull request closed without merging**
