### PR TITLE
Add back removed breaks from TopToolbar, see #3184

### PR DESCRIPTION
**Pull request by kcmaxwell**
Breaks were removed in commit df925222a2c4ce94024b8df7eeb0d014e2d82271

Signed-off-by: Kristopher Maxwell <kristophermaxwellc@gmail.com>
Change-Id: I376207d654ccbe98fc1d1b4b84363748190ab646

* Resolves: # 3184
* Target version: master 

### TODO

- [ ] ...

### Checklist

- [x] Code is properly formatted
- [x] All commits have Change-Id
- [ ] I have run tests with `make check`
- [x] I have issued `make run` and manually verified that everything looks okay
- [x] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by pedropintosilva** [comment]
Thanks @kcmaxwell ! I have re-triggered the cypress test since it failed the build midway

**Comment by pedropintosilva** [comment]
@kcmaxwell I have tested your patch but I think this was removed in the past because the drop-down menus already count as visual dividers making the additional bezels unecessary:

image

**Comment by kcmaxwell** [comment]
Ok, would you still like to have the space between the dropdowns and the other icons, just no bezels?
I could do that with the CSS margin property on the dropdowns.
Let me know if that sounds good or if you want something different.

**Comment by pedropintosilva** [comment]
Good idea : ) I think that would be the best, retaining white space but without the visual clutter of those breaks (since the drop-down menus being already different visually from the surrounding elements already do that role)

**Comment by pedropintosilva** [comment]
maybe even better would be to add something like `visible: false` on the JS side that would then set `visibility: hidden` instead of having loosely breaks in the CSS set to hidden and then people forget about them : p

---

Note: The `hidden: true` set `display` to `none` in the CSS side

**Comment by pedropintosilva** [comment]
or if you prefer or easier to add the .hidden class which we already have on the css side : )

**Review by pedropintosilva — APPROVED** [review]
You what I will merge this : ) and then we can make them hidden since you already waited some time

**Pull request merged**
