### PR TITLE
Fix mobile-ui-tabs Misaligned Headings

### PR DESCRIPTION
**Pull request by Darshan-upadhyay1110**
Signed-off-by: Darshan-upadhyay1110 <darshan.upadhyay@collabora.com>
Change-Id: Ib982a59c141d937c7f92eb9684b91fc7f2548df5

- will fix Misaligned ui-tabs in mobile wizard
- also added scrollable property that will handle more fields in tabs if it does not fit into screen

* Resolves: #7638 
* Target version: master 

### Summary

- Before
image

-After

image

### CODE REVIEW

**Comment by Darshan-upadhyay1110** [comment]
> disable that menu item completely when on mobile because as we stand it's unusable.

@pedropintosilva `menu item` means the Property tag inside `files` ?

**Comment by pedropintosilva** [comment]
Yes

**Comment by Darshan-upadhyay1110** [comment]
@pedropintosilva i have removed `Property` menu item for mobile.  Still there are many places where we have this Mialligned headings issue.

For Ex: On Mobile 
- go to Download As
- selcted Downaload as PDF 

Before this patch that dialog looks very odd.

so Pedro can we go with this flex property for better User interaction in mobile.


About 

> Also I have noticed that it seems we are ignoring .button-primary that is correctly assigned to the OK button on desktop but on mobile-wizard we loose that andthen every single pushbutton is styled as primary button.

I will fix that in other PR with better description so this will not overlap with current issue

**Comment by pedropintosilva** [comment]
I'm also worried about that margin change

**Review by pedropintosilva — APPROVED** [review]

**Comment by pedropintosilva** [comment]
Looks good but I didn't test the second commit , can we get @Rash419 to give a +2?

**Review by Rash419 — APPROVED** [review]
thanks

**Pull request merged**
