### PR TITLE
remove-w2ui #6: convert sheets toolbar to JSDialog

### PR DESCRIPTION
**Pull request by eszkadev**

### CODE REVIEW

**Comment by eszkadev** [comment]
3 times in a row only `calc/focus_spec.js` failed - which also fails in other PRs - we can merge

**Review by gokaysatir — COMMENTED** [review]
* On mobile readonly mode, i cannot see the tablist.
* There is JS error when adding new tabs and also while loading the document:
`"cannot call methods on tooltip prior to initialization; attempted to call method 'option' emitting event calcfunctionlist"`
* "Protect Sheet" doesn't work but i think that's another issue.

Other than these, it's beatiful:) Thanks.

**Comment by gokaysatir** [comment]
I think below one should be Calc only, or it causes errors on loading of different formats (Writer for example):
* `this.map.uiManager.sheetsBar.show();`

**Comment by eszkadev** [comment]
> * On mobile readonly mode, i cannot see the tablist.

Fixed.


>     * There is JS error when adding new tabs and also while loading the document:
>       `"cannot call methods on tooltip prior to initialization; attempted to call method 'option' emitting event calcfunctionlist"`
> 
>     * "Protect Sheet" doesn't work but i think that's another issue.

These 2 are present even before patch. I will try to fix/report later

**Comment by eszkadev** [comment]
only calc/focus_spec.js failed, which is broken

**Review by gokaysatir — APPROVED** [review]
Thanks @eszkadev :)

**Comment by eszkadev** [comment]
First https://github.com/CollaboraOnline/online/pull/8583 has to be merged

**Review by pedropintosilva — APPROVED** [review]
tested, it works, thanks!

**Pull request merged**
