### PR TITLE
Dark Mode: box-shadow tooltip fix

### PR DESCRIPTION
**Pull request by Andreas-Kainz**
tooltip use var colors.

**Before**
Screenshot_20230428_224357

**After**
Screenshot_20230428_230408

**After light mode**
Screenshot_20230428_230424

Change-Id: Ic8addda2167be038d7e435d424448824be73127a

### CODE REVIEW

**Review by pedropintosilva — CHANGES_REQUESTED** [review]
Thanks but it would be better if a shadow is not light then the background bellow otherwise it wouldn't be a shadow ; )

**Comment by Andreas-Kainz** [comment]
good point, but in dark-mode the background color is #000 so darken than black isn't possible.

**Comment by pedropintosilva** [comment]
right so the way I see it we have two options:

1. make sure the background is not pure black and reserve that for shadows 
2. Or remove shadow altogether from those
  * The tooltip's background is lighter so maybe we don't need nothing else. But if you find out that the contrast is still a bit poor (difficult to distinguish where the tooltip ends and where the bellow elements start) then we can add a light border to the tooltips

**Comment by pedropintosilva** [comment]
I'm merging this as it is already an improvement. Thanks! I will then push a follow up (dark mode only)

**Review by pedropintosilva — APPROVED** [review]

**Pull request merged**
