### PR TITLE
private/pedro/jsdialogs rm css n fix bg n radiobtn

### PR DESCRIPTION
**Pull request by pedropintosilva**
- JSdialog, p element: Remove #table- from CSS it was removed from JS
- Macro dialog: remove unecessary CSS rules
- JSdialog: Don't add margins to multiple inner containers
- Do not add padding too all td jsdialog cells
- JSdialog: fix disabled radio buttons border
- Dialogs should have white background

### CODE REVIEW

**Comment by eszkadev** [comment]
Macro dialog should be checked, can we just remote these rules?

**Comment by eszkadev** [comment]
BTW Macro dialog is missing in notebookbar, it was in the hamburger menu

**Comment by pedropintosilva** [comment]
> BTW Macro dialog is missing in notebookbar, it was in the hamburger menu

Yes I noticed when I tried to test both macro dialogs (warning and the selection dialog)

**Comment by pedropintosilva** [comment]
> Macro dialog should be checked, can we just remote these rules?

what is remote? (maybe a typo = remove?) . I have tested everything seems fine (a part from other color regression from css vars)

**Review by gokaysatir — APPROVED** [review]
Thanks for the improvements @pedropintosilva :)

**Pull request merged**
