### PR TITLE
browser: simplify logServer

### PR DESCRIPTION
**Pull request by hcvcastro**
Use "fetch()" function to save logging client data
to server side.

Change-Id: I8b6a94b7ad7ae02ca00666759e3695867df4d372
Signed-off-by: Henry Castro <hcastro@collabora.com>

### CODE REVIEW

**Comment by caolanm** [comment]
This seems to be stuck in some ci limbo, maybe we need another rebase here?

**Comment by caolanm** [comment]
If you could get the conflicts resolved and this up to date with master, then this good be a good time to try and merge this.

**Comment by hcvcastro** [comment]
Thanks, rebased

**Review by caolanm — APPROVED** [review]
There's quite a lot here, but looks sane to me and this looks to be a good window of time to merge

**Pull request merged**
