### PR TITLE
jsdialog: transparent color in picker

### PR DESCRIPTION
**Pull request by eszkadev**
solves issue with not remembered transparent (no fill) color selected from the picker

### CODE REVIEW

**Comment by eszkadev** [comment]
no cpp change, codeql fails due to some env issues (dependencies...)

**Review by Darshan-upadhyay1110 — COMMENTED** [review]
Font color in notebook bar is not working. There is also  dropdown arrow is missing

Current:

image

Expected:

image

**Comment by eszkadev** [comment]
> Font color in notebook bar is not working. There is also dropdown arrow is missing
> 
> Current:
> 
> image
> 
> Expected:
> 
> image

please do `make clean` :)

**Review by Darshan-upadhyay1110 — APPROVED** [review]
Code looks code good to me! Thanks :)

**Pull request merged**
