### PR TITLE
Fix Issue #68 Ensure consistent function declaration

### PR DESCRIPTION
**Pull request by kendy**
Change-Id: I0a2b8deba4fdb48a8aed92b26d749a00f5f37ada

### CODE REVIEW

**Comment by kendy** [comment]
@kandarppatel28: To make things easier for you, I've squashed your patches into one - hope that's fine. So I suggest that we merge your patch via this pull request, and close the pull request 77.

In the meantime, can you please create a separate pull request for the rest of those functions with unwanted declaration?  I still see them in loleaflet/src/layer/marker/TextInput.js ...

Thank you in advance!

**Comment by kandarppatel28** [comment]
Thank you @kendy for squashing the patches into one, it looks cleaner now. We can go with this pull request.

My bad, I missed out some of them, I will create a new PR for the same in a while, Thank you once again. :)

**Comment by kendy** [comment]
So it's in, congratulations on your first patch to Collabora Online! :-)

**Comment by kandarppatel28** [comment]
Thank you @kendy for the opportunity and also for helping and guiding me at each step. Looking forward for more contributions. :)

As discussed I have created a different PR #167 for TextInput.js, Please review it.

**Pull request merged**
