### PR TITLE
Fixed missing % upon pressing the escape key

### PR DESCRIPTION
**Pull request by rparth07**
Change-Id: I0ac901dc0d5a53e82be70d3c89f17e03b8872989

* Resolves: #5342 
* Target version: master 

### Summary
Empty area when pressing `Esc`

### Checklist

- [x] Code is properly formatted
- [x] All commits have Change-Id
- [ ] I have run tests with `make check`
- [x] I have issued `make run` and manually verified that everything looks okay
- [x] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by Rash419** [comment]
@pedropintosilva will do

**Review by pedropintosilva — APPROVED** [review]
I have tested and it works, thanks! +1 but I need +2 from someone else

**Comment by pedropintosilva** [comment]
> @pedropintosilva will do

awesome thanks!

**Comment by pedropintosilva** [comment]
I have checked the logs from the failing GCC check  and there is nothing. I have re-triggered the test

**Review by Rash419 — APPROVED** [review]
Tested it with IMEs : ), LGTM!

**Pull request merged**
