### PR TITLE
menubar: disabled hideMenuBar button in readonly mode

### PR DESCRIPTION
**Pull request by CodingwithKetan**
Change-Id: I5658869c7f901dfdec26c7329f48da54bb179c0e

* Resolves: #9746 
* Target version: master 

### Checklist

- [X] I have run `make prettier-write` and formatted the code.
- [X] All commits have Change-Id
- [ ] I have run tests with `make check`
- [X] I have issued `make run` and manually verified that everything looks okay
- [X] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Review by Darshan-upadhyay1110 — COMMENTED** [review]
@CodingwithKetan, great patch to fix the issue! 

However, would it be possible to remove the element from the list in read-only mode instead of just disabling it? My concern is that if we add more options in the future, disabling them could become a never-ending cycle. It would be more effective to hide the element entirely rather than just disabling it.

@eszkadev please correct me if i an wrong here  :)

**Comment by Darshan-upadhyay1110** [comment]
Also i have just did a small try on code it seems easy to this hide task so this can be still a `easy hack` 😉

**Comment by CodingwithKetan** [comment]
> Also i have just did a small try on code it seems easy to this hide menubar option and not just disable it so this can be still a `easy hack` 😉

Thank you @Darshan-upadhyay1110 for the feedback! I see your point about the potential issue with simply disabling elements. I’ll update the patch to remove the element from the list in read-only mode instead of just disabling it.

**Comment by CodingwithKetan** [comment]
> @CodingwithKetan, great patch to fix the issue!
> 
> However, would it be possible to remove the element from the list in read-only mode instead of just disabling it? My concern is that if we add more options in the future, disabling them could become a never-ending cycle. It would be more effective to hide the element entirely rather than just disabling it.
> 
> @eszkadev please correct me if i an wrong here :)



> Also i have just did a small try on code it seems easy to this hide menubar option and not just disable it so this can be still a `easy hack` 😉

Thank you @Darshan-upadhyay1110  for the feedback! I see your point about the potential issue with simply disabling elements. I’ll update the patch to remove the element from the list in read-only mode instead of just disabling it.

**Review by eszkadev — APPROVED** [review]
looks ok, but yes, would be good to just remove that item from RO view

**Comment by Darshan-upadhyay1110** [comment]
> looks ok, but yes, would be good to just remove that item from RO view

Sure let's merge this PR and as followup work we will do the next steps :)

**Comment by Darshan-upadhyay1110** [comment]
Thanks, @CodingwithKetan looking forward to more commits in upstream. Checkout the issues section, a bunch of issues are waiting for a contributor.

Happy hacking 😉

**Pull request merged**
