### PR TITLE
fix(COOLWSD): Fix a typo `remove_font_config`->`remote`

### PR DESCRIPTION
**Pull request by joshtrichards**
* Target version: master 

Signed-off-by: Josh Richards <josh.t.richards@gmail.com>
Change-Id: Ib2c5bc13ded052aa3e76b0dcb280b32d7febedb5
    
### Checklist

- [x] Code is properly formatted
- [x] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [x] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by pedropintosilva** [comment]
Thanks for the PR!/Could you please add at the end of your commit message a sign off ?:

Signed-off-by: Author Name <authoremail@example.com> 

Otherwise DCO check will not pass: 
https://github.com/CollaboraOnline/online/pull/9385/checks

**Review by timar — APPROVED** [review]

**Comment by timar** [comment]
@joshtrichards Thanks for the fix!

**Comment by Darshan-upadhyay1110** [comment]
thanks and welcome @joshtrichards  ! But please after looking and proceed according to @pedropintosilva  's notes do sign- off your commits and Add Change -id.

Sign-off
(DCO)

You should only do this if:

To add your Signed-off-by line to every commit in this branch:

Ensure you have a local copy of your branch by [checking out the pull request locally via command line](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally).
In your local branch, run: git rebase HEAD~1 --signoff
Force push your changes to overwrite the branch: git push --force-with-lease origin Switch-between-spreadsheet-tabs
Change-id
How to obtain Change-Id in commit message :

copy commit hook :
cp .git-hooks/commit-msg .git/hooks/commit-msg

And then amend your commit message :
git commit --amend
git push -f

**Comment by joshtrichards** [comment]
Oops! I even know better. :)

**Comment by pedropintosilva** [comment]
@Darshan-upadhyay1110 please add the change id and merge it

**Pull request merged**
