### PR TITLE
notebookbar: add Insert Frame to the Insert tab

### PR DESCRIPTION
**Pull request by vmiklos**
This allows the creation of floating tables when an entire table is
selected by the time we dispatch .uno:InsertFrame.

Signed-off-by: Miklos Vajna <vmiklos@collabora.com>
Change-Id: Ia0614d47275eb8d9127c496a0b06a8993c5f9989

### CODE REVIEW

**Comment by vmiklos** [comment]
@pedropintosilva once you're back, could you please state if you're OK to put this new insert frame button on the insert tab in the notebookbar, under qr code? The other option I considered is fontwork, but that's tricky (hidden for non-ODF), so it's not ideal to put an always-on frame button under it. It looks like this:

image

Thanks.

**Comment by pedropintosilva** [comment]
I have no objection. But @gokaysatir might want to check if this will affect the access keys (we are trying to set each to already known letters from MSO but there are a limit set of keys and positions )

**Comment by vmiklos** [comment]
unit-copy-paste failed, let's try again.

**Comment by vmiklos** [comment]
> https://cpci.cbg.collabora.co.uk:8080/job/github_online_master_debug_vs_co-23.05/8487/

And again unit-copy-paste is one of the failed tests. I wonder that broke there.

**Comment by vmiklos** [comment]
> https://cpci.cbg.collabora.co.uk:8080/job/github_online_master_debug_vs_co-23.05/8491/

Progress, now only unit-bad-doc-load fails, but that passes for me locally.

**Comment by vmiklos** [comment]
> https://cpci.cbg.collabora.co.uk:8080/job/github_online_master_debug_vs_co-23.05/8515/

Better, now we fail in cypress tests.

**Comment by eszkadev** [comment]
pplease rebase, writer/statusbar_spec.js will be fixed

**Comment by vmiklos** [comment]
> please rebase, writer/statusbar_spec.js will be fixed

Done. :-)

**Comment by eszkadev** [comment]
We need also menubar entry in the compact mode: `browser/src/control/Control.Menubar.js`

**Comment by vmiklos** [comment]
@caolanm could you please review this? Thanks.

@pedropintosilva already said OK from the design point of view. I checked that the a11y shortcut is unique, so I believe it should be good enough.

**Comment by vmiklos** [comment]
> We need also menubar entry in the compact mode: `browser/src/control/Control.Menubar.js`

Ah, let me fix that. I hoped we killed the menubar by now.

**Review by caolanm — APPROVED** [review]
I think its uncontroversial if it now passes ci

**Pull request merged**
