### PR TITLE
Configurable allow scripting

### PR DESCRIPTION
**Pull request by Ashod**
- wsd: jail: unlink before copying files
- wsd: allowing scripting is now configurable

### CODE REVIEW

**Comment by Ashod** [comment]
@mmeeks: updated to signal that this config is to control *external* scripts only and added fixme to convert the envars to command-line params. As mentioned elsewhere, the fact that there is currently no mechanism for shared config inside the forkit/kit process is what needs to be implemented. But agreed that piling up more envars is just bad form.

**Comment by Ashod** [comment]
@mmeeks: I've renamed and clarified that this controls external scripts only. Any chance to take another look please? Looks like a decent security feature, and saves a some 10s of MBs in the jails.

**Comment by mmeeks** [comment]
I'm very far from a fan of adding 'security' settings - these attract -intense- interest from pedants and time-wasters who can waste staggering amounts of other people's lives ;-) [ you think I'm bad pushing back on this one - but that's nothing compared to the security circus ].

Also - I expect we would leave this setting on by default, thus giving no real size saving - but more of a documentation burden, more maintenance complexity etc. Whatever we add here we have to maintain its semantics -forever- (it's a security setting) - and I really am not a fan of the initial semantic: it seems an accident of trying to save 10Mb from the systemplate in one specific way.

I guess if we have to have it it has to be really clear ideally in a verbose comment  that it is about disabling this single remote UNO command execution feature, and that anything else is a bonus. But ideally it doesn't live in a section called 'security' but in some: <transient_unloved_advised_optimization_tweaks> section ;-) or something; then we can have it break and/or change in later releases. Even then - from a support perspective having that around and having to know it exists, and/or check for it when we find weird behavior in the field is a serious pain.

Can we push it to a branch for later reference if we need it and abandon it for now ? I would prefer to spend time pre-initializing / loading python (then trying to fight its new threads away so we can use forkit properly) - than have a new setting we don't want =)

**Comment by mmeeks** [comment]
Oh, and we solved most of the real-world performance problem here anyway by getting the hard-linking EXDEV issue done I think.

**Comment by Ashod** [comment]
Shelving for now.

**Pull request closed without merging**
