### PR TITLE
calc: restore correct position on tab operations

### PR DESCRIPTION
**Pull request by mcecchetti**
This patch improves restoring a view to the previous position on tab
switching, tab operations (move, insert, delete) and tab operations
undo/redo

Signed-off-by: Marco Cecchetti <marco.cecchetti@collabora.com>
Change-Id: Iadce3d4922d94c3417dc9aeddfce5c9018ccdb09

### CODE REVIEW

**Comment by mcecchetti** [comment]
This patch works better with https://gerrit.libreoffice.org/c/core/+/164651

**Review by eszkadev — CHANGES_REQUESTED** [review]
Patch has conflicts, it is not clear if it is needed or not?

**Comment by mcecchetti** [comment]
I see, as soon as I've time to work on this I'll fix conflicts

**Comment by eszkadev** [comment]
closing as there is SheetSwitch thing already, I'm not aware about many bugs in this area and it has conflicts currently

**Pull request closed without merging**
