### PR TITLE
browser: add last modification timeout setting

### PR DESCRIPTION
**Pull request by alessioalex-1and1**
Signed-off-by: Alexandru Vlăduţu <alexandru.vladutu@1and1.ro>
Change-Id: I04891ce23e0f250243d9453bfecb0570683cae7a

* Resolves: #4194 4194
* Target version: master 

### Summary

Add configurable setting for the minimum timeout / delay until the "Last modified" message is displayed.

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by alessioalex-1and1** [comment]
ping @pedropintosilva

**Review by eszkadev — COMMENTED** [review]
looks sensible, but could you please rebase?

**Comment by pedropintosilva** [comment]
I think this PR is an old version of https://github.com/CollaboraOnline/online/pull/4531 right @gmasei11 ?

**Comment by mmeeks** [comment]
Assuming an old version of the other patch.

**Pull request closed without merging**
