### PR TITLE
Add Scrollbar onmouseover effect

### PR DESCRIPTION
**Pull request by codewithvk**
Change-Id: If52d3b4b3afa8ad629adeeda6fd65c7a80776b06

* Resolves: #5473 
* Target version: master

### CODE REVIEW

**Comment by codewithvk** [comment]
@pedropintosilva Can you please review this PR or add appropriate reviewers?

**Comment by pedropintosilva** [comment]
Hi @codewithvk and sorry for the delay, I missed notification for this PR. 

I will check it but @eszkadev could you please review it?

**Review by pedropintosilva — APPROVED** [review]
Thanks ! it works, The scrollbar gets thicker on hover. I wonder if we could do a follow up where we animate that increase

**Review by eszkadev — APPROVED** [review]

**Comment by codewithvk** [comment]
> Thanks ! it works, The scrollbar gets thicker on hover. I wonder if we could do a follow up where we animate that increase

I think we can give try to JavaScript Animation. [Ref : JavaScript animations](https://javascript.info/js-animation) If it sound good, I will create PR for this fix.

**Comment by Minion3665** [comment]
@codewithvk re:
> I think we can give try to JavaScript Animation using setTimeOut and timing functions. [Ref : JavaScript animations](https://javascript.info/js-animation) If it sound good, I will create PR for this fix.

yep, that sounds like it would work! go ahead

**Comment by codewithvk** [comment]
Created Follow up PR for animation : #7218

**Pull request merged**
