### PR TITLE
Private/gokay/shape handles

### PR DESCRIPTION
**Pull request by gokaysatir**
* Resolves: # 
* Target version: master 

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by eszkadev** [comment]
it's green week, we have to wait ~2 weeks to merge

**Comment by gokaysatir** [comment]
> all the handles doesn't work when trying to use them second time

This one is interesting. Reported also before and i couldn't reproduce this. I'll check again. Thanks for the review. I'll also check the rotation handle usage.

**Comment by gokaysatir** [comment]
I increased the radius of rotation handle. I hope it is easier to pick it now. I can't reproduce the issue with second usages of handles.

**Comment by eszkadev** [comment]
Rotation still doesn't work propery. It just works sometimes. When I try 10 times, 5 of them fail to drag...

**Comment by gokaysatir** [comment]
> Rotation still doesn't work propery. It just works sometimes. When I try 10 times, 5 of them fail to drag...

I see, let's get this in since this improves the situation. Then i'll prepare a follow up and check this issue deeply.

**Review by eszkadev — APPROVED** [review]

**Pull request merged**
