### PR TITLE
Make export EPUB/PDF always with options dialog (Calc, Impress, Draw)

### PR DESCRIPTION
**Pull request by timar**
Signed-off-by: Andras Timar <andras.timar@collabora.com>
Change-Id: I86880ab3c54994554ab7f91921d028f962318e5a

* Resolves: # 
* Target version: master 

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by timar** [comment]
@eszkadev I found an issue with the non grouped download icons in case of Writer, therefore I did not change Control.NotebookbarCalc.js, Control.NotebookbarDraw.js, and Control.NotebookbarImpress.js.
There are no icons. Shoud we duplicate icons with the new names or is there a better workaround? I hope there is, because otherwise we have to duplicate icons in themes as well.
image

**Comment by eszkadev** [comment]
> @eszkadev I found an issue with the non grouped download icons in case of Writer, therefore I did not change Control.NotebookbarCalc.js, Control.NotebookbarDraw.js, and Control.NotebookbarImpress.js. There are no icons. Shoud we duplicate icons with the new names or is there a better workaround? I hope there is, because otherwise we have to duplicate icons in themes as well. image

@timar yes, we have aliasing for icons:
https://github.com/CollaboraOnline/online/blob/6d1b392b7ef9ea529708b653240125ab2871af9c/browser/src/control/Control.JSDialogBuilder.js#L2331

**Comment by timar** [comment]
I added the icon aliases, but the buttons do not have labels, only tooltips. Probably it's acceptable.
image
I will add them to Calc, Draw and Impress, too.

**Comment by timar** [comment]
On the other hand, it looks a bit ugly in Calc:
image

**Comment by eszkadev** [comment]
> I added the icon aliases, but the buttons do not have labels, only tooltips. Probably it's acceptable

Fixed missing text. inlineLabel property will do the job

**Review by eszkadev — APPROVED** [review]

**Pull request merged**
