### PR TITLE
Private/darshan/backport 10027

### PR DESCRIPTION
**Pull request by Darshan-upadhyay1110**
List of the PR's from which I cherry-picked the commits:

1. https://github.com/CollaboraOnline/online/pull/10027
2. https://github.com/CollaboraOnline/online/pull/10252
3. https://github.com/CollaboraOnline/online/pull/10286
4. https://github.com/CollaboraOnline/online/pull/10296
5. https://github.com/CollaboraOnline/online/pull/10304

* Resolves: # 
* Target version: master 

### TODO

- [ ] ...

### Checklist

- [ ] I have run `make prettier-write` and formatted the code.
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by Darshan-upadhyay1110** [comment]
Do not merge yet, I got some build errors i need to test this first...

**Comment by Darshan-upadhyay1110** [comment]
> Do not merge yet, I got some build errors related to cpp files, all good in online.But just to be sure i need to test this...

@eszkadev @pedropintosilva all okay we can merge this now :)

**Comment by pedropintosilva** [comment]
Thanks @Darshan-upadhyay1110 one commit seems to be missing
```
commit 845d216a39270f936e10c71cc67d0fb3fde14cc9
Author: Pedro Pinto Silva <pedro.silva@collabora.com>
Date:   Mon Oct 21 11:49:14 2024 +0200

    Dropdowns: Don't force any specific width
```

**Review by pedropintosilva — CHANGES_REQUESTED** [review]
^

**Comment by timar** [comment]
@Darshan-upadhyay1110 did you inted this PR for COOL 24.04.8.4 "quick fix" release, if it happens? Because normal COOL 24.04.8.3 was released last week. Is this an urgent fix?

**Comment by pedropintosilva** [comment]
I think it would be good to have this merged for the quick fix release

**Comment by Darshan-upadhyay1110** [comment]
Thanks @pedropintosilva & @timar

**Pull request merged**
