### PR TITLE
Private/caolan/rejig slurp delay

### PR DESCRIPTION
**Pull request by caolanm**
* Resolves: # 
* Target version: master 

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by caolanm** [comment]
Can try scaling delay based on num of expected tiles to a max of 50ms.

wrt. better,  not overwhelmed, maybe slightly better on first start. Otherwise I don't know if it makes a discernible difference.

original, [Screencast from 2024-05-28 20-39-02.webm](https://github.com/CollaboraOnline/online/assets/833656/907a7cb3-e715-4df7-b0ec-e24852806af9)

after, [Screencast from 2024-05-28 20-39-02.webm](https://github.com/CollaboraOnline/online/assets/833656/eaa63836-573b-4cb1-9f4c-d992be64455e)

**Review by mmeeks — APPROVED** [review]
All looks very plausible; I assume when we have slurped all the predicted tiles - that we get back to a 1ms delay - and/or cancel the timer and get on with it - which is what we should do =)
Thanks!

**Comment by mmeeks** [comment]
Wrt. the videos - do we manage to predict any tiles incoming as we press page-down; IIRC we somehow managed not to predict anything there (I think) - perhaps we are not counting missing tiles or something in the calculation or ... (?) could that be related; at least I didn't see much difference in the videos ;-) but conceptually it seems a sensible approach.

**Comment by caolanm** [comment]
yeah, if the prediction is 0 then if there is an earlier longer-scheduled timer existent, it's rescheduled to as soon as possible.

wrt videos, I don't see much of a difference either. On adding some bespoke logging, then in a local server case I can see some initial long delay timer launches at first start, but otherwise they seem to get rescheduled to short generally, so I feel the actual change is modest.

**Pull request merged**
