### PR TITLE
Menubar update sync with LibO

### PR DESCRIPTION
**Pull request by Andreas-Kainz**
Change-Id: If6631438057c8f955617924315196fa749102328

### CODE REVIEW

**Comment by DarkknightAK** [comment]
writer menubar update arrangement sync with LibO writer and add some commands which are available in LibO writer but for now not at COOL.

All added commands are tested and work.

**Comment by DarkknightAK** [comment]
if wanted I can go through calc, impress and draw menubar next

**Comment by mrkara** [comment]
@DarkknightAK Thank you for the PR! :)

Not particularly sure about the ones added here, but some of the commands might have been left out on purpose for various reasons. (Not fitting in the online workflow/design, not being fully-functional on Online etc.)

I hope @pedropintosilva or @thebearon can tell more about it, and also check the PR. -Thanks! :)-

**Comment by pedropintosilva** [comment]
So i have tested this without and with storage file service and:

- File: pretty cool thanks!
- View: definitely it makes much more sense to sync this as well, so we can have everything that hides together etc
- Insert: here I'm not so sure if this wouldn't work against the user base that already uses CO for sometime now. Specially because the order is very different but also the grouping. For example in the suggested change `Header and Footer >` would get orphaned ; Things that are quite used such as TOC or would get reshuffled etc 
- Format: this change is very welcomed and I think the current user-base will not suffer that much with the changes or at least will re-adapt quite easily  
- Table: `Split cells..` was added but it's always active (and clickable) even without any table present. Also I wonder if wouldn't be better to also have there the simple `Split cell`. `HeadingRowsRepeat` and `RowSplit` are always active even without any table
- Tools: great additions, thanks!

I would also love to hear what @kendy and @thebearon think about the `Insert` and `Table` menu entries

sync-menu-tools
sync-menu-table
sync-menu-format
sync-menu-insert

**Comment by pedropintosilva** [comment]
> true I also saw it, but it's not an issue of COOL it's already in LibO wrong.

so maybe for now, and so we can merge all the goodies,  it would be wise if you could
* fix the conflicts
* remove the `Split cells...` from this pull request and then add new pull request just with that so anyone else can also tackle that issue (and so if needed we can revert just that change without affecting the other stuff)
* remove the `HeadingRowsRepeat` and `RowSplit`
* and also revert the changes on `Insert` menu entry

**Comment by Andreas-Kainz** [comment]
> 
> 
> > true I also saw it, but it's not an issue of COOL it's already in LibO wrong.
> 
> so maybe for now, and so we can merge all the goodies, it would be wise if you could
> 
>     * fix the conflicts
> 
>     * remove the `Split cells...` from this pull request and then add new pull request just with that so anyone else can also tackle that issue (and so if needed we can revert just that change without affecting the other stuff)
> 
>     * remove the `HeadingRowsRepeat` and `RowSplit`
> 
>     * and also revert the changes on `Insert` menu entry

As I already have an merge conflict, I will wait for feedback about the changes. In general it's a cosmetic issue with `Split cells...`, `HeadingRowsRepeat` and `RowSplit` so I would add them to the menubar cause the commands work. They are not grayed out when the user isn't in a table (which is ok, cause all commans are in the menu table).

About the `Insert` menu entry rearrangement. I can reverte the arrangement, but the arrangement is the same than in LibO so in a long run, I would rearrange them.

**Comment by Andreas-Kainz** [comment]
All comments from @pedropintosilva are now in the request.

**Comment by mrkara** [comment]
Rebased & conflict-resolved PR is #366

**Pull request closed without merging**
