### PR TITLE
Resize cursor width according to browser zoom.

### PR DESCRIPTION
**Pull request by GulsahKose**
Signed-off-by: Gülşah Köse <gulsah.kose@collabora.com>
Change-Id: I15418181394d27cb379d99e7f4c688153ac7a443

* Target version: master 

### TODO

- [ ] ...

### Checklist

- [x] Code is properly formatted
- [x] All commits have Change-Id
- [x] I have run tests with `make check`
- [x] I have issued `make run` and manually verified that everything looks okay
- [x] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by pedropintosilva** [comment]
Retriggered tests as it failed with timeout

**Comment by pedropintosilva** [comment]
I have tested and it works :) probably good to test this in a HiDPI device just to make sure it also works there

**Comment by pedropintosilva** [comment]
tested in HiDPI ipad (chrome) using zoom browser it works

**Review by merttumer — APPROVED** [review]
LGTM

**Pull request merged**
