### PR TITLE
Disable overwrite mode in experimantal mode automatically.

### PR DESCRIPTION
**Pull request by GulsahKose**
Disable overwrite mode by default

### CODE REVIEW

**Comment by GulsahKose** [comment]
That PR is first followup improvement that Pedro mentioned here: https://github.com/CollaboraOnline/online/pull/7415#discussion_r1360737613

**Comment by pedropintosilva** [comment]
Assigning reviewer. But:
this a low priority PR but if it works it should be merged so it can be tested in the next CODE. But would be good to check why CI didn't pass and re-triggered. But just to reiterate this other work/PR should take priority here.

**Review by eszkadev — APPROVED** [review]
looks ok

**Comment by eszkadev** [comment]
I think we can now merge this one, right? Please rebase :)

**Comment by eszkadev** [comment]
@GulsahKose tests have to be adjusted probably, it fails on statusbar

**Pull request merged**
