### PR TITLE
Fix : Menubutton should have disabled state styling different

### PR DESCRIPTION
**Pull request by codewithvk**
Change-Id: I1cd97503e0d3ca4333b11552ca3571093cf10bfe

* Resolves: #6877 
* Target version: master 

image

### CODE REVIEW

**Comment by eszkadev** [comment]
Nice! it fixed enabled/disabled state and also text alignment inside.
One probably unwanted thing is that now menubutton become higher when compared to other listboxes / edit fields:
alignment

@pedropintosilva what do you think?

**Review by pedropintosilva — CHANGES_REQUESTED** [review]
Thanks @codewithvk !

I think with this change we still get the misalignment , now a bit more visible. And it seems we are not really targeting the disabled menubutton and addressing the lack of styling for those.

Here is what I would prefer:
- Avoid adding more exceptions to btns.csss
- Properly set all the missing styles:
```css
.jsdialog.menubutton[disabled] span {
	color: var(--color-text-lighter);
}

.jsdialog.menubutton[disabled] .arrow {
	border-top-color: var(--color-text-lighter);
}
```
to https://github.com/CollaboraOnline/online/blob/master/browser/css/jsdialogs.css#L1032

And maybe in additional commit make sure that regular menubutton has the same size as the other elements

**Comment by codewithvk** [comment]
Hi @pedropintosilva,

Thank you for your valuable suggestions and feedback on my pull request. I have incorporated several changes based on your suggestions, and I appreciate your help in improving the code.

I wanted to share a small suggestion for future interactions. While I value the code you provided, I believe it would be more beneficial to my learning process if you could offer hints or suggestions rather than providing the code directly. This way, I can have the opportunity to explore and implement the solutions on my own, which will greatly contribute to my growth as a developer.

Regarding your additional comment on making sure that the regular menubutton has the same size as the other elements, I agree that it's a good idea. However, to keep the changes focused and organized, I will address this separately in a new commit and create a separate pull request once the current one is merged.

Once again Thanks :)

**Comment by pedropintosilva** [comment]
Cool, I'll check it. 

Yup I agree and I appreciate the feedback :) 

Granted the ins and outs of what should be where can be a bit all over the place and so I wanted to offer some initial aid (I just shouldn't over do it :)

**Comment by pedropintosilva** [comment]
@codewithvk thanks. Can you also make sure it doesn't reach to hover state when it's disabled?

**Comment by codewithvk** [comment]
> @codewithvk thanks. Can you also make sure it doesn't reach to hover state when it's disabled?

Do i have to tack care of all the inputs or just for the date picker? I can see all inputs are hover even they are disabled.
image

**Comment by pedropintosilva** [comment]
Let me merge this and please create a follow up pr that fixes all the hover states on disabled items :)

**Comment by codewithvk** [comment]
> Let me merge this and please create a follow up pr that fixes all the hover states on disabled items :)

Sure, Thanks!

**Pull request merged**
