### PR TITLE
Private/gokay/autofillmarker co 6 4

### PR DESCRIPTION
**Pull request by gokaysatir**
* Resolves: # 
* Target version: master 

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by mmeeks** [comment]
Would be great - currently as you move the cursor you can see it sort of 'jump' on top / is not in the same frame: more noticeable now cursor moving is faster too =)

**Comment by dennisfrancis** [comment]
@gokaysatir Are there more patches to port regarding auto-fill marker or this the final set ?

**Comment by gokaysatir** [comment]
@dennisfrancis  This is final set.

**Review by dennisfrancis — COMMENTED** [review]
This patch is empty : "LOUtil: Add rectangle class". The patch "LOUtil: Rectangle class follow-up." is also empty Can you fix ?

**Comment by dennisfrancis** [comment]
I see the same marker behaviour on moving the cursor in the svg version too. I'll fix it in a follow-up.

**Pull request merged**
