### PR TITLE
Close autofilter popovers when click or change the sheet tab

### PR DESCRIPTION
**Pull request by Darshan-upadhyay1110**
- jsdialog not getting close when we change tab
- this will close all dialogs when we click on tab or change the tab

To test this patch
    - add 2 or 3 tab sheet in calc
    - add `autofilter` in any calc sheet tab
    - open autofilter popup
    - change sheet tab

Before this patch:
    - popup not getting close when focus goes away.

After: - all dialogs should be closed now when change the sheet tab.

Change-Id: I4eb308e499853a6e1d86b8dc7f60aa938e9c03b9

### CODE REVIEW

**Comment by eszkadev** [comment]
We can't do it this way:

[formula-2024-01-19_10.13.05.webm](https://github.com/CollaboraOnline/online/assets/5307369/88415b65-ad20-45e5-833f-c6e55dbbceb3)

**Review by eszkadev — APPROVED** [review]
code looks good

**Review by eszkadev — CHANGES_REQUESTED** [review]
I found one other case:
- when you see autofilter popup, click insert sheet
- you will be switched and popup is still there

**Comment by Darshan-upadhyay1110** [comment]
I guess i have fire the event at wrong place. now it works. Close dialogs when we add class tab selected so it will be more generic than call inside `setPart`

CC: @eszkadev

**Review by eszkadev — APPROVED** [review]

**Pull request merged**
