### PR TITLE
docstate: Modified colorPalettes in docstate to include new color values

### PR DESCRIPTION
**Pull request by rparth07**
- Modified colorPalettes in docstate to include new color values 
- Added margin-top to .ui-color-picker-palette

Change-Id: I5a8520ec0b1798977ec69da74b8488021b30123a

* Resolves: #6947
* Target version: master 

### Checklist

- [X] I have run `make prettier-write` and formatted the code.
- [X] All commits have Change-Id
- [ ] I have run tests with `make check`
- [X] I have issued `make run` and manually verified that everything looks okay
- [X] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by gokaysatir** [comment]
Not only new colors are added but also some old ones are removed it seems. Code looks ok but we need @pedropintosilva 's comment on the colors i think.

**Comment by gokaysatir** [comment]
No objections for more colors, they look better.

Not sure if it's the best way to add colors to make the window size bigger.

Also, "document colors" option is still small and i guess we can't add new colors there.

I am not sure if different sizes is an issue for the popup but i guess we could solve it via CSS rules?

**Review by pedropintosilva — APPROVED** [review]

**Review by pedropintosilva — CHANGES_REQUESTED** [review]
Thanks ! @rparth07 and sorry for the delay. Everything seems much much better <3 

we just need to double check why these tests `Apply font color` and `Apply highlight color` are failing and possibly update them

```javascript
fail:	
                    Test failed: integration_tests/desktop/writer/top_toolbar_spec.js / Top toolbar tests. / Apply highlight color.
                    
                    Timed out retrying after 10000ms: Expected to find element: `.ui-color-picker-entry[name="FFF2CC"]`, but never found it. Queried from:
                    
                                  > cy.get(#coolframe, [object Object]).its(0.contentDocument, [object Object])
                    
                    /home/collabora/jenkins/workspace/github_online_master_debug_vs_co-24.04_cypress_desktop/cypress_test/support/index.js:177:1
                      175 | 		return cy.get(cy.cActiveFrame, {log: false})
                      176 | 			.its('0.contentDocument', {log: false})
                    > 177 | 			.find(selector, optionsWithLogFalse);
                          | ^
                      178 | 	} else {
                      179 | 		return cy.get(cy.cActiveFrame, optionsWithLogFalse)
                      180 | 			.its('0.contentDocument', {log: false});
          cy:log ✱  Finishing test: integration_tests/desktop/writer/top_toolbar_spec.js / Top toolbar tests. / Apply highlight color.
```

```javascript
 cy:command ✔  fail:	
                    Test failed: integration_tests/desktop/writer/top_toolbar_spec.js / Top toolbar tests. / Apply font color.
                    
                    Timed out retrying after 10000ms: Expected to find element: `.ui-color-picker-entry[name="8E7CC3"]`, but never found it. Queried from:
                    
                                  > cy.get(#coolframe, [object Object]).its(0.contentDocument, [object Object])
                    
                    /home/collabora/jenkins/workspace/github_online_master_debug_vs_co-24.04_cypress_desktop/cypress_test/support/index.js:177:1
                      175 | 		return cy.get(cy.cActiveFrame, {log: false})
                      176 | 			.its('0.contentDocument', {log: false})
                    > 177 | 			.find(selector, optionsWithLogFalse);
                          | ^
                      178 | 	} else {
                      179 | 		return cy.get(cy.cActiveFrame, optionsWithLogFalse)
                      180 | 			.its('0.contentDocument', {log: false});
          cy:log ✱  Finishing test: integration_tests/desktop/writer/top_toolbar_spec.js / Top toolbar tests. / Apply font color.
```

**Comment by pedropintosilva** [comment]
To check those locally and see what it happens and where it fails you ca run the following in the save Collabora Online directory that you normally do `make run`:

```bash
make -C cypress_test run-desktop spec=writer/top_toolbar_spec.js
```

**Comment by rparth07** [comment]
> To check those locally and see what it happens and where it fails you ca run the following in the save Collabora Online directory that you normally do `make run`:
> 
> ```shell
> make -C cypress_test run-desktop spec=writer/top_toolbar_spec.js
> ```
> 
> Code pointers:
> 
> * It we a helper in cypress_test/integration_tests/common/desktop_helper.js
> * And then in multiple *_spec.js we call that with specific colour values `desktopHelper.selectColorFromPalette('FFF2CC');` to test if the colour value

Thanks for the code pointers! While analyzing the test cases, I noticed that some were using colors from the standard palette. Since the standard color palette has been updated, some of the previously used values are no longer available, causing the tests to fail. I fixed this by updating the tests to use values from the new palette. All relevant test cases should now pass.

**Comment by rparth07** [comment]
Additionally, although it's a minor change, I noticed that in the previous version, all color values were in uppercase. To maintain consistency, I updated them accordingly in the current version.

**Comment by eszkadev** [comment]
DCO check failed. Please sign-off your commits.
When doing commit you can use `-s` argument, like `git commit -m "this is commit title" -s`

**Comment by Darshan-upadhyay1110** [comment]
CC: @gokaysatir @pedropintosilva needs +1 review ☝🏼

**Review by pedropintosilva — APPROVED** [review]

**Comment by Darshan-upadhyay1110** [comment]
@rparth07 it's quite some time since last rebase can you please rebase it and test this patch ? then we are good to merge it...

**Review by gokaysatir — APPROVED** [review]
Thanks for the improvements :)

**Pull request merged**
