### PR TITLE
UI: Prefill rename dialog with the current document name

### PR DESCRIPTION
**Pull request by lpranam**
resolves: #7468

Change-Id: Icb6563f76cc0f9c7d81eac96fedc6e476dfdad46

* Target version: master 

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by lpranam** [comment]
@pedropintosilva I wish we could keep the name(just name without extension) selected in some way. I might do that as follow-up

**Comment by pedropintosilva** [comment]
> @pedropintosilva I wish we could keep the name(just name without extension) selected in some way. I might do that as follow-up

Yes that would be good, Or at least for now please make a PR that the whole thing is selected. Currently nothing is selected

**Review by pedropintosilva — APPROVED** [review]
Thanks

**Comment by lpranam** [comment]
> > @pedropintosilva I wish we could keep the name(just name without extension) selected in some way. I might do that as follow-up
> 
> Yes that would be good, Or at least for now please make a PR that the whole thing is selected. Currently nothing is selected

that's complicated, that's why its gonna be a follow up 😂

**Comment by pedropintosilva** [comment]
Yes that is what I meant make a PR, meaning the follow up xD

**Pull request merged**
