### PR TITLE
Leaflet use var colors

### PR DESCRIPTION
**Pull request by Andreas-Kainz**
leaflet-popup dialog use var colors

Signed-off-by: andreas kainz <kainz.a@gmail.com>
Change-Id: Ibc8a0a2ca2ff63dc0bc66613a202959288a331d1

image

### CODE REVIEW

**Comment by Andreas-Kainz** [comment]
image

**Comment by Andreas-Kainz** [comment]
@Rash419 come this failure from my PR or from something else?

**Comment by Rash419** [comment]
@Andreas-Kainz In last three runs there is one unit test failure and 2 cypress failures. I will have a look in cypress failures later today and if any test needs to be updated I will update this PR with it : ) and I think unit test failure is not related to your PR

**Comment by Andreas-Kainz** [comment]
Thanks for the feedback. I will submit the PR.

**Pull request merged**
