### PR TITLE
“Copy_loleaflet-api.html_into_code:autoFitWidth”

### PR DESCRIPTION
**Pull request by greenthings**
Signed-off-by: Jun Shin <mnhfn8hj@gmail.com>
Change-Id: Ib1defbedf71b37cee0e44e30a3375056bb61e5a1

* Resolves: # 
* Target version: master 

### Summary
I wrote a comment about autoFitWidth.

### TODO

- [x] ...

### Checklist

- [x] Code is properly formatted
- [x] All commits have Change-Id
- [x] I have run tests with `make check`
- [x] I have issued `make run` and manually verified that everything looks okay
- [x] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by greenthings** [comment]
Thank you for advice, I am really pleased to contribute to your business 
and I will file a bug report.

And Can I ask something about commit message??

git commit -a -m “Copy loleaflet-api.html into code :autoFitWidth”

This is what I wrote command line for commit comment in Gitpod.

I expected this sentence that is 

Copy loleaflet-api.html into code :autoFitWidth

But, There was 

“Copy loleaflet-api.html into code :autoFitWidth” 

I am trying to figure out this problem, but still I can not find this.

**Comment by greenthings** [comment]
I want to attend, but I'm a graduate student, so the class is on Tuesday and Thursday at that time. I'm sorry I couldn't attend. Is there any other way?

**Comment by pedropintosilva** [comment]
> Thank you for advice, I am really pleased to contribute to your business and I will file a bug report.
> 
> And Can I ask something about commit message??
> 
> git commit -a -m “Copy loleaflet-api.html into code :autoFitWidth”
> 
> This is what I wrote command line for commit comment in Gitpod.
> 
> I expected this sentence that is
> 
> Copy loleaflet-api.html into code :autoFitWidth
> 
> But, There was
> 
> “Copy loleaflet-api.html into code :autoFitWidth”
> 
> I am trying to figure out this problem, but still I can not find this.

well that's very interesting, indeed I see that both in the title of this PR and in the commit message itself. Maybe you copied and paste the command for a different text editor you were using and it ended up pasting  typopgraphic quotes:
“” vs ""

**Comment by pedropintosilva** [comment]
@greenthings : I think you have an issue with the indentation could you please fix that?

You can see what and where to fix by clicking in the `CodeQL` failed test:
https://github.com/CollaboraOnline/online/pull/3396/checks?check_run_id=3949395396

```
  5119:1  error  Expected indentation of 3 tabs but found 12 spaces  indent
  5120:1  error  Expected indentation of 3 tabs but found 12 spaces  indent
```

**Pull request closed without merging**
