### PR TITLE
 Presentations: Ruler

### PR DESCRIPTION
**Pull request by Darshan-upadhyay1110**
-  Initialized ruler UI for DOCTYPE Presentation
 - Now functionality is available independent of the selected view.
 - Ruler is present in both Compact/Tabbed view
 
Signed-off-by: Darshan-upadhyay1110 <darshan.upadhyay@collabora.com>
Change-Id: Ie443a69d0afead8fde2ac08b63442b491710fcb8

* Resolves: # 
* Target version: master 

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by hfiguiere** [comment]
Is this #7405

**Comment by Darshan-upadhyay1110** [comment]
Final CORE changes: https://gerrit.libreoffice.org/c/core/+/168276/1

To test this online patch, please build CORE with above PR

**Comment by eszkadev** [comment]
it doesn't work for me, tested with core patch [https://gerrit.libreoffice.org/c/core/+/168276](https://gerrit.libreoffice.org/c/core/+/168276)

ruler

**Comment by Darshan-upadhyay1110** [comment]
@eszkadev I have also checked it’s working can you please share about anything different you are doing here ?

[Screencast from 2024-06-11 00-32-51.webm](https://github.com/CollaboraOnline/online/assets/61383886/a70c81cc-d73f-4ccb-8b6f-cd6c79e3b3d1)

**Comment by Darshan-upadhyay1110** [comment]
> @eszkadev I have also checked it’s working can you please share about anything different you are doing here ?
> 
>  Screencast.from.2024-06-11.00-32-51.webm

Sorry @eszkadev there is one more change that we need for ruler to work

https://gerrit.libreoffice.org/c/core/+/167060 => i restored it now all will work

**Comment by eszkadev** [comment]
please rebase, we had issues with cpp tests recently

**Comment by eszkadev** [comment]
thanks, works now with core patch. Please rebase as we fixed ci. Also do not merge now, let's wait a bit.

**Review by eszkadev — APPROVED** [review]

**Comment by Minion3665** [comment]
(CI had a full disk, I fixed it so close/open to restart the jobs)

**Pull request merged**
