### PR TITLE
Add multi-language support for Notebookbar accelerators.

### PR DESCRIPTION
**Pull request by gokaysatir**
Change-Id: I185f60960cb819814dfdc72900bafaef023cafd6

* Resolves: # 
* Target version: master 

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by pedropintosilva** [comment]
@gokaysatir does https://github.com/CollaboraOnline/online/pull/6783 help?

**Review by pedropintosilva — COMMENTED** [review]
Thanks Gokay!

I have tested and Firefox is still very flimsy 

https://github.com/CollaboraOnline/online/assets/65948705/4f116f84-5086-4093-b5e1-c36ac76b03cb


https://github.com/CollaboraOnline/online/assets/65948705/624af0d1-90c3-4fed-ad72-d4031e4a415b

and Chromium with window menu on is also a bit I think:


https://github.com/CollaboraOnline/online/assets/65948705/79b6bce9-7165-4907-a7d6-5d1d8400f73b


 Plus I'm not able to insert an image

Also in PT-BR I'm not getting different hints than in EN

**Comment by gokaysatir** [comment]
@pedropintosilva thanks for checking this :)

You need to hold your finger up after you see the accelerator keys, so they don't mess with browser shortcuts.

I improved it for Firefox.

Usage is:

* Press "Shift + Alt" (Firefox) or "Alt" (Chrome).
* Menu appears.
* Release the keys.
* Pick the action you want.

Can you have another look when you have time?

**Comment by gokaysatir** [comment]
"Also in PT-BR I'm not getting different hints than in EN"

@pedropintosilva you mean accelerator keys? If so, we need to define them, there are only German and English definitions. English are default.

If you mean the button hints when you hover the mouse over them, that's a different issue.

**Comment by pedropintosilva** [comment]
> If you mean the button hints when you hover the mouse over them, that's a different issue.
@gokaysatir  meant this ^

**Comment by pedropintosilva** [comment]
expected to be able to trigger a command (that has focus) by:
~~Pressing that accesskey again~~ (not expected)
:ballot_box_with_check:  Pressing Enter key
:x:  Pressing Space key
https://github.com/CollaboraOnline/online/assets/65948705/ae6f4332-bec7-466e-b4df-c9f53042606c

references: https://webaim.org/techniques/keyboard/#testing

**Pull request merged**
