### PR TITLE
Handle JSON exception when parsing commands

### PR DESCRIPTION
**Pull request by eszkadev**

### CODE REVIEW

**Comment by eszkadev** [comment]
just wrapping JSON parsing with try {} catch {} so we don't stop the app

**Comment by eszkadev** [comment]
should fix https://github.com/CollaboraOnline/online/issues/3916

**Comment by eszkadev** [comment]
@Ashod could you look if we need to return something in case of an exception in that method?
(It was hard to me to understand what means false or true when following the calls, no comment above declaration either)

btw real fix for incorrect JSON is also made, but in core ;)

**Review by Ashod — APPROVED** [review]
I checked why leaking the exception didn't get gracefully handled. Basically, this exception is happening while we inspect the data in DocBroker, before forwarding to clients. So this scenario doesn't benefit from the default exception belts we have around external data.

Let's get it in, this is good. Thanks @eszkadev!

**Pull request merged**
