### PR TITLE
Improve group_download_as: replace icon

### PR DESCRIPTION
**Pull request by pedropintosilva**
As discussed in https://github.com/CollaboraOnline/online/issues/4564
the current download as 2 is quite different form the surrounding icons
- Remove and use colibre's icon

Signed-off-by: Pedro Pinto Silva <pedro.silva@collabora.com>
Change-Id: I5808af8a50c1f8025b38502ba5fcd2db3f98c9d5

### CODE REVIEW

**Comment by pedropintosilva** [comment]
@gmasei11 I agree this icon comes from Colibre theme (which is used in the core as export) and here we are using it as download. I will adjust the icon : )

**Comment by pedropintosilva** [comment]
I also start a draft PR to improve the implementation of this and to make more small and consistent with the other menus we already use : https://github.com/CollaboraOnline/online/pull/4576

**Comment by gmasei11** [comment]
> @gmasei11 Also I think we should remove the `as` from `Download as` contrary to the "Save as" which has point (to convey to the user that the action will open a dialog/more options) in here we have a dropdown, it is already clear that the component is not an action in itself but a dropdown to more actions

It's up to you :)

**Comment by pedropintosilva** [comment]
only iOS fails and it is unrelated

**Pull request merged**
