### PR TITLE
color-palette use var --color-border-*

### PR DESCRIPTION
**Pull request by Andreas-Kainz**
add a description to color-palette to define
which --color-border-* color should be used.

replace hardcoded colors with the equivalent
--color-border-* variable

Signed-off-by: andreas kainz <kainz.a@gmail.com>
Change-Id: I7be11904eee2fe7f9330a87915cdb71e6a9af3ba

### CODE REVIEW

**Comment by Andreas-Kainz** [comment]
sure there are a few hardcoded border colors, but I change the color ONLY when I know where the color was used. So each changed value was checked in the UI.

**Comment by pedropintosilva** [comment]
Hover status somehow got affected notebookbar > buttons

https://user-images.githubusercontent.com/65948705/152501311-8037803a-97ff-4a85-86a6-c6c926bbe514.mp4

**Comment by Andreas-Kainz** [comment]
Thanks for thre Review Pedro, sorry you are right, will check what's going wrong.

**Comment by Andreas-Kainz** [comment]
I think it's not reviewable so I make a #4119 and hope that it's easier to review.

**Pull request closed without merging**
