### PR TITLE
[co-23.05] cool#8292 browser, clipboard: fix navigator.clipboard error handling

### PR DESCRIPTION
**Pull request by vmiklos**
- **cool#8023 browser**
- **cool#8292 browser**

### CODE REVIEW

**Comment by vmiklos** [comment]
@caolanm could you please review this? Thanks.

This is just a backport from master: a dependency + making sure that the Chrome error codepath matches Firefox (and is not worse).

**Review by caolanm — APPROVED** [review]
I wish we had ci operating on this branch

**Comment by vmiklos** [comment]
> https://cpci.cbg.collabora.co.uk:8080/job/github_online_co-23.05_debug_vs_co-23.05/4/console

unit-quarantine failed, let's see if that's a one-off, retry.

**Comment by vmiklos** [comment]
@eszkadev could you please review this as a 2nd reviewer for this branch? Thanks.

This is meant to be reasonably straightforward, the first is just to avoid conflicts the second improves error handling because I initially thought it's just a theoretical problem, so I went with log the error + move on. Now that we have a use-case where this can indeed fail, I tested & fixed the error handling.

**Review by eszkadev — APPROVED** [review]

**Pull request merged**
