### PR TITLE
fix: unusual spacing between the icons in the mobile view 

### PR DESCRIPTION
**Pull request by aarsh21**
Change-Id: Ic3d751e2f781441f0b860183773fac752147972e

* Fixes : https://github.com/CollaboraOnline/online/issues/9320
* Target version: master 

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by aarsh21** [comment]
@Darshan-upadhyay1110

**Review by Darshan-upadhyay1110 — APPROVED** [review]
LGTM :)

**Comment by Darshan-upadhyay1110** [comment]
@aarsh21 please rebase.

**Review by pedropintosilva — CHANGES_REQUESTED** [review]
Thank you @aarsh21 but by removing this it affects the statusbar on desktop:

image

**Comment by aarsh21** [comment]
hey @pedropintosilva i am sorry perhaps i didn't count it status bar to have change init.i will look into it and patch it =)

**Comment by Darshan-upadhyay1110** [comment]
@aarsh21 any joy here ? let me know if you need any help ?

**Comment by aarsh21** [comment]
@Darshan-upadhyay1110 still working on it

**Comment by aarsh21** [comment]
I tested it, and I don't think the problem is with the width. It seems to be related to the initial rendering of the bottom bar after adding an image to the canvas. When I click or focus back on the canvas, the bottom bar rebuilds and the issue is fixed. I'm considering whether queuing a bottom bar build after inserting the image could cause performance issues. Alternatively, I could use a media query or check if it's a mobile device (isMobile). If true, then remove the width; if not, then improve the width.
.
.
.
it might be a dumb idea still . perhaps i could be overthinking here =0

**Comment by Darshan-upadhyay1110** [comment]
@aarsh21 i did a quick debug and found you can play around `width` of `.jsdialog.ui-separator.horizontal` css rule in `/online/browser/css/jsdialogs.css`.

This is just a hint, and it might not be a solution you need to check it with other cases as well. All the best and keep hacking 😉

**Comment by aarsh21** [comment]
@Darshan-upadhyay1110 I think the one you suggested is the potential fix i checked briefly , well its dumb of me that i didn't find it first :sweat: . thank you for the help tho !!. have a great day.

**Comment by Darshan-upadhyay1110** [comment]
> @Darshan-upadhyay1110 I think the one you suggested is the potential fix i checked briefly , well its dumb of me that i didn't find it first 😓 . thank you for the help tho !!. have a great day.

@aarsh21 no problem happens to me all the time. Glad that you have a working solution now. 

Keep contributing, there are lots of bug report that are easy to fix. And let us know for any help :)

**Review by pedropintosilva — APPROVED** [review]
Thank you!

**Pull request merged**
