### PR TITLE
browser: improve logging by using custom logging methods instead of c…

### PR DESCRIPTION
**Pull request by alessioalex-1and1**
…onsole ones directly

Signed-off-by: Alexandru Vlăduţu <alexandru.vladutu@1and1.ro>
Change-Id: Id4ad5711c85998ce71ba0849fca5fe6dc580f395

* Resolves: #3878
* Target version: master 

### Summary

Instead of using `console` methods everywhere now we will be using `window.app.console` while having the same methods as before. It is the easiest transition to a better logging solution as we will keep using the same methods as we used before with a prefix basically (like for example `window.app.console.log(<string>)`) and it allows us to set those functions to do nothing when needed.

### TODO

- [ ] Make sure I haven't omitted any `console` function somewhere, I have used the following command to track them down:

```bash
grep -r "console\." . --exclude-dir="node_modules" --exclude-dir=".git" --exclude-dir="archived-packages" --exclude-dir="dist" --exclude-dir="jails" --exclude-dir="po" --exclude-dir="test" --exclude-dir="admin" -l --include \*.js
```
### Checklist

- [ ] Code is properly formatted
- [x] All commits have Change-Id
- [x] I have run tests with `make check`
- [x] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Review by mmeeks — APPROVED** [review]
Thanks Alexandru - looks good; I expect it helps the casual developer too.
I wonder if we should allow this stuff to be turned on & off in our tripple-click help->about dialog popup: where we mis-use these 'layer check-boxes' to select that sort of stuff.
I wonder what our stack of libraries we use underneath does too - perhaps they use console.log left and right.
Can you re-base this and lets get it in ASAP.
Thanks!

**Comment by mmeeks** [comment]
We should also make CodeQL - happy:

/home/runner/work/online/online/browser/js/global.js
  78:24  error  Do not access Object.prototype method 'hasOwnProperty' from target object  no-prototype-builtins
  89:1   error  Expected indentation of 2 tabs but found 1

**Comment by alessioalex-1and1** [comment]
> Thanks Alexandru - looks good; I expect it helps the casual developer too. I wonder if we should allow this stuff to be turned on & off in our tripple-click help->about dialog popup: where we mis-use these 'layer check-boxes' to select that sort of stuff. I wonder what our stack of libraries we use underneath does too - perhaps they use console.log left and right. Can you re-base this and lets get it in ASAP. Thanks!

Since it's a custom function and not involving the native `console.log` directly this should be easily doable. I will resolve the CodeQL thing and the conflicts and push again.

**Comment by mmeeks** [comment]
Thanks Alexandru =)

**Comment by mmeeks** [comment]
I was about to merge this - which looks fine; and then considered the scope for conflicts as we back-port to the 21.11 branch for the next week (or worse silent exceptions causing very odd behavior).

It sucks to do it, but can we delay another week ?

**Comment by alessioalex-1and1** [comment]
@mmeeks sure, comment here before you want to make the merge, there might be a few conflicts to solve by then.

**Comment by mmeeks** [comment]
Urgh; github makes a separate merge commit - can you re-base properly and just push this ? =)

Thanks !

**Comment by mmeeks** [comment]
Lovely - thanks ! =)

**Pull request merged**
