### PR TITLE
Copy loleaflet-api.html into code: cursorURL

### PR DESCRIPTION
**Pull request by siddharth25pandey**
* Resolves: # [loleaflet-api.html: Copy documentation into source code as comments #2160](https://github.com/CollaboraOnline/online/issues/2160)
* Target version: master

### CODE REVIEW

**Comment by siddharth25pandey** [comment]
@pedropintosilva please review this

**Comment by siddharth25pandey** [comment]
@pedropintosilva Lemme know if it's correct. So, that I can create a single PR for entire Options and General Methods

**Review by pedropintosilva — APPROVED** [review]
Yup thanks! I will merge it after it passes the tests :)

**Comment by pedropintosilva** [comment]
Merging this as the only falling test is unrelated (FreeBSD)

**Pull request merged**
