### PR TITLE
Impress: Notebookbar: Insert: Author Name

### PR DESCRIPTION
**Pull request by pedropintosilva**
- .uno:InsertAuthorField

Signed-off-by: Pedro Pinto Silva <pedro.silva@collabora.com>
Change-Id: Ic71e33d9ce1a4f1d209fce876da02a8c57a6d76f

### CODE REVIEW

**Comment by pedropintosilva** [comment]
Before:
image

after:
image

**Comment by pedropintosilva** [comment]
https://user-images.githubusercontent.com/65948705/112015877-802a2680-8b2c-11eb-97ea-8b48c0eff93d.mp4

**Comment by pedropintosilva** [comment]
cannot be merge until #1812 is clarified

**Comment by timar** [comment]
This PR did not work as expected, and there is no update. Let's close it for now. Please re-open, if you disagree.

**Pull request closed without merging**
