### PR TITLE
wsd: add 'wopi_host_id' to about dialog

### PR DESCRIPTION
**Pull request by hcvcastro**
Change-Id: I04004f416e7bc6cb2c265fe3ebc08f2c250e8009
Signed-off-by: Henry Castro <hcastro@collabora.com>

### CODE REVIEW

**Review by mmeeks — APPROVED** [review]
Thanks Henry - great work.
I think some of our partners are not hyper-eager for us to expose this in the UI by default; can you show it only in our tripple click / debugging mode ? =)
But of course for feedback reporting it is invaluable =)
Fine to do the version hide/show in a follow-on =) Thanks!

**Comment by hcvcastro** [comment]
Thanks, I will do next commit

**Comment by hcvcastro** [comment]
oh, it is not rebased, I will modify now =)

**Review by mmeeks — APPROVED** [review]
Looks sensible; thanks =)

**Pull request merged**
