### PR TITLE
toolbar: make fold btn visible in compact mode

### PR DESCRIPTION
**Pull request by aarsh21**
Change-Id: I703acfb96491e264f498cc0945ef5d052d4f46ae

* Resolves: #9749 
* Target version: master 

### TODO

- [ ] ...

### Checklist

- [x] I have run `make prettier-write` and formatted the code.
- [x] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [x] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Review by Darshan-upadhyay1110 — COMMENTED** [review]
Hii @aarsh21 thanks for the fix. I have tested your patch it seems good.

But I saw a strange behavior there in icon. At the very first time when fold icon loads is looking different compare to what we have using CSS property.

is there any way you can direct change the url path of fold and not add or remove class?  is it possible ?

Let me know your findings here, other than that it's a good fix for now :)

CC: @eszkadev

**Comment by aarsh21** [comment]
@Darshan-upadhyay1110 I can do that. but i thought it'd be still better to use unfold and fold classes.And path to fold icon were given wrong path but still it was displaying icon. That's still confusing.
- I will change the path directly in the image tag as you said. I will make them consistent.
- What if we just rotate the icon 180 degrees :D.  ( might be a dumbway ).

**Comment by Darshan-upadhyay1110** [comment]
> @Darshan-upadhyay1110 I can do that. but i thought it'd be still better to use unfold and fold classes.And path to fold icon were given wrong path but still it was displaying icon. That's still confusing.
> 
> * I will change the path directly in the image tag as you said. I will make them consistent.
> * What if we just rotate the icon 180 degrees :D.  ( might be a dumbway ).

@pedropintosilva any thoughts on the last suggestion here ? Looks okay to me

**Review by Darshan-upadhyay1110 — APPROVED** [review]

**Review by pedropintosilva — APPROVED** [review]
Thank you!

**Comment by pedropintosilva** [comment]
This seem quite safe to me merged

**Pull request merged**
