### PR TITLE
Handle poll results in SocketPoll in a round-robin order

### PR DESCRIPTION
**Pull request by tml1024**
We don't want to always start with the most recently added socket.

Signed-off-by: Tor Lillqvist <tml@collabora.com>
Change-Id: Ic4b4bf6c19c5d119e6e6f9b398789a4c77b47a10

* Resolves: # 
* Target version: master 

### TODO

- [ ] ...

### Checklist

- [x] Code is properly formatted
- [x] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [x] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by tml1024** [comment]
(Tentative patch, do not merge just to be "helpful". But I do want the checks to be run so I can't mark it as "draft".)

**Comment by tml1024** [comment]
Ah, this crashes right away even in "make run"... truly work in progress;)

**Comment by tml1024** [comment]
OK, now it even seems to work as intended.

**Comment by tml1024** [comment]
Changed commit message and comments to match reality better. It is of course not the "poll order" that this change modifies, but the order in which we handle the sockets that the poll result indicated.

**Comment by mmeeks** [comment]
Lets get this into master but not co-6-4 =) Thanks.

**Pull request merged**
