### PR TITLE
transitions

### PR DESCRIPTION
**Pull request by quikee**
* Resolves: # 
* Target version: master 

### TODO

- [ ] ...

### Checklist

- [ ] I have run `make prettier-write` and formatted the code.
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Review by codewithvk — CHANGES_REQUESTED** [review]
We need to add `/* -*- js-indent-level: 8 -*- */`  Inorder to prevent build Error.

**Comment by codewithvk** [comment]
We need to rebase for CI pass.

**Comment by pedropintosilva** [comment]
Pressed retry on `COOL release (from tarball) co-24.04 `

**Comment by pedropintosilva** [comment]
Pressed retry on `COOL 24.04 Cypress (desktop)` since the error is on `writer/invalidations_spec.js ` see details bellow

<details>
cy:command ✔  cGet	.empty-deltas
      cy:command ✘  assert	expected **'2'** to equal **'0'**
                    Actual: 	"2"
                    Expected: 	"0"
      cy:command ✔  fail:	
                    Test failed: integration_tests/desktop/writer/invalidations_spec.js / Invalidation tests. / Click Existing Header.
                    
                    Timed out retrying after 10000ms: expected '2' to equal '0'
                    
                    /home/collabora/jenkins/workspace/github_online_master_debug_vs_co-24.04_cypress_desktop/cypress_test/integration_tests/desktop/writer/invalidations_spec.js:62:42
                      60 |             // verify empty deltas is unchanged
                      61 |             cy.cGet('.empty-deltas').should(($after) => {
                    > 62 |                 expect($after.text()).to.eq(beforeCount);
                         |                                          ^
                      63 |             });
                      64 |         });
                      65 |     });
          cy:log ✱  Finishing test: integration_tests/desktop/writer/invalidations_spec.js / Invalidation tests. / Click Existing Header.
</details>

**Comment by pedropintosilva** [comment]
> Pressed retry on `COOL 24.04 Cypress (desktop)` since the error is on `writer/invalidations_spec.js ` see details bellow
> 
> <details>
> cy:command ✔  cGet	.empty-deltas
>       cy:command ✘  assert	expected **'2'** to equal **'0'**
>                     Actual: 	"2"
>                     Expected: 	"0"
>       cy:command ✔  fail:	
>                     Test failed: integration_tests/desktop/writer/invalidations_spec.js / Invalidation tests. / Click Existing Header.
>                     
>                     Timed out retrying after 10000ms: expected '2' to equal '0'
>                     
>                     /home/collabora/jenkins/workspace/github_online_master_debug_vs_co-24.04_cypress_desktop/cypress_test/integration_tests/desktop/writer/invalidations_spec.js:62:42
>                       60 |             // verify empty deltas is unchanged
>                       61 |             cy.cGet('.empty-deltas').should(($after) => {
>                     > 62 |                 expect($after.text()).to.eq(beforeCount);
>                          |                                          ^
>                       63 |             });
>                       64 |         });
>                       65 |     });
>           cy:log ✱  Finishing test: integration_tests/desktop/writer/invalidations_spec.js / Invalidation tests. / Click Existing Header.
> </details>

Retry again

**Comment by vmiklos** [comment]
https://cpci.cbg.collabora.co.uk:8080/job/github_linux_release_co-24.04/3205/console fails with:

> make[2]: /bin/sh: Argument list too long

I see no reason why the browser/l10n/ files have to be processed from the browser/; doing it separately avoids the error for me locally on 'make clean && make dist', I've pushed a commit to the branch to see if it helps on CI as well.

**Comment by quikee** [comment]
Vivek force pushed by mistake - the new PR is now https://github.com/CollaboraOnline/online/pull/9918

**Pull request closed without merging**
