### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by YadlaMani**
* Target version: master 

### Summary
Fixed Typos

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [X] Documentation (manuals or wiki) has been updated or is not required

Name : Mani Yadla
E-mail: blank22062005@gmail.com

### CODE REVIEW

**Review by pedropintosilva — APPROVED** [review]
Welcome and thanks for the fix!

**Comment by YadlaMani** [comment]
@pedropintosilva  Done

**Comment by pedropintosilva** [comment]
> @pedropintosilva Done

hm I think there is something missing the DCO test is still failing . Did you follow the instructions and then pushed? I do not see any change in the commit message. If you prefer you can paste here in the comments your name and email address and I can add that to the commit message so it passes the DCO verification.

**Comment by YadlaMani** [comment]
@pedropintosilva 
Name :YadlaMani
email:yadlamaniymn2005@gmail.com

**Comment by pedropintosilva** [comment]
Thank you!

**Pull request merged**
