### PR TITLE
co-6-4: loleaflet: avoid reload page if it is integrated with WOPI

### PR DESCRIPTION
**Pull request by hcvcastro**
Change-Id: I3c6ba97c04c001affbc62b039290d2a7a8c8f91a
Signed-off-by: Henry Castro <hcastro@collabora.com>

### CODE REVIEW

**Comment by mmeeks** [comment]
Hmm - interesting; are you sure this is the right fix? what is it about WOPI that helps here?
I would assume that we want to do the reload command but without the dialog showing up - if we are doing that already - to refresh just that iframe (?) or ... ?

**Comment by hcvcastro** [comment]
No explicit dialog to reload when WOPI is used, the auto-reconnecting will refresh the document.

**Comment by mmeeks** [comment]
Surely the purpose of the reload is to refresh the javascript though - since when the server version changes the JS can too and we badly don't want to leave old JS running against a new loolwsd - hence the reload.

So - we should do an automatic reload in this case, as/when we detect a different serverid I think.

**Comment by hcvcastro** [comment]
I see, working on it ...

**Pull request closed without merging**
