### PR TITLE
fix(helm): improve ingress-haproxy annotations

### PR DESCRIPTION
**Pull request by genofire**
* Resolves: # 
* Target version: master 

### TODO

- [x] bump chart version

### Checklist

- [ ] Code is properly formatted
- [x] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by genofire** [comment]
@Rash419 i believe we would the problem with the haproxy-ingress controller on loadbalancing

**Comment by Rash419** [comment]
@genofire Looks good to me. can you rebase please ? There are merge conflicts =)

**Comment by genofire** [comment]
we found the option to disable loadbalance:
https://haproxy-ingress.github.io/docs/configuration/keys/#dynamic-scaling

we have not yet evaluate that option ...

**Comment by eszkadev** [comment]
@Rash419 what should we do with this PR?

**Comment by Rash419** [comment]
@genofire I am closing this PR. If you find something please create the new one, thanks : )

**Pull request closed without merging**
