### PR TITLE
Draw dark mode fixes

### PR DESCRIPTION
**Pull request by OFFTKP**
Resolves issue where presentations would not load all at once. Along with https://gerrit.libreoffice.org/c/core/+/154940, the dark mode related Draw bugs should be fixed.

### CODE REVIEW

**Comment by gokaysatir** [comment]
Previews are not loaded on opening. They are loaded on master branch.

**Review by gokaysatir — CHANGES_REQUESTED** [review]
Can you check the previews issue?

**Comment by OFFTKP** [comment]
@gokaysatir I made some changes and the preview issue is fixed for me, can you re-test?

**Review by gokaysatir — APPROVED** [review]
Thanks @OFFTKP :)

**Comment by OFFTKP** [comment]
This fixes the issue but some unit tests fail - It shouldn't be hard to fix though

**Comment by OFFTKP** [comment]
Fail seems unrelated, merging

**Pull request merged**
