### PR TITLE
loleaflet: add menubar shortcuts where applicable

### PR DESCRIPTION
**Pull request by alessioalex-1and1**
closes 3177

Signed-off-by: Alexandru Vlăduţu <alexandru.vladutu@1and1.ro>
Change-Id: Ib6959852263afba0b268d73f2879ec22357716c3

* Resolves: # 
* Target version: master 

### TODO

- [ ] ...

### Checklist

- [x] Code is properly formatted
- [x] All commits have Change-Id
- [ ] I have run tests with `make check`
- [x] I have issued `make run` and manually verified that everything looks okay
- [x] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Review by eszkadev — APPROVED** [review]
Looks great, let's wait for CI to pass

**Comment by alessioalex-1and1** [comment]
@eszkadev is this again a CI general issue?

**Comment by eszkadev** [comment]
> @eszkadev is this again a CI general issue?

we can ignore FreeBSD 13 failure, but Unit & Cypress should pass. Please rebase the patch with current master.

**Comment by eszkadev** [comment]
hi, we don't use git's 'merge' strategy, we do 'rebase' instead. Could you remove merge commits from this PR?  it should contain only one commit with changes.

**Comment by alessioalex-1and1** [comment]
hi @eszkadev can you take a look again over this PR? thanks!

**Comment by pedropintosilva** [comment]
it looks good, thanks! @alessioalex-1and1 could you make sure `(Short + Cut)` is inside of key html elements so we can target them and style them? Maybe something like:
```
<div class="shortcut"><kbd>Ctrl</kbd><span class="kbd--plus">+</span><kbd>B</kbd></div>
```

image

**Comment by pedropintosilva** [comment]
> it looks good, thanks! @alessioalex-1and1 could you make sure `(Short + Cut)` is inside of key html elements so we can target them and style them? Maybe something like:
> 
> ```
> <div class="shortcut"><kbd>Ctrl</kbd><span class="kbd--plus">+</span><kbd>B</kbd></div>
> ```
> 
> image

you know what I will just merge this, and if you could then create another PR addressing this would be great : )!

**Comment by alessioalex-1and1** [comment]
Ah I understand. That would be a good addition. It would probably require a bit of a different approach than the current one, but it should be possible. Will add that to the list.

**Pull request merged**
