### PR TITLE
RTL UI

### PR DESCRIPTION
**Pull request by eszkadev**

### CODE REVIEW

**Comment by eszkadev** [comment]
can be tested with `&lang=ar` parameter in the URL

**Review by gokaysatir — APPROVED** [review]
Thanks for the improvements :)

**Comment by eszkadev** [comment]
in case this will fail or we will have time to wait a bit longer there is better PR with comments in writer fixed:
https://github.com/CollaboraOnline/online/pull/3968

**Comment by eszkadev** [comment]
Merged another PR with the same patches

**Pull request closed without merging**
