### PR TITLE
Add a ProfileZone implementation here, too

### PR DESCRIPTION
**Pull request by tml1024**
Compiled but not yet used.

Signed-off-by: Tor Lillqvist <tml@collabora.com>
Change-Id: I3b85696ca6076e42d16e710b49bfd37bac342ec8
Signed-off-by: Tor Lillqvist <tml@collabora.com>

* Resolves: # 
* Target version: master 

### TODO

- [ ] ...

### Checklist

- [x] Code is properly formatted
- [x] All commits have Change-Id
- [ ] I have run tests with `make check`
- [x] I have issued `make run` and manually verified that everything looks okay
- [x] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by tml1024** [comment]
This is not even compiled yet so no point in waiting for build;)

**Comment by tml1024** [comment]
Maybe I should add a commit that at least compiles it.

**Review by mmeeks — COMMENTED** [review]
Looks great to me - thanks Tor =)
We should prolly use this around bits in the DocumentBroker.
I suspect we will need some async-capable thing here too - to be able to emit individual events - lots of our work is a bit hard to turn into start/end stuff I think =)

**Comment by tml1024** [comment]
Argh. What I needed to make gettid() visible in that one Jenkins build?

**Comment by tml1024** [comment]
@mmeeks Can you reproduce the compilation failure?

**Comment by mmeeks** [comment]
We have a gettid wrapper internally in online already: Util::getThreadId() (?)

**Comment by tml1024** [comment]
Heh, we resort to syscall(SYS_gettid)... Lovely consistency among Linuxes;)

**Pull request merged**
