### PR TITLE
added vex-overlay in admin console when Wsd shutdown

### PR DESCRIPTION
**Pull request by Rash419**
Signed-off-by: Rash419 <rasheshpadia419@gmail.com>
Change-Id: Ifcf259aee446196cc6e8269a540a6514e628e4a8

* Resolves: #71
* Target version: master 

Screenshot from 2020-11-11 20-18-16

edit - Message has been updated to "Server has been shutdown please reload the page"

### CODE REVIEW

**Review by lpranam — CHANGES_REQUESTED** [review]
the message is miss leading. WSD cannot be reloaded on click, it requires WSD to restart

**Comment by lpranam** [comment]
Also, commit message is not descriptive!

**Review by lpranam — CHANGES_REQUESTED** [review]
Any many files in many lines you have added trailing white spaces. Please remove that. You can use IDE settings to remove that easily and those settings will save you in future from such unnecessary changes too. :)

**Comment by Rash419** [comment]
ok

**Review by lpranam — APPROVED** [review]
Looks good to me

**Comment by mrkara** [comment]
@Rash419 Thank you! Keep up the good work! 👍 :)

**Pull request merged**
