### PR TITLE
Update and rename README to README.md

### PR DESCRIPTION
**Pull request by ptylczynski**
Remake readme so it is in Markdown now. For ease of access and readability

* Resolves: Non of know bugs, QoL change
* Target version: master 

### Summary
Changed docker readme from normal txt to markdown

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by kendy** [comment]
@ptylczynski: Thank you for this!  Looks great to me in general - can you please make sure to fix the DCO and Change-Id checks?

When you click on the "Details", they should tell you what to do. If it is still unclear, please let us know, happy to help!

**Comment by mrkara** [comment]
@ptylczynski Hey! :) We still need your commit signature to be able to merge your nice contribution. Please feel free to ping me if you need help to do that.

Looking forward to get this patch merged. Thanks!

**Comment by mrkara** [comment]
@ptylczynski Hey! Still stuck on this? We can help! Just ping me and tell in which step you are stuck. :)

**Comment by pedropintosilva** [comment]
Hi @ptylczynski here is what you need to do step by step (so the DCO test passes):

1. `git commit --amend --no-edit --signoff`

Now your commits will have your sign off. Next run

2. `git push --force-with-lease origin patch-1`

Or, and in the case I can use the email address that is visible on your profile, I can do the sign off for you

**Comment by kendy** [comment]
I am very sorry, we cannot integrate this without the proper sign-off :-(  Please do feel encouraged to re-open this PR & to push a patch that has the correct Signed-off-by: line in the commit message.

Either way, thanks a lot for the patch!

**Pull request closed without merging**
