### PR TITLE
Formatted and add missing .md

### PR DESCRIPTION
**Pull request by ArshErgon**
* Resolves: # 
* Target version: master 

### Summary
Formatted the readme.md for better understanding

### TODO

- [ ] ...

### Checklist

- [x] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Review by pedropintosilva — CHANGES_REQUESTED** [review]
see my comments above

**Comment by vmiklos** [comment]
Rebase, interestingly I got no conflicts, so perhaps easy to get this in.

**Comment by vmiklos** [comment]
https://cpci.cbg.collabora.co.uk:8080/job/github_online_master_debug_vs_co-24.04_cypress_multi_user/1118/console fails in invalidations_spec.js, retry.

**Review by vmiklos — APPROVED** [review]
Looks good to me now, thanks.

**Review by pedropintosilva — APPROVED** [review]
Thanks @ArshErgon and sorry for the delay. Thanks @vmiklos for rebasing this.

**Pull request merged**
