### PR TITLE
add minus,plus and search icon for bottom toolbar

### PR DESCRIPTION
**Pull request by Darshan-upadhyay1110**
Change-Id: Ia675cf4c1607d4ef5f19268647a40ea701109d76

* Resolves: #6505
* Target version: master 

### Summary

fixed part 1 mentioned in this issue : https://github.com/CollaboraOnline/online/issues/6505

### CODE REVIEW

**Comment by eszkadev** [comment]
it doesn't work, because regular rule for zoomin, zoomout, zoomreset contains !important, so dark variant is ignored

**Comment by Darshan-upadhyay1110** [comment]
@eszkadev can you please check this again i am seeing the changes working .


Before Dark mode:
image

After:
image

**Comment by eszkadev** [comment]
you are showing "prev" icon, I was talking about   zoomin (plus), zoomout (minus), zoomreset

**Comment by Darshan-upadhyay1110** [comment]
I think here is confusion. we removed !important from that css for dark mode theme to work 
https://github.com/CollaboraOnline/online/pull/6437 ( here you can get refrence ).

**Comment by eszkadev** [comment]
now I understand, this is not rebased

**Review by eszkadev — APPROVED** [review]

**Pull request merged**
