### PR TITLE
Mobile Sidebar Character remove Grow and Shrink

### PR DESCRIPTION
**Pull request by Andreas-Kainz**
- Mobile Menubar update
- Mobile Sidebar Remove Grow Shrink commands

### CODE REVIEW

**Comment by Andreas-Kainz** [comment]
### Before
Screenshot_20210527_125028


### After
Screenshot_20210527_125426

**Comment by Rash419** [comment]
There are test for grow and shrink ,as you have removed the option , CI will always fail

**Comment by Andreas-Kainz** [comment]
as I don't know anything about CI tests, can you help with this PR?

**Comment by Rash419** [comment]
May I ask why are we removing these options?

**Comment by Andreas-Kainz** [comment]
There is already an Font Size DropDown menu, have grow/shrink will make the UI only more complex cause the two commands were shown at one line together with Character direct formating stuff.

Mobile UI should be simple and easy to understood with grow/shrink you duplicate the function (cause there is already Font Size)

But let's ask @pedropintosilva if we can remove grow/shrink from the mobile sidebar implementation.

**Comment by Andreas-Kainz** [comment]
I checked gdocs and MS Office mobile and both didn't have an additional Grow/Shrink button, so from my point of view, this can be hidden.

**Comment by Rash419** [comment]
I can help you with this PR :D

**Comment by Andreas-Kainz** [comment]
maybe I can than at a future PR fix the test stuff myself.

**Comment by Rash419** [comment]
> maybe I can than at a future PR fix the test stuff myself.

ok :+1:

**Comment by Andreas-Kainz** [comment]
@Rash419 can you help me remove grow/shrink commands from the mobile bottom sidebar?

**Comment by Rash419** [comment]
Sure

**Comment by Rash419** [comment]
> @Rash419 can you help me remove grow/shrink commands from the mobile bottom sidebar?

Sure

**Comment by Rash419** [comment]
Hello @Andreas-Kainz  you have to remove the grow and shrink test otherwise CI will fail because you have removed the grow and shrink option.CI will try to test that functionality. In calc , impress and writer you need to remove the test.
In Calc:
Grow test : https://github.com/CollaboraOnline/online/blob/14ff3a3047aa8db2b2cae9f0fe79f75793772923/cypress_test/integration_tests/mobile/calc/apply_font_spec.js#L88
Shrink test:
https://github.com/CollaboraOnline/online/blob/14ff3a3047aa8db2b2cae9f0fe79f75793772923/cypress_test/integration_tests/mobile/calc/apply_font_spec.js#L97

In Impress:
Grow test:
https://github.com/CollaboraOnline/online/blob/14ff3a3047aa8db2b2cae9f0fe79f75793772923/cypress_test/integration_tests/mobile/impress/apply_font_text_spec.js#L121

Shrink test:
https://github.com/CollaboraOnline/online/blob/14ff3a3047aa8db2b2cae9f0fe79f75793772923/cypress_test/integration_tests/mobile/impress/apply_font_text_spec.js#L137

Writer:
Grow test:
https://github.com/CollaboraOnline/online/blob/14ff3a3047aa8db2b2cae9f0fe79f75793772923/cypress_test/integration_tests/mobile/writer/apply_font_spec.js#L107

Shrink test:
https://github.com/CollaboraOnline/online/blob/14ff3a3047aa8db2b2cae9f0fe79f75793772923/cypress_test/integration_tests/mobile/writer/apply_font_spec.js#L116

**Comment by Andreas-Kainz** [comment]
Follow up PR is #2585

**Pull request closed without merging**
