### PR TITLE
color-palette: use color-palette vars instead of hardcoded colors

### PR DESCRIPTION
**Pull request by Andreas-Kainz**
add a description to color-palette to define

Signed-off-by: andreas kainz <kainz.a@gmail.com>
Change-Id: I23f78c8c6e87417095c2c0bc029fda5f43f5a488

* Resolves: #3772

### CODE REVIEW

**Comment by Andreas-Kainz** [comment]
image

**Comment by Andreas-Kainz** [comment]
image

**Comment by Andreas-Kainz** [comment]
image

**Comment by Andreas-Kainz** [comment]
image

**Comment by Andreas-Kainz** [comment]
image

**Comment by Andreas-Kainz** [comment]
image

**Comment by Andreas-Kainz** [comment]
image

**Comment by Andreas-Kainz** [comment]
image

**Comment by Andreas-Kainz** [comment]
image

**Comment by Andreas-Kainz** [comment]
image

**Comment by Andreas-Kainz** [comment]
image

**Comment by Andreas-Kainz** [comment]
image

**Comment by Andreas-Kainz** [comment]
image

**Comment by Andreas-Kainz** [comment]
image

**Comment by Andreas-Kainz** [comment]
image

**Review by pedropintosilva — COMMENTED** [review]
So I have checked all these commit but a couple of them do not only change values to css var but also change spacing , border and opacity. Some of these changes are impacting cypress tests and also how it looks , (e.g.: how the split button looks which is not a bug, or changes on border width that makes transparent parent thinner and thus less spacing surrounding those) 

I have created a new PR (where cypress test passes) and without those above mentioned ^ but I still kept other changes that even thought are not related to CSS vars do not seemed problematic

**Comment by Andreas-Kainz** [comment]
ok so please when everything that work for you will pass, please submit to master, so I can work on a "fresh" master.

thanks a lot and sorry for all the work you have with the review. In general I think the most visual items are done, so everything else can be done with smaler patches for specific topics.

**Comment by Andreas-Kainz** [comment]
thanks to pedro the stuff was merged with #4164

**Pull request closed without merging**
