### PR TITLE
browser: do not hide the document title when resize

### PR DESCRIPTION
**Pull request by hcvcastro**
Change-Id: I55f5aa0ccd8938feea3b64c5d1422bb8502adb2b
Signed-off-by: Henry Castro <hcastro@collabora.com>

### CODE REVIEW

**Comment by eszkadev** [comment]
@hcvcastro I think it was intentional, by @pedropintosilva

**Comment by hcvcastro** [comment]
I asked to review it. it has side effects that it is marked as a bug.

**Comment by pedropintosilva** [comment]
thanks but I really think that it's better to hide elements when there is no space so we can have room to interact with other buttons. With this PR we enhance the situation for one user (now user can see the title in narrow window ) while making it unusable for other users, screenshot with this patch:

image

**Comment by hcvcastro** [comment]
Ok, I think you can continue to follow-up patch to fix the remaining issues =)

**Comment by pedropintosilva** [comment]
fixed with https://github.com/CollaboraOnline/online/pull/9119

**Pull request closed without merging**
