### PR TITLE
Sidebar Layout Harmonization #4305

### PR DESCRIPTION
**Pull request by Andreas-Kainz**
The goal is to harmonize the sidebar layout

#### Global Sidebar Layout:

- Sections Headers use --font-size-header
- Separation between Sections have padding and a separator line

#### Section Layout:

- align-left are the Labels
- align-right are the widgets (commands)
- Labels use -default-font-size

Signed-off-by: andreas kainz <kainz.a@gmail.com>
Change-Id: Ib08ca0340d99dac7e7479bc43a04d069d550d85c

* Resolves: #4305 
* Target version: master 

#### Writer Default + Table
Table

#### Shape
shape

### CODE REVIEW

**Comment by Andreas-Kainz** [comment]
@pedropintosilva @juliushaertl this patch isn't finished. I only checked for now writer and I know that there has to be some fixes in the default view of calc, I will do the fixes. What I need is feedback about the direction of this patch from you, cause it change the design of the sidebar. 

- the labels are the same than any other string. 
- the Section Headers use default font and height, ...
- the labels are vertical align with the header label
- ...

The goal is to have an clean sidebar. I also think to drop the horizontal line at each section.

**Review by pedropintosilva — CHANGES_REQUESTED** [review]
understood, regarding the icon, it would be better to refrain from using hamburger menu icon because:
- it does not really trigger menus, it opens dialogs with more options
- on top of that in some cases we might already have hamburger menus in the screen (ipad) and it will look strange to have the same type of icon for very different things

**Comment by juliushaertl** [comment]
Looks nice I think. Regarding to the icon I agree with @pedropintosilva but also find the different icons currently un use not that ideal in terms of giving the user a quick idea on what a click would trigger. Maybe something like a preferences icon could be more suitable there as the type of preferences is already indicated by the heading text? Something like https://thenounproject.com/search/icons/?iconspage=1&q=preferences

**Comment by Andreas-Kainz** [comment]
About the icon. I prefer the different icons like it was done by nextcloud office. It's great and the hamburger menu was only an backup when there is no specific icon.

**Comment by Andreas-Kainz** [comment]
if you are ok with this PR I have to fix the conflict.

**Pull request closed without merging**
