### PR TITLE
Widget: enable iconview with text

### PR DESCRIPTION
**Pull request by codewithvk**
Change-Id: I44e3e40b3be1dcfd0d099939e6f6a9a4e574fdbd

* Resolves: # 
* Target version: master 

### Summary
- Previously, we only showed icons in cases where we wanted to display the IconView from the core. Now, if the IconView contains text, the text will be displayed below the icon from the IconView.

Screenshot from 2024-08-01 18-22-46

### CODE REVIEW

**Comment by codewithvk** [comment]
This PR is failing. We are using style preview with a text field from the core side, which causes the Iconview to be displayed with text here.    

Screenshot from 2024-08-03 23-17-02

Code pointer: stylespreview.ui

I think we are using IconView with text in sidebargallery.ui, Not sure where we have this in UI. We have to fix it as well.

**Comment by codewithvk** [comment]
> stylespreview.ui

Fix from core side : https://gerrit.libreoffice.org/c/core/+/171491

**Comment by codewithvk** [comment]
Fix for Failing CI: https://gerrit.libreoffice.org/c/core/+/171491. @quikee We need to merge so that the CI green here. :)

**Review by eszkadev — APPROVED** [review]

**Comment by eszkadev** [comment]
Added some cleanup and fix for a bug we detected recently

**Pull request merged**
