### PR TITLE
Remove w2ui #5: Formulabar

### PR DESCRIPTION
**Pull request by eszkadev**
Removes w2toolbar from formulabar and uses JSDialog instead.
HTML structure is simplified. But still there is a room to improve.

### CODE REVIEW

**Review by gokaysatir — COMMENTED** [review]
I can't open mobile view. There are JS errors.

**Comment by eszkadev** [comment]
Sorry it was leftover after last rebase. Updated now.

**Comment by pedropintosilva** [comment]
I get this on the terminal:

warn:pyuno.runtime:21552:21505:pyuno/source/module/pyuno_runtime.cxx:951: Python exception: <class 'FileNotFoundError'>: [Errno 2] No such file or directory: '/lo/share/extensions/numbertext/reg.uno.py', traceback follows
  File "/home/pedro/LibreOffice/core-24-x/instdir/program/pythonloader.py", line 134, in activate
    mod = self.getModuleFromUrl( locationUrl )
  File "/home/pedro/LibreOffice/core-24-x/instdir/program/pythonloader.py", line 94, in getModuleFromUrl
    with open( filename, encoding='utf_8' ) as fileHandle:

 at /home/pedro/LibreOffice/core-24-x/pyuno/source/module/pyuno_runtime.cxx:950
warn:sc:21552:21505:sc/source/core/tool/addincol.cxx:303: Failed to initialize create instance of sheet.AddIn


and I get browser console errors so I couldn't test mobile 


16:55:32.374 Uncaught TypeError: target is undefined
    addEventListeners hammer.js:222
    each hammer.js:60
    addEventListeners hammer.js:221
    init hammer.js:449
    Input hammer.js:434
    PointerEventInput hammer.js:868
    createInputInstance hammer.js:485
    Manager hammer.js:2282
    Hammer hammer.js:2142
    enableTooltip Control.UIManager.js:1722
    createFormulabar Control.FormulaBarJSDialog.js:182
    FormulaBar Control.FormulaBarJSDialog.js:39
    FormulaBar Control.FormulaBarJSDialog.js:389
    initializeSpecializedUI Control.UIManager.js:313
    beforeAdd CalcTileLayer.js:78
    addLayer Layer.js:69
    _onStatusMsg Socket.js:1421
    _onStatusMsg Socket.js:1389
    setTimeout handler*_onStatusMsg Socket.js:1388
    _onMessage Socket.js:1200
    _emitSlurpedEvents Socket.js:374
    _slurpTimer Socket.js:325
    setTimeout handler*_queueSlurpEventEmission Socket.js:323
    _slurpMessage Socket.js:422
    _emptyQueue Socket.js:89
    connect Socket.js:83
    loadDocument Map.js:333
    <anonymous> main.js:117
    <anonymous> main.js:137
hammer.js:222:9


16:55:32.376 Uncaught TypeError: this._map is undefined
    _updateCursorAndOverlay CanvasTileLayer.js:3960
    _changeFocusWidget Map.js:1378
    _onEditorGotFocus Map.js:1395
    fire Events.js:146
    _onGotFocus Map.js:1403
    handler DomEvent.js:51
    _on DomEvent.js:86
    on DomEvent.js:21
    _initEvents Map.js:1344
    initialize Map.js:86
    NewClass Class.js:16
    map Map.js:1728
    <anonymous> main.js:54
    <anonymous> main.js:137
CanvasTileLayer.js:3960:6


16:55:32.405 Exception TypeError: app.sectionContainer is undefined emitting event applicationbackgroundcolor: ffffff _onMessage@http://localhost:9980/browser/0bec574ec3/src/layer/tile/CanvasTileLayer.js:1556:13
_onMessage@http://localhost:9980/browser/0bec574ec3/src/layer/tile/CalcTileLayer.js:136:52
_onMessage@http://localhost:9980/browser/0bec574ec3/src/core/Socket.js:1122:33
_emitSlurpedEvents@http://localhost:9980/browser/0bec574ec3/src/core/Socket.js:316:30
_queueSlurpEventEmission/that._slurpTimer<@http://localhost:9980/browser/0bec574ec3/src/core/Socket.js:273:22
setTimeout handler*_queueSlurpEventEmission@http://localhost:9980/browser/0bec574ec3/src/core/Socket.js:271:32
_slurpMessage@http://localhost:9980/browser/0bec574ec3/src/core/Socket.js:360:18
EventHandlerNonNull*connect@http://localhost:9980/browser/0bec574ec3/src/core/Socket.js:67:35
loadDocument@http://localhost:9980/browser/0bec574ec3/src/map/Map.js:284:20
@http://localhost:9980/browser/0bec574ec3/src/main.js:105:13
@http://localhost:9980/browser/0bec574ec3/src/main.js:119:2
cool.html:329:37

**Review by pedropintosilva — APPROVED** [review]
It seems my previous message didn't got pushed. Anyhow I pressed the button to comment now. And I have also pulled again as tested. I didn't see any staggering problem I think this should be merge as soon as possible so we can further test it. 

Specially because there are things they need polishing , example formula bar weird scrollbar even when there is nothing to scroll:

image

**Comment by eszkadev** [comment]
> It seems my previous message didn't got pushed. Anyhow I pressed the button to comment now. And I have also pulled again as tested. I didn't see any staggering problem I think this should be merge as soon as possible so we can further test it.
> 
> Specially because there are things they need polishing , example formula bar weird scrollbar even when there is nothing to scroll:

Thank you for checking. Yes, would be good to do a CSS fix and cleanup in case I didn't remove all leftovers.

**Pull request merged**
