### PR TITLE
Add missing enum `MissingSSLError` and fix typo

### PR DESCRIPTION
**Pull request by Darshan-upadhyay1110**
Change-Id: Ibe3a8417b7ea54cfaa00857a5ed37bbf6f25e1dd

* Resolves: # 
* Target version: master 

### TODO

- [ ] ...

### Checklist

- [ ] I have run `make prettier-write` and formatted the code.
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Review by meven — APPROVED** [review]
I don't understand how this could have passed CI.

**Comment by meven** [comment]
> I don't understand how this could have passed CI.

I see this was in the !SSL ifdef

**Comment by Darshan-upadhyay1110** [comment]
> > I don't understand how this could have passed CI.
> 
> I see this was in the !SSL ifdef

Yes ,  should we add a test case for non-ssl flow ?

**Comment by meven** [comment]
> > > I don't understand how this could have passed CI.
> > 
> > 
> > I see this was in the !SSL ifdef
> 
> Yes , should we add a test case for non-ssl flow ?

That would be valuable to prevent those kinds of issues but that's not simple to put together, would need a separate CI build maybe.

**Review by bayramcicek — COMMENTED** [review]
`make run` works well after this change. 
Thanks.

**Pull request merged**
