### PR TITLE
Mobile BottomBar Align

### PR DESCRIPTION
**Pull request by Andreas-Kainz**
- Mobile Icon closedocument fix
- Mobile BottomBar Align dropdown

### CODE REVIEW

**Comment by Andreas-Kainz** [comment]
@eszkadev this patch didn't work cause the Align dropdown menu wasn't shown. Do you know what I miss to have the Align commands behind a dropdown? I take the code from classic toolbar.

**Comment by eszkadev** [comment]
> @eszkadev this patch didn't work cause the Align dropdown menu wasn't shown. Do you know what I miss to have the Align commands behind a dropdown? I take the code from classic toolbar.

I think there is type: "menu" and you can define list of items in the dropdown.

https://github.com/CollaboraOnline/online/blob/master/loleaflet/src/control/Control.TopToolbar.js#L181

**Comment by Andreas-Kainz** [comment]
At patch set 1 I use menu as type but it didn't work at bottomBar.

**Comment by Andreas-Kainz** [comment]
> I think there is type: "menu" and you can define list of items in the dropdown.
> https://github.com/CollaboraOnline/online/blob/master/loleaflet/src/control/Control.TopToolbar.js#L181

I got it, many thanks

**Pull request closed without merging**
