### PR TITLE
contextmenu: add support to insert and remove data labels on charts

### PR DESCRIPTION
**Pull request by rparth07**
Change-Id: If77d15697eadb56aadb62cf883d2bcf5782f4a54

* Resolves: #9478
* Target version: master 

### Checklist

- [X] I have run `make prettier-write` and formatted the code.
- [X] All commits have Change-Id
- [ ] I have run tests with `make check`
- [X] I have issued `make run` and manually verified that everything looks okay
- [X] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by rparth07** [comment]
I'm not sure, do we need LOKit patch to enable commands status?
cc: @pedropintosilva @Darshan-upadhyay1110

**Comment by Darshan-upadhyay1110** [comment]
> I'm not sure, do we need LOKit patch to enable commands status? cc: @pedropintosilva @Darshan-upadhyay1110

Hii @rparth07  thanks for the PR.

- Have you tried your solution ? is it working ? - Please test it first :)
- Add Core patch if needed, first verify is this patch will solve the linked issue ?

**Comment by rparth07** [comment]
> > I'm not sure, do we need LOKit patch to enable commands status? cc: @pedropintosilva @Darshan-upadhyay1110
> 
> Hii @rparth07  thanks for the PR.
> 
> - Have you tried your solution ? is it working ? - Please test it first :)
> - Add Core patch if needed, first verify is this patch will solve the linked issue ? 

Yes I tried and manually test it and it is working.

**Comment by Darshan-upadhyay1110** [comment]
> > > I'm not sure, do we need LOKit patch to enable commands status? cc: @pedropintosilva @Darshan-upadhyay1110
> > 
> > 
> > Hii @rparth07  thanks for the PR.
> > 
> > * Have you tried your solution ? is it working ? - Please test it first :)
> > * Add Core patch if needed, first verify is this patch will solve the linked issue ?
> 
> Yes I tried and manually test it and it is working.

Okay then what is the thought behind adding LOKit patch here can you explain ?

**Comment by Darshan-upadhyay1110** [comment]
@eszkadev this patch looks good, can you please take a look so we can merge it. Thanks :)

**Review by eszkadev — APPROVED** [review]
looks useful :) thanks!

**Pull request merged**
