### PR TITLE
menubar: disable "serveraudit" option in help menu items in read only mode

### PR DESCRIPTION
**Pull request by rparth07**
Change-Id: Iafeeac96893816b813ff3d6fe0c5a845adcb759d

* Resolves: #9750
* Target version: master 

### Checklist

- [X] I have run `make prettier-write` and formatted the code.
- [X] All commits have Change-Id
- [ ] I have run tests with `make check`
- [X] I have issued `make run` and manually verified that everything looks okay
- [X] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Review by Darshan-upadhyay1110 — COMMENTED** [review]
@rparth07 

However, would it be possible to remove the element from the list in read-only mode instead of just disabling it? My concern is that if we add more options in the future, disabling them could become a never-ending cycle. It would be more effective to hide the element entirely rather than just disabling it.

@eszkadev please correct me if i an wrong here  :)

**Review by Darshan-upadhyay1110 — COMMENTED** [review]
This one similar to https://github.com/CollaboraOnline/online/pull/9775.

**Comment by eszkadev** [comment]
yes, would be good to also remove that item

**Review by Darshan-upadhyay1110 — CHANGES_REQUESTED** [review]
@rparth07 please rebase and if possible try to remove the items which are not needed in RO. 

ATB,
Darshan

**Comment by rparth07** [comment]
On the similar line, Should we also remove all uno command elements instead of disabling them in Read Only mode? 
cc: @eszkadev @Darshan-upadhyay1110

**Comment by eszkadev** [comment]
hiding not disabling patch - is fine
removing serveraudit in readonly - I think it could be useful for admin tom check also RO case

**Comment by Darshan-upadhyay1110** [comment]
Hi @rparth07! Could you please rebase and resolve the conflicts? 

>Also, regarding the patch for hiding (not disabling) – that looks good. As for removing serveraudit in read-only mode, I believe it might still be helpful for admins to check in read-only cases as well. 

Please review this comment and make the necessary changes. Thanks so much! 😊

**Comment by rparth07** [comment]
> hiding not disabling patch - is fine removing serveraudit in readonly - I think it could be useful for admin tom check also RO case

@eszkadev Thank you for reviewing the changes. Could you please confirm if the intended behavior is that, In read-only mode, for admin users, the 'Server Audit' option should be disabled while for other users, it should be hidden?

cc: @Darshan-upadhyay1110

**Comment by eszkadev** [comment]
we need to solve merge conflict, @rparth07 are you still working on it? :)

**Comment by rparth07** [comment]
> we need to solve merge conflict, @rparth07 are you still working on it? :)

Thank you for the update. I’ll take care of resolving the merge conflicts.

**Comment by rparth07** [comment]
I resolved the merge conflicts and enabled serveraudit option for admin. 
Can you please review @eszkadev @Darshan-upadhyay1110 
Thanks :)

**Review by Darshan-upadhyay1110 — APPROVED** [review]
Looks good :)

Admin user read-only mode:
image



Non-admin user read-only mode: `server-audit` option is hidden
image

**Comment by eszkadev** [comment]
Thank you both, for fix and checking :)

**Pull request merged**
