### PR TITLE
Chart line settings

### PR DESCRIPTION
**Pull request by eszkadev**
* Resolves: # 
* Target version: master 

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by tzolnai** [comment]
Hi Szymon,
I checked the cypress test failure this patch has. This kind of error: "This DOM element likely became detached..." Happens for mobile wizard because of flickering (it rendered more times at some point). On maser and co-6-4 online branches we have methods to avoid this issue (clickOnIdle(), inputOnIdle()). On co-4-2, I used to just workaround this with a 'cy.wait(2000)'. You can add it before the failing cy.click() call.

**Comment by tzolnai** [comment]
Well, it passed now incidentally for the third time, but better to fix it up, because it will break the build most of the time.

**Comment by eszkadev** [comment]
@tzolnai hi, I pused update in the cypress test where it waits 500ms, that's why it passed :)

**Comment by eszkadev** [comment]
is it enough? or should I increase to 2000?

**Comment by tzolnai** [comment]
Aha, I did not see that. Great, then my help was not necessary here. Since it passes, 500 ms must be enough.

**Pull request merged**
