### PR TITLE
Update icons in sidebar

### PR DESCRIPTION
**Pull request by rizmut**
Signed-off-by: Rizal Muttaqin <riz_17_oke@yahoo.co.id>
Change-Id: I4d44746709049ced93fba5e163b5446546f56fd2

* Resolves: #4316 
* Target version: master 

### Summary
This PR provides updated icons for sidebar

**Before:**
gambar

**After:**
gambar

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by Andreas-Kainz** [comment]
The icons are all fine and come from core.

However the strikethrough icon I prefer the older one where I think it's better to see the strikethrough. 

About the Shadow icon I also liked the older one better. But you are correct it should have a blue shadow. However do you have an idea of an shadow icon which look more balanced and easier to understood?

**Comment by pedropintosilva** [comment]
I agree with @Andreas-Kainz maybe it would help if in the case strikethrough we  would have white space surrounding the blue line (as it happens in the previous version); and in the shadow case I'm a bit neutral (I see advantages either way).

**Comment by pedropintosilva** [comment]
but I would merge this and then wait for a follow up from @rizmut : )

**Comment by pedropintosilva** [comment]
it seems there was a problem while getting online dependencies within GH actions, re-running them

**Pull request merged**
