### PR TITLE
Mobile color var update

### PR DESCRIPTION
**Pull request by Andreas-Kainz**
primary colors use color from colibre icon theme

Signed-off-by: andreas kainz <kainz.a@gmail.com>
Change-Id: Iaf8eddbe4b66aebd00c7c0d1598bad8cdc4db988

### CODE REVIEW

**Comment by Andreas-Kainz** [comment]
mobile

**Comment by Andreas-Kainz** [comment]
Screenshot_20220306_222429

**Comment by Andreas-Kainz** [comment]
Screenshot_20220306_230904

**Comment by Andreas-Kainz** [comment]
image

**Comment by Andreas-Kainz** [comment]
image

**Comment by Andreas-Kainz** [comment]
image

**Comment by Andreas-Kainz** [comment]
image

**Comment by Andreas-Kainz** [comment]
image

**Comment by Andreas-Kainz** [comment]
image

**Comment by Andreas-Kainz** [comment]
image

**Comment by Andreas-Kainz** [comment]
image

**Comment by Andreas-Kainz** [comment]
image

**Comment by Andreas-Kainz** [comment]
image

**Comment by Andreas-Kainz** [comment]
image

**Comment by Rash419** [comment]
@Andreas-Kainz please don't merge it without passing CI  : ) it broke the test writer/shape_proeperties_spec.js. Tinderbox master failed. If cypress tests doesnot pass for your PR please let me know I will help you out

**Comment by Andreas-Kainz** [comment]
Sorry will check

**Comment by Rash419** [comment]
> Sorry will check

@Andreas-Kainz  no problem I am working on the cypress fix : )

**Pull request merged**
