### PR TITLE
Mobile Context BottomToolbar

### PR DESCRIPTION
**Pull request by Andreas-Kainz**
Signed-off-by: andreas kainz <kainz.a@gmail.com>
Change-Id: I5199d45cce08933229bc68e2048f1285fd6594bf

* Resolves: #2393
* Target version: master 

### Summary
BottomToolbar for mobile (writer) with context related commands.
For now with default, Text, Table. Other context commands will follow. Also other apps (calc, impress, draw). But with a separate patch. I'm not a big fan of large patches.

### CODE REVIEW

**Comment by Andreas-Kainz** [comment]
Ah I see @timar already add @pedropintosilva to review this patch.

There are two options:
1. review this patch
2. wait until contextual bottombar is finished (for mobile)
whatever @pedropintosilva prefer. Plan to be ready until 09.12. to the next cool meeting.

**Comment by Andreas-Kainz** [comment]
@pedropintosilva you can review tha PR and after that we can talk about the description. I would add screenshots.

**Comment by Andreas-Kainz** [comment]
#### Open issues calc mobile
- [ ] calc mobile insert to a cell so you can type a text or function, the context- isn't know. 

vlcsnap-2021-12-09-09h39m22s666

vlcsnap-2021-12-09-09h39m32s604

It's cool that this separate context- toolbar is available. I would add to the menu commands for functions (=, sum, average, ...) but this commands aren't available for now. So what should I add to this context element. 

In addition I have to know how to activate commands for this menu.

Other option would be to hide the toolbar cause the focus is on type something so have there more hight available, would be a benefit.

**Comment by pedropintosilva** [comment]
@Andreas-Kainz I think there too many things in this one commit (that has no description ). Could you please:
1. Maybe separate this commit in 3 commits?
  -  Add Mobile context bottom toolbar
  - Mobile: Fix [x-component] height [and add in the commit's message body why it needed to be change)
  - Mobile: Replace view comments icon [and add  in the commit's message body why it needed to be change)

**Comment by pedropintosilva** [comment]
image
regarding this it seems that we already had an internal discussion. I have created a separated issue https://github.com/CollaboraOnline/online/issues/3826 for that. Thanks for the heads up!

**Comment by Andreas-Kainz** [comment]
this request will be separated to different requests so it's easier to review and also easier to develop.

**Pull request closed without merging**
