### PR TITLE
Fix minor iOS build and runtime problems

### PR DESCRIPTION
**Pull request by plubius**
This patch contains changes to iOS and/or Android code only.

### CODE REVIEW

**Comment by plubius** [comment]
@OFFTKP While testing, I may have found a bug as a side effect of commit https://github.com/CollaboraOnline/online/commit/04ac02b0339008382dcf640899ea18513de5a4a5.

When I open the following PDF document in the iOS app, the thumbnails in the left panel no longer get drawn. For some reason, when opening PDF documents, browser/src/layer/tile/CanvasTileLayer.js:1013 is never called:

https://github.com/CollaboraOnline/online/files/10777062/Cloudervaringsdocument%2BNCSC.pdf

**Comment by plubius** [comment]
> @OFFTKP While testing, I may have found a bug as a side effect of commit [04ac02b](https://github.com/CollaboraOnline/online/commit/04ac02b0339008382dcf640899ea18513de5a4a5).
> 
> When I open the following PDF document in the iOS app, the thumbnails in the left panel no longer get drawn. For some reason, when opening PDF documents, browser/src/layer/tile/CanvasTileLayer.js:1813 is never called but is called for when opening .odp files:
> 
> https://github.com/CollaboraOnline/online/files/10777062/Cloudervaringsdocument%2BNCSC.pdf

Committed the following fix for this and added it to this pull request:

https://github.com/CollaboraOnline/online/pull/7230/commits/89a3df24ee6e8d5725706f6893d183550616548a

**Comment by OFFTKP** [comment]
Please test if you can reproduce after my commit, I don't have an iOS devenv setup to check.

**Comment by plubius** [comment]
> Please test if you can reproduce after my commit, I don't have an iOS devenv setup to check.

I just did a clean build with your commit. I can no longer reproduce the bug so your commit looks good to me.

**Comment by OFFTKP** [comment]
If your PR is otherwise ready it would be great if we could merge this after CI passes because it might fix another blocker, and if not, at the very least a cypress test regression.

**Comment by plubius** [comment]
> If your PR is otherwise ready it would be great if we could merge this after CI passes because it might fix another blocker, and if not, at the very least a cypress test regression.

My PR is ready. The other changes in this pull request only changes code for iOS only. I am not sure what privileges I have in this repo so if you can mark this as reviewed, I will see if I can merge this PR when CI passes.

**Comment by OFFTKP** [comment]
In that case I'll merge. Cypress tests pass now.

**Review by OFFTKP — APPROVED** [review]

**Comment by plubius** [comment]
> In that case I'll merge. Cypress tests pass now.

Thank you for your help.

**Pull request merged**
