### PR TITLE
jssidebar simplify

### PR DESCRIPTION
**Pull request by Andreas-Kainz**
remove as much as possible hardcoded stuff

Signed-off-by: andreas kainz <kainz.a@gmail.com>
Change-Id: I506d73b4243455b60e44fd1bacb7c8ae04723468

### CODE REVIEW

**Comment by eszkadev** [comment]
@Andreas-Kainz nice, we need to clean and reduce css.

Could you provide list of items you touched? which controls/elements we should look at?

Next time it would be good to split that kind of change into few smaller ones (per widget) with short description what widget it changes. Then it is much easier to test and spot regression.

**Comment by Andreas-Kainz** [comment]
The patch isn't 100% done. And for sure, I'm not a fan of a complete NEW css structure (which this is).

When I'm done, I would make screenshots of the sidebar's to show you the results AND to review my work. I hope this is a good way for the review.

In general I delete the jssidebar.css file cause there are so much specific rules and start from scratch. Cause I also want to update the complete structure of the css tree. For example how the sidebar container will be defined. I can also make single patches when I'm done. The goal of this patch wasn't patch a single issue. The goal was fix the sidebar stuff cause it cause troubles since long time so complete new. Sure it requires more testing.

**Comment by Andreas-Kainz** [comment]
@pedropintosilva do you have an idea why I didn't see the `.ui-expander` elements in LTR view?

image

**Comment by Andreas-Kainz** [comment]
the alignment work's quite well. Biggest open issue is LTR has no `.ui-expander` area (I'm not sure if it's really an issue of this PR).

**Comment by Andreas-Kainz** [comment]
## Firefox screenshots LTR
Screenshot_20220521_001606Screenshot_20220521_001634
Screenshot_20220521_001744Screenshot_20220520_231307
Screenshot_20220520_231520Screenshot_20220521_001526
Screenshot_20220520_231336Screenshot_20220520_231119
Screenshot_20220520_231615Screenshot_20220520_231108

**Comment by Andreas-Kainz** [comment]
Firefox work well, Chrome need some love.

**Comment by pedropintosilva** [comment]
I think this PR is outdate another was has been merged meanwhile etc

**Pull request closed without merging**
