### PR TITLE
Add missing Colibre Dark Icons

### PR DESCRIPTION
**Pull request by Andreas-Kainz**
* Resolves: #6447 
* Resolves: #4880
* Target version: master 

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by Andreas-Kainz** [comment]
This PR will only add missing dark icons. 

Future rework will be done by separate PR's. Cause there we have maybe some discussion. Add missing icons, shouldn't be something we have to discuss (a lot).

**Comment by rizmut** [comment]
Just curious, how can lc_chart2restype*.svg files have 16px size dimension?

**Review by rizmut — APPROVED** [review]

**Review by pedropintosilva — APPROVED** [review]
Much appreciated!

**Review by pedropintosilva — CHANGES_REQUESTED** [review]
Much appreciated!

I do not understand why in the add the missing icons for the dark mode we have svg removals there
for example: https://github.com/CollaboraOnline/online/pull/6453/commits/e1586a729b708ab9498d38c788ff228dd600d2f2
was it a mistake/typo?
or am I missing something

Also all those svg removal commits are missing DCO

If it's a typo, just let me know and I can drop those commits

**Comment by pedropintosilva** [comment]
I have merged the other PR (that was pushed by @rizmut ) what should I do with this PR?

**Comment by Andreas-Kainz** [comment]
Hi thanks for submit the PR from @rizmut as I have here DCO and Change-Id check issues (new laptop), it's fine to use rizmut PR. will submit follow up PR's IF NEEDED.

**Pull request closed without merging**
