### PR TITLE
wsd: Cache result of disk space check, too

### PR DESCRIPTION
**Pull request by thebearon**
...when it's requested.

Previously always an empty string was returned on subsequent
calls, and the error message was only shown once.

Signed-off-by: Aron Budea <aron.budea@collabora.com>
Change-Id: I7645c7770e3e1712c8ef1b3ad145daec14530fb0

* Target version: master 

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Review by Ashod — APPROVED** [review]
Looks reasonable. Thanks @thebearon.

**Comment by thebearon** [comment]
The failure in the iOS chain is unrelated.

**Pull request merged**
