### PR TITLE
Added class a private addresses

### PR DESCRIPTION
**Pull request by t0fik**
Added missing class A ip addresses regex to config file.

### Checklist

- [x] Code is properly formatted
- [x] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [x] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by mrkara** [comment]
@t0fik Hi! Thank you for the pull request. :)

We need the commits to be signed with a real name to be able to merge into the repo. And it also needs a ChangeId. Could you please fix those errors? (You can click on the Details link next to each failed check.)

Thanks!

**Review by timar — APPROVED** [review]

**Comment by t0fik** [comment]
@mrkara I've added change-id and signed-off commits.

**Comment by mrkara** [comment]
> @mrkara I've added change-id and signed-off commits.

@t0fik Thanks! Now let's wait for the CI to do its thing. :)

**Comment by mrkara** [comment]
@t0fik Hi! It looks like we have a failing test here, but seems unrelated to your change. Could you please rebase your branch on top of current master?

(I can also do that for you if you make sure "allow changes from maintainers" option is enabled for the pull request.)

**Comment by t0fik** [comment]
I will create new PR with clean history.

**Comment by t0fik** [comment]
Clean PR #2583

**Pull request closed without merging**
