### PR TITLE
cool#9992 doc electronic sign: add a provider selector dialog

### PR DESCRIPTION
**Pull request by vmiklos**
- **jsdialog: avoid 'as any' cast by adding more types**
- **cool#9992 doc electronic sign: add a provider selector dialog**

### CODE REVIEW

**Comment by vmiklos** [comment]
https://cpci.cbg.collabora.co.uk:8080/job/github_online_master_debug_vs_co-24.04_cypress_mobile/2519/console fails in:

> writer/mobile_wizard_state_spec.js

but local

```
make -C cypress_test check-mobile spec=writer/mobile_wizard_state_spec.js
```
passes, retry.

**Comment by vmiklos** [comment]
https://cpci.cbg.collabora.co.uk:8080/job/github_online_master_debug_vs_co-24.04_cypress_desktop/2968/console first failure is in:

> calc/searchbar_spec.js

but a local

```
make -C cypress_test check-desktop spec=calc/searchbar_spec.js
```

passes, retry.

**Comment by vmiklos** [comment]
@caolanm could you please review this? Thanks.

My goal is to have a dialog like this:

image

This adds much of the functionality, but I still need to split handleSendHashJson() to two, so it triggers the dialog and once the dialog is closed, continue with the rest of the steps, that's not done yet.

For the JSON data, that's mostly created by looking at what JSON is generated by the Writer insert break dialog (which also has a dropdown) and then adapt accordingly.

**Review by caolanm — APPROVED** [review]
looks sensible to me at least

**Pull request merged**
