### PR TITLE
cool#9383: build error on FreeBSD

### PR DESCRIPTION
**Pull request by timar**
Change-Id: I287c938bfcdbbdb76dd8f1253e52bb167b440a22

* Resolves: #9383 
* Target version: master

### CODE REVIEW

**Review by vmiklos — APPROVED** [review]
There is a bit of risk that this will lead to processes that linger around because we don't die when our parent dies, but I guess this at least fixes the build. And if that concern turns into a practical problem, we can deal with it in some way.

**Comment by JAicewizard** [comment]
There is an alternative, see https://man.freebsd.org/cgi/man.cgi?procctl(2) `PROC_PDEATHSIG_CTL` released in FreeBSD 11.2 (7 years ago) which has reached EOL already. I think we should be good to start using that? I will open a PR for it.

**Comment by vmiklos** [comment]
Sounds good, in general we don't support COOL on EOL operating systems. Thanks.

**Comment by JAicewizard** [comment]
This was already merged in #12499, didn't reference this PR so thats why it doesn't show up here

**Pull request merged**
