### PR TITLE
Calc: make grouping responsive for each group level

### PR DESCRIPTION
**Pull request by bayramcicek**
Change-Id: I68572eb126acf4a00ed96af870c1f908083aec8b

* Resolves: #7369 
* Target version: master 

### TODO

- [ ] ...

### Checklist

- [x] Code is properly formatted
- [x] All commits have Change-Id
- [ ] I have run tests with `make check`
- [x] I have issued `make run` and manually verified that everything looks okay
- [x] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by bayramcicek** [comment]
I see that group-related codes are added by @gokaysatir here https://github.com/CollaboraOnline/online/pull/1221 . 
Adding @gokaysatir as a reviewer too.

**Review by gokaysatir — APPROVED** [review]
Thanks for the fix @bayramcicek :)

**Comment by pedropintosilva** [comment]
I somehow encounter some weird behaviour: 

https://github.com/CollaboraOnline/online/assets/65948705/48c80089-db86-4985-a8e5-40e7da3f4444

**Review by pedropintosilva — APPROVED** [review]
So WRT the video I posted. I have double checked and that particular bug is already reproducible on master without this commit. Furthermore I have tested this PR and it fixes the problems reported in https://github.com/CollaboraOnline/online/issues/7369 : 
* With this PR: clicking in the control boxes (expander buttons) correctly expands/collapses the respective group instead of activating the Parent
* It also fixes hidden children control boxes (expanders). Before the mouse cursor would switch to the pointer hand when hovering above headers that were hidden (because they were collpased by their parent). Now the cursor doesn't change and there is no click event at all.

**Pull request merged**
