### PR TITLE
Calc: Prevent unnecessary jumping while editing a cell.

### PR DESCRIPTION
**Pull request by gokaysatir**
When autocomplete feature is on, and user starts to edit a cell, view
jumps to the beginning and it quickly jumps again. With the second jump,
edited cell is centered. At the end, view moves. Even though the user
can still see the cell subject to edit, this is uncomfortable.

Sometimes Core side fires events unordered. While this doesn't cause any
problems for it, it may cause some for Online side. Because Online side
processes data immediately. If we can have a stronger state structure on
Online side, we can process this unordered data safely. At least for
some situations like this one.

Signed-off-by: Gökay Şatır <gokay.satir@collabora.com>
Change-Id: I84d129ffa2bd06f4fd55505605f514ac5ca57c51

* Resolves: # 
* Target version: master 

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Review by mmeeks — COMMENTED** [review]
If it works - great; I'd feel much more comfortable with getting the event emissions correct in the core really. I suspect the input-bar and its use of EditEngine of causing many of these problems.

**Comment by kendy** [comment]
@gokaysatir: Thanks for this, but please let's not merge it (at least not yet). Originally the idea was to disable the autocomplete; which seems that the original code was not doing well - the feature that does this is actually "AutoInput" - accessible as Tools -> AutoInput toggle in the desktop version.

I'll attempt to disable it there & see if it fixes the issue.

**Comment by mmeeks** [comment]
Marco re-enabled the autocomplete - and it seemed to mostly work (and is -really- useful ;-) I'd hate to disable it having shipped it. You saw my core patch around this trying to further reduce bogus events from the input area EditEngine ? - doesn't do the trick but ... ;-)

**Comment by kendy** [comment]
@mmeeks: It is problematic in at least 3 ways; let's disable it for now please, see the details here:

https://gerrit.libreoffice.org/c/core/+/113047

**Comment by kendy** [comment]
@gokaysatir: Sorry about this - but let's not use this patch...  Thanks for the work here though! :-)

**Pull request closed without merging**
