### PR TITLE
wsd: allow different UI mode for different views

### PR DESCRIPTION
**Pull request by gmasei11**
Signed-off-by: Gabriel Masei <gabriel.masei@1and1.ro>
Change-Id: I4995d871c309ea3a8c1126388f1ad345886c5c37

* Resolves: # 
* Target version: master 

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by kendy** [comment]
@gmasei11: Thank you for the patch, looks exciting! :-)  The actual piece that decides whether to use the notebookbar or classic looks great to me, let's go that way.

For the change of the return type of uiDefaultsToJSON, let's do it a bit different way. Let's have it as uiDefaultsToMap, and let it return only a map<string, string>, and then have an additional mapToJSON, that will output the string separately. It is a bit confusing to have this complex pair<string, map<string, string>> return type ;-) - better to just have one, the more useful one, and treat the other with an additional conversion function.

Also the returning reference - if we have to go that way, would be good to use const there everywhere; but I'd feel safer returning a copy...

**Comment by gmasei11** [comment]
@kendy: Thanks for your review!

Let me explain my implementation.

I've chose the implementation with std::pair and returning reference because it is better optimized for multiple execution with the same uiDefaults value. I guess that was the reason for storing the result in a static variable and avoid parsing if the uiDefaults is the same as in previous execution.

If we split into two functions as you suggest we must either parse uiDefaults twice (once in every function) or enforce some kind of dependence between them to avoid that (first call uiDefaultsToMap and then pass the result to the uiDefaultsToJSON). Also, the initial scope to not process again for the same value as the previous one is not so straightforward to implement so that we have optimization, encapsulation, simplicity and a nice look. Probably we'll need two variables to check this, one for each function.

As for using reference: I prefer to avoid copying unless it is unavoidable.

If you consider that std::pair with reference type for members looks complex/ugly then we can replace it with a struct with two members (or remove reference from std::pair and rename it into a new type) and return a const reference to it. It will keep the optimization and looks better. What do you think ?

**Comment by kendy** [comment]
> @kendy: Thanks for your review!
> 
> Let me explain my implementation.
> 
> I've chose the implementation with std::pair and returning reference because it is better optimized for multiple execution with the same uiDefaults value. I guess that was the reason for storing the result in a static variable and avoid parsing if the uiDefaults is the same as in previous execution.

Yes, it was so when it was clear that the ui_defaults will be the same in all the calls; the probability that the next call will have the same one is nearly 100%. But when you expect that one user will have classic and other notebookbar, there is a big probability that it all will be always re-parsed anyway, so let's avoid premature optimization, and optimize this only if it appears in a profile (but I'm pretty sure it won't).

> If we split into two functions as you suggest we must either parse uiDefaults twice (once in every function) or enforce some kind of dependence between them to avoid that (first call uiDefaultsToMap and then pass the result to the uiDefaultsToJSON). Also, the initial scope to not process again for the same value as the previous one is not so straightforward to implement so that we have optimization, encapsulation, simplicity and a nice look. Probably we'll need two variables to check this, one for each function.

The idea is that before you first need the data (ie. before the Poco::replaceInPlace() "block") you'd get the map, and then you'd call the uiDefaultsToJSON in the replaceInPlace "block".

> As for using reference: I prefer to avoid copying unless it is unavoidable.

Fair enough; but here it should clearly be const, to avoid potential modification of the underlying static variable.

Having said all this; all we need the map<string, string> for is actually just to find the UIMode, right?

So let's forget all this, instead just add a reference parameter to the uiDefaultsToJSON, and pass only that one, and use it later:

/** \@param uiMode Returns an empty string, "classic" or "notebookbar" depending on what is in the uiDefaults. */
std::string FileServerRequestHandler::uiDefaultsToJSON(const std::string& uiDefaults, std::string & uiMode)

And we'll avoid all the problems with 2 data structures, and additional handling of the map, and reduce the amount of changes in the patch :-)

+    std::string uiMode;
     ...
-     Poco::replaceInPlace(preprocess, std::string("%UI_DEFAULTS%"), uiDefaultsToJSON(uiDefaults));
+    Poco::replaceInPlace(preprocess, std::string("%UI_DEFAULTS%"), uiDefaultsToJSON(uiDefaults, uiMode));
     ...
+    if (uiMode != "")
+        userInterfaceMode = uiMode;
+    else
+        userInterfaceMode = config.getString("user_interface.mode", "classic");

How does that sound?

**Comment by gmasei11** [comment]
> Yes, it was so when it was clear that the ui_defaults will be the same in all the calls; the probability that the next call will have the same one is nearly 100%. But when you expect that one user will have classic and other notebookbar, there is a big probability that it all will be always re-parsed anyway, so let's avoid premature optimization, and optimize this only if it appears in a profile (but I'm pretty sure it won't).

Well, if the user's choice is equal spread between classic and notebookbar then the probability is 50% to be re-parsed and is lower than 50% if the spread is not equal. On the other hand, it seems that sometimes the 'preprocessFile' is called 6 times for the same document but for different files, especially when you refresh in browser the page of the document. I didn't digged into it to see why it is happening but it is happening. So, I think that the optimization is still relevant.

> The idea is that before you first need the data (ie. before the Poco::replaceInPlace() "block") you'd get the map, and then you'd call the uiDefaultsToJSON in the replaceInPlace "block".

True, but splitting is useful when you use the two functions independently or you need some processing between the two which is not the case here. It just adds an overhead. Also, if we stick to the idea that we need the above optimization then this only complicates things.

> Fair enough; but here it should clearly be const, to avoid potential modification of the underlying static variable.

I totally agree.

> Having said all this; all we need the map<string, string> for is actually just to find the UIMode, right?

Yes.

> So let's forget all this, instead just add a reference parameter to the uiDefaultsToJSON, and pass only that one, and use it later:
> 
> /** @param uiMode Returns an empty string, "classic" or "notebookbar" depending on what is in the uiDefaults. */
> std::string FileServerRequestHandler::uiDefaultsToJSON(const std::string& uiDefaults, std::string & uiMode)
> 
> And we'll avoid all the problems with 2 data structures, and additional handling of the map, and reduce the amount of changes in the patch :-)
> 
> ```
> +    std::string uiMode;
>      ...
> -    Poco::replaceInPlace(preprocess, std::string("%UI_DEFAULTS%"), uiDefaultsToJSON(uiDefaults));
> +    Poco::replaceInPlace(preprocess, std::string("%UI_DEFAULTS%"), uiDefaultsToJSON(uiDefaults, uiMode));
>      ...
> +    if (uiMode != "")
> +        userInterfaceMode = uiMode;
> +    else
> +        userInterfaceMode = config.getString("user_interface.mode", "classic");
> ```
> 
> How does that sound?

Sounds a reasonable compromise for me although I like more the map :D. I'll commit a new patch.

Thanks for review !

**Comment by kendy** [comment]
@gmasei11: Thanks so much for the update!  Can you please actually squash these 2 patches into one, so that it is just one change introducing the uiMode?

Regarding the 6x call; I suspect that it is because it is called for various files, not only loleaflet.html - might be worth splitting the huge method into a part that handles the easier cases, and part that handles loleaflet.htmt if that's the case; but separately from this uiMode problem of course, if you are interested :-)

**Comment by gmasei11** [comment]
> @gmasei11: Thanks so much for the update! Can you please actually squash these 2 patches into one, so that it is just one change introducing the uiMode?

Done!

> Regarding the 6x call; I suspect that it is because it is called for various files, not only loleaflet.html - might be worth splitting the huge method into a part that handles the easier cases, and part that handles loleaflet.htmt if that's the case; but separately from this uiMode problem of course, if you are interested :-)

Well, it is a good idea but I don't think that I have time to work on it right now. Anyway, from ui_defaults perspective, it doesn't parse twice for the same input so I think its not urgent.

Thanks again for your review!

**Comment by kendy** [comment]
@gmasei11: Thanks again for your work! :-)

**Pull request merged**
