### PR TITLE
Fix styles dropdown: make all styles searchable, remove one separator

### PR DESCRIPTION
**Pull request by Andreas-Kainz**
Signed-off-by: andreas kainz <kainz.a@gmail.com>
Change-Id: I5f1809858c5aecdef04d9c736711dbb25c80afaa

* Resolves: #3764
* Target version: master 

### Summary
3 sections
1. section predefined styles
2. section favorite styles
3. section ALL available styles

As there is a search (compare to the sidebar) I listed all styles so the search result will find all styles that are available.
separator between predefined styles (default and clear) was removed to have less separations.

Fix is for writer (tested also for the other apps) maybe add favorites to the other apps to.

### CODE REVIEW

**Review by pedropintosilva — CHANGES_REQUESTED** [review]
I think something is not right:
image

**Comment by Andreas-Kainz** [comment]
Is it cool draw isn't it?

**Comment by Andreas-Kainz** [comment]
> I think something is not right: image

The behavior is the same before the PR that Default Paragraph Style is last element.

Screenshot_20211206_220157

Default Style should be Default Paragraph Style from my point of view.

**Comment by Andreas-Kainz** [comment]
The issue from @pedropintosilva isn't related to the PR. So please review the PR and than add an issue if the some behavior from master should be changed.

**Comment by pedropintosilva** [comment]
> Is it cool draw isn't it?

no, it's also in writer.

> The issue from @pedropintosilva isn't related to the PR. So please review the PR and than add an issue if the some behavior from master should be changed.

True, sorry it's just very dificult to review stuff now and later (after it's merge and we want to rework or improved merged stuff) if there is no description in the commit message and if the commit subject is just "[component] update" : p

Could you please amend the commit  and add more info? If I understand it correctly this would do:
* In the subject (1st line): `Fix styles dropdown: make all styles searchable, remove separators`
* Empty line
* In the body:
```
The search in #styles-select didn't include all the styles in its search
results, some styles at the end of the list were being excluded.
List all the available styles by removing the end limit of the content
extraction.

As the predefined styles had unnecessary separators around them since
..explain why. Get rid of those separators  (default and clear).
```

I didn't understand this `3 sections...` as I didn't see that in the code.


-------
Notes for reference:
* The commit message should tell what the commit does, in imperative mood. If necessary, you can mention how the code used to work, too. But what actually is done by the commit should be in present tense. Not what you did. Not "Fixed hang in foo()" but "Fix hang in foo()". Your subject line should be able to fit into this `If applied, this commit will [your subject line here]`
* The first line should be clearly less than 80 characters. It is supposed to be a minimal summary. It can be called the subject of the commit. Do not end it with a period.
* If the change is very simple conceptually, that one line might be enough.
* The rest of the commit message describes the change in greater detail. This is the body of this commit message. The body is written after the subject line with one blank line in between. The blank line is used by various tools (such as 'git log', 'git show', etc.) to differentiate subject from body. Further paragraphs are also separated by blank lines.
* Explain the problem being solved by this commit. More importantly, explain why these changes are being made, as opposed to how. The 'why' part is your responsibility, the 'how' part is code's responsibility.

**Review by pedropintosilva — COMMENTED** [review]
waiting for amended commit here

**Review by pedropintosilva — APPROVED** [review]

**Pull request merged**
