### PR TITLE
private/marco/a11y/contenteditabl

### PR DESCRIPTION
**Pull request by mcecchetti**
- a11y: TextInput: switch from <textarea> to content editable <div>
- a11y: populating editable area with focused paragraph

### CODE REVIEW

**Comment by mmeeks** [comment]
I assume this requires: https://gerrit.libreoffice.org/c/core/+/152363 first ?

**Comment by mmeeks** [comment]
Nice - I forget what we need to do to re-run the checks; but re-basing and force pushing to the branch is prolly a good plan to re-trigger here (?) =)

**Comment by mcecchetti** [comment]
Usually I close and re-open the PR. ;-)
Anyway, as far as I can remember new merged commits are not immediately available here

**Review by eszkadev — APPROVED** [review]
looks good in general

one question: do we want to enable that unconditionally? probably worth adding some switch in coolwsd for that?

**Comment by mcecchetti** [comment]
> looks good in general

Thanks for your review.

> 
> one question: do we want to enable that unconditionally? probably worth adding some switch in coolwsd for that?

So, I plan to add such a switch, too. I hope to include this option in my next patch.
Later we should also allow a user  to enable/disable this feature through the UI.
I point out that at present it's enabled for Writer only.

**Comment by mcecchetti** [comment]
So, all tests checking the editable area content are passing now.
Also desktop and mobile tests are passing except for some `beforeEach` that's randomly failing.
Since failures are few, random and unrelated I think that's safe to merge the patch without waiting for having an all green run.

**Pull request merged**
