### PR TITLE
feat: Add UITheme option for light/dark to ui_defaults

### PR DESCRIPTION
**Pull request by juliushaertl**
Signed-off-by: Julius Härtl <jus@bitgrid.net>
Change-Id: Ief028dcec0daa2ae448f83df993e0e5ade594a7c

* Resolves: #6432
* Target version: master 

### Summary

This adds the option to provide a default theme through the form parameters ui_defaults. As the frontend code currently only uses a boolean flag I mapped just UITheme=dark to enable the dark mode, all other values will use light by default.

### Checklist

- [x] Code is properly formatted
- [x] All commits have Change-Id
- [x] I have run tests with `make check`
- [x] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by juliushaertl** [comment]
One minor flaw I notice is that in writer the page itself is still showing up as white until the `.uno:ChangeTheme` method has been handled, though the document content also doesn't seem to be available at that point in time, so maybe there is a way to also change the placeholder page to dark mode early. However I'm not sure where to start looking for that.

**Review by eszkadev — COMMENTED** [review]
code looks good

**Comment by juliushaertl** [comment]
Testing can also be done without integrator implementation by passing the ui_defaults to the debug.html:

https://localhost:9980/browser/05638f9c2/debug.html?file_path=/home/jus/repos/collaboraonline/online/test/data/hello-world.odt&theme=nextcloud&ui_defaults=UITheme%3Ddark

**Comment by eszkadev** [comment]
It doesn't work for me, tested with `&ui_defaults=UITheme%3Ddark`

**Comment by Darshan-upadhyay1110** [comment]
Same goes with not working :(

**Comment by juliushaertl** [comment]
> I have tried with the latest nextcloud server (master) and richdocuments (main)
> 
>     1. set NC to force dark theme
> 
>     2. but it didn't affect, document was still being opened with light mode

Sorry I missed to push the required part for that in richdocuments, pushed one commit to https://github.com/nextcloud/richdocuments/pull/2964

> I have also tried to add that line [#6436 (comment)](https://github.com/CollaboraOnline/online/pull/6436#issuecomment-1568520617) but it also didn't affect. I keep getting always light mode

Strange that should work fine. Could you check if clearing browser storage data might make a difference there? Maybe it still has the remembered state as it has from before this PR?

**Comment by Darshan-upadhyay1110** [comment]
@juliushaertl i got it why it is not giving any effect.  take took into function `getSavedStateOrDefault` in Control.UIManager.js file. in initiation of UI we are taking value form local storage that always lead to take value from local storage.
image

**Comment by Darshan-upadhyay1110** [comment]
there is fix needed to work UIDefault In this i am working on it and will post PR over here so you can connect the dots.

**Comment by juliushaertl** [comment]
Thanks @Darshan-upadhyay1110 I'm out sick today unfortunately but feel free to also push directly to this branch

**Comment by Darshan-upadhyay1110** [comment]
No worries. take care:)

**Comment by Darshan-upadhyay1110** [comment]
@pedropintosilva or @eszkadev  can anyone test this branch i have tested it. working good . now after last commit you can check ui_default dark.

**Comment by Darshan-upadhyay1110** [comment]
Just a heads up please clear local storage values for dark theme whene you chose to open new tab for same document to test otherwise you might not get right results as we wanted.

Priority to chosse dark mode is like this 

If you open first time with passed dark mode default value to true => it will render page in dark theme 
Then if user changes theme using Dark mode icon will work as usal ( will not consider default value because now users changes from ui => even if that page got refreshed )

**Review by Darshan-upadhyay1110 — APPROVED** [review]

**Review by eszkadev — APPROVED** [review]
I can confirm it now uses the ui_defaults parameter when provided, but after user manually switched mode using UI button -> then we remember that setting and ignore ui_defaults

**Review by pedropintosilva — APPROVED** [review]
I have-re tested  and it works (latest richdocuments + this PR), thanks!

**Comment by pedropintosilva** [comment]
> I can confirm it now uses the ui_defaults parameter when provided, but after user manually switched mode using UI button -> then we remember that setting and ignore ui_defaults

Yes, that's desirable. Thanks for checking it @eszkadev .

**Comment by Darshan-upadhyay1110** [comment]
@pedropintosilva  & @eszkadev thanks for the review  :)

**Pull request merged**
