### PR TITLE
feature: Add "Background Color" button to Table tab for setting table field background color

### PR DESCRIPTION
**Pull request by Darshan-upadhyay1110**
- Introduced a new button in the Table tab to set the background color of the currently selected table field(s).

Change-Id: I4fa2cc7a1003eafdee4d54acfea9faaa1a457254

* Resolves: # 
* Target version: master 

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by Darshan-upadhyay1110** [comment]
Hii @pedropintosilva need your advice here about what will be the best way to show this table bgcolor icon in table tab

For now i have added like this
image

Tried many places but it looks very odd in other places. Can you please take a look and give feedback on it

**Comment by Darshan-upadhyay1110** [comment]
Small change on CORE to update state after color change => https://gerrit.libreoffice.org/c/core/+/169835 ( MERGED)
Thanks @eszkadev

**Review by pedropintosilva — CHANGES_REQUESTED** [review]
I think we don't need to touch that cell operation group:
1. I would place the new icon more near to the `Number Format` button (this way it's easier for the user to remember that those 2 formatting buttons are nearby each other).
2. Replace the currency button with the currency button dropdown (similar as we use in online calc in the home tab)
3. Remove the format with decimal button (since the user can always access "Number Format" for more options)

result: 
image

**Comment by Darshan-upadhyay1110** [comment]
Point 1 and 3 are done. 

> Replace the currency button with the currency button dropdown (similar as we use in online calc in the home tab)

This option need some more R and D in Core side as i changed it to dropdown and made some changes as same as we do in Calc makes COOL to crash.
Also a note that in LO CORE i see writer does not have dropdown so to add that new feature i need to do more work in CORE.

@pedropintosilva can we merge this PR just as a Pure feature related to `Table cell background Color` ?

**Comment by Darshan-upadhyay1110** [comment]
Crash log 

```
coolforkit: /home/darshan/Collabora/COOL-24.04/libreoffice/vcl/source/app/salvtables.cxx:1089: virtual bool SalInstanceToolbar::get_menu_item_active(const rtl::OUString&) const: Assertion `m_xToolBox->GetItemBits(nItemId) & ToolBoxItemBits::DROPDOWN' failed.
kit-62132-62132 2024-07-03 21:58:49.043720 +0530 [ kitbroker_003 ] SIG   Fatal signal received: SIGABRT code: 18446744073709551610 for address: 0x3e80000f2b4
Recent activity:
Session count: 1
        view: 4, session 05e, rw, user: 'LocalUser#2', loading, type: text, lang: 
Commands:
        session: 05e: load doc: file:///tmp/user/docs/0kWW5lEjEcj1GSJo/hello-world.odt
        session: 05e: unoCommand : ToolbarMode?Mode:string=notebookbar_online.ui - 2024-07-03 16:28:28
        session: 05e: unoCommand : ShowRuler - 2024-07-03 16:28:28
        session: 05e: unoCommand : ToolbarMode?Mode:string=Default - 2024-07-03 16:28:28
        session: 05e: unoCommand : ToolbarMode?Mode:string=notebookbar_online.ui - 2024-07-03 16:28:28
        session: 05e: unoCommand : SidebarShow - 2024-07-03 16:28:28
        session: 05e: unoCommand : InsertTable - 2024-07-03 16:28:37

Backtrace 62132 - kit startup of 24.04.4.2 ad9b04885b:
/home/darshan/Collabora/COOL-24.04/online/coolforkit(_ZN7SigUtil13dumpBacktraceEv+0x7e)[0x5f1ef26d347e]
/home/darshan/Collabora/COOL-24.04/online/coolforkit(+0x11888d)[0x5f1ef26d388d]
/lib/x86_64-linux-gnu/libc.so.6(+0x42990)[0x7abaa8042990]
/lib/x86_64-linux-gnu/libc.so.6(pthread_kill+0x11b)[0x7abaa8099a1b]
/lib/x86_64-linux-gnu/libc.so.6(raise+0x16)[0x7abaa80428e6]
/lib/x86_64-linux-gnu/libc.so.6(abort+0xd7)[0x7abaa80268b7]
/lib/x86_64-linux-gnu/libc.so.6(+0x267db)[0x7abaa80267db]
/lib/x86_64-linux-gnu/libc.so.6(+0x39206)[0x7abaa8039206]
/home/darshan/Collabora/COOL-24.04/libreoffice/instdir/program/libvcllo.so(+0xee5422)[0x7aba9e6e5422]
/home/darshan/Collabora/COOL-24.04/libreoffice/instdir/program/libvcllo.so(+0x125bdc4)[0x7aba9ea5bdc4]
/home/darshan/Collabora/COOL-24.04/libreoffice/instdir/program/libvcllo.so(_ZN8jsdialog13ExecuteActionERKN3rtl8OUStringES3_RNSt7__debug3mapIS1_S1_St4lessIS1_ESaISt4pairIS2_S1_EEEE+0x2045)[0x7aba9eaabcf1]
/home/darshan/Collabora/COOL-24.04/libreoffice/instdir/program/libsofficeapp.so(+0x10658c)[0x7abaa7d0658c]
/home/darshan/Collabora/COOL-24.04/libreoffice/instdir/program/libsofficeapp.so(+0x106a86)[0x7abaa7d06a86]
/home/darshan/Collabora/COOL-24.04/online/coolforkit(_ZN12ChildSession11dialogEventERK12StringVector+0x141)[0x5f1ef261ba31]
/home/darshan/Collabora/COOL-24.04/online/coolforkit(_ZN12ChildSession12_handleInputEPKci+0x75f)[0x5f1ef263844f]
/home/darshan/Collabora/COOL-24.04/online/coolforkit(_ZN7Session13handleMessageERKSt6vectorIcSaIcEE+0x58)[0x5f1ef26cc368]
/home/darshan/Collabora/COOL-24.04/online/coolforkit(_ZN8Document14forwardToChildERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt6vectorIcS4_E+0x7c5)[0x5f1ef267df65]
/home/darshan/Collabora/COOL-24.04/online/coolforkit(_ZN8Document10drainQueueEv+0xb71)[0x5f1ef267f181]
/home/darshan/Collabora/COOL-24.04/online/coolforkit(_ZN13KitSocketPoll7kitPollEi+0x541)[0x5f1ef267fbc1]
/home/darshan/Collabora/COOL-24.04/libreoffice/instdir/program/libvcllo.so(_ZN14SvpSalInstance9ImplYieldEbb+0x262)[0x7aba9eb609ae]
/home/darshan/Collabora/COOL-24.04/libreoffice/instdir/program/libvcllo.so(_ZN14SvpSalInstance7DoYieldEbb+0xed)[0x7aba9eb60c81]
/home/darshan/Collabora/COOL-24.04/libreoffice/instdir/program/libvcllo.so(+0xf997f0)[0x7aba9e7997f0]
/home/darshan/Collabora/COOL-24.04/libreoffice/instdir/program/libvcllo.so(_ZN11Application5YieldEv+0x196)[0x7aba9e79a5d2]
/home/darshan/Collabora/COOL-24.04/libreoffice/instdir/program/libvcllo.so(_ZN11Application7ExecuteEv+0x1b9)[0x7aba9e7994df]
/home/darshan/Collabora/COOL-24.04/libreoffice/instdir/program/libsofficeapp.so(+0x3a254)[0x7abaa7c3a254]
/home/darshan/Collabora/COOL-24.04/libreoffice/instdir/program/libvcllo.so(_Z10ImplSVMainv+0x312)[0x7aba9e7ba41d]
/home/darshan/Collabora/COOL-24.04/libreoffice/instdir/program/libvcllo.so(_Z6SVMainv+0xd)[0x7aba9e7ba752]
/home/darshan/Collabora/COOL-24.04/libreoffice/instdir/program/libsofficeapp.so(soffice_main+0x141)[0x7abaa7caa151]
/home/darshan/Collabora/COOL-24.04/libreoffice/instdir/program/libsofficeapp.so(+0x118113)[0x7abaa7d18113]
/home/darshan/Collabora/COOL-24.04/online/coolforkit(_Z10lokit_mainRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES6_S6_S6_bbbbm+0x24ee)[0x5f1ef268730e]
/home/darshan/Collabora/COOL-24.04/online/coolforkit(+0x93b08)[0x5f1ef264eb08]
/home/darshan/Collabora/COOL-24.04/online/coolforkit(_Z18forkLibreOfficeKitRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES6_S6_+0x1066)[0x5f1ef26505d6]
/home/darshan/Collabora/COOL-24.04/online/coolforkit(_Z11forkit_mainiPPc+0x24b5)[0x5f1ef2653475]
/lib/x86_64-linux-gnu/libc.so.6(+0x28150)[0x7abaa8028150]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x89)[0x7abaa8028209]
/home/darshan/Collabora/COOL-24.04/online/coolforkit(_start+0x25)[0x5f1ef2615c15]

ERROR: Fatal signal! Attach debugger with:
sudo gdb --pid=62132
 or 
sudo gdb --q --n --ex 'thread apply all backtrace full' --batch --pid=62132
Sleeping 60s to allow debugging: attach 62132

```

**Comment by Darshan-upadhyay1110** [comment]
image

@pedropintosilva

**Review by pedropintosilva — APPROVED** [review]

**Pull request merged**
