### PR TITLE
Mobile Context Toolbars for writer [WIP] #2484

### PR DESCRIPTION
**Pull request by Andreas-Kainz**
Signed-off-by: Andreas-Kainz <kainz.a@gmail.com>
Change-Id: I8d7711a9002f7a49e586beda8605485df85d2ede

* Resolves: #2484
* Target version: master 

### Summary
Show Context Related Toolbar commands within Mobile Bottom Toolbar

### TODO
- [ ] You can have ONLY one context item, so `context: ['Graphic']` and `context: ['Draw']` are the same. Would be nicer if you can use `context: ['Graphic|Draw']` like in https://github.com/CollaboraOnline/online/blob/dad92dee2523f67c5d592727fbd9b0c9eb8e400a/loleaflet/src/control/Control.NotebookbarWriter.js#L57
- [ ] `context: ['default]`  wasn't defined so at the initial load you don't see commands.

### CODE REVIEW

**Comment by Andreas-Kainz** [comment]
This is a WIP PR. as default isn't available you don't see any command at the initial load of the bottom bar only if you change from text to another context, text will work.
In addition you see that if we can't use more than one context entry, the toolbar has a lot of copy paste elements.

@eszkadev I know you have a lot on your todo list. I can't fix it myself and I need this two items fixed to go ahead with context toolbars, ...

**Comment by Andreas-Kainz** [comment]
This PR isn't for push to master. It's for fix the issues.

**Comment by eszkadev** [comment]
@Andreas-Kainz it is possible to define multiple contexts, [ ... ] is an array, so you can do: ['Text', 'Graphic']

**Comment by eszkadev** [comment]
@Andreas-Kainz I've added support for "default" context

BTW: please rebase

**Comment by Andreas-Kainz** [comment]
Thanks for the work Szymon. It work very well. As there was a lot of changes in the past and the change here is very tiny. I make the change with a new MR. Thanks for your hard work.

**Pull request closed without merging**
