### PR TITLE
calc: Enable sheet protection

### PR DESCRIPTION
**Pull request by hfiguiere**
Require LOKit change Ib8e8209225d027472c1f2eef57839df5784acf30 
https://gerrit.libreoffice.org/c/core/+/163205

Change-Id: Ie54b355ad794a0e34fabbd8e56b4a17a936686f7

* Resolves: Part of #551 
* Target version: master 

### TODO

- [ ] Merge https://gerrit.libreoffice.org/c/core/+/163205

### Checklist

- [x] Code is properly formatted
- [x] All commits have Change-Id
- [x] I have run tests with `make check`
- [x] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Review by mmeeks — APPROVED** [review]
Looks plausible; will need a back-port to the co-23.05 branch =)

**Comment by timar** [comment]
The Protect sheet dialog is not async.
image

**Comment by hfiguiere** [comment]
I am working on making it async.

As for the layout:

image

**Comment by hfiguiere** [comment]
backport #8249

**Pull request merged**
