### PR TITLE
[co-23.05] wsd, clientsession: guard against negative w/h in clientvisiblearea

### PR DESCRIPTION
**Pull request by vmiklos**
(cherry picked from commit c3c80f00a686b6ef8914f89e895828ba842703a9)

Signed-off-by: Miklos Vajna <vmiklos@collabora.com>
Change-Id: I34435276afbdc02b6e820b630560608f16f3a0e0

### CODE REVIEW

**Comment by vmiklos** [comment]
Quoting <https://cpci.cbg.collabora.co.uk:8080/job/github_online_co-23.05_debug_vs_co-23.05/87/console>:

> Your configFile is invalid: /home/collabora/jenkins/workspace/github_online_co-23.05_debug_vs_co-23.05/cypress_test/cypress.config.ts
> SyntaxError: Unexpected token '('

Hmm, let's retry.

**Comment by vmiklos** [comment]
Quoting <https://cpci.cbg.collabora.co.uk:8080/job/github_online_co-23.05_debug_vs_co-23.05/88/console>:

> Your configFile is invalid: /home/collabora/jenkins/workspace/github_online_co-23.05_debug_vs_co-23.05/cypress_test/cypress.config.ts
> SyntaxError: Unexpected token '('

Right, so this wasn't a one-off problem, sadly.

**Comment by vmiklos** [comment]
Rebasing to see if this gets better.

**Comment by vmiklos** [comment]
https://cpci.cbg.collabora.co.uk:8080/job/github_online_co-23.05_debug_vs_co-23.05/122/console

Cypress failure because of too much parallelism, retry.

**Comment by vmiklos** [comment]
@caolanm could you please review? Thanks.

This is just a fuzzer fix: non-required iOS still fails with some JS error after retry, to I would tend to suggest ignoring it for now, this was peding CI for 5 days already.

**Review by caolanm — APPROVED** [review]

**Pull request merged**
