### PR TITLE
cypress:added font spec for desktop writer,impress,calc

### PR DESCRIPTION
**Pull request by Rash419**
Signed-off-by: Rash419 <rashesh.padia@collabora.com>
Change-Id: Iecd6671be39cd686f47129cde936b705a411f122

* Target version: master

### CODE REVIEW

**Review by lpranam — CHANGES_REQUESTED** [review]
missing mobile impress test.

**Comment by Rash419** [comment]
> missing mobile impress test.

its already there ,name is different apply_font_text_spec.js

**Review by lpranam — APPROVED** [review]

**Comment by eszkadev** [comment]
please rebase, cypress should be fixed now

**Comment by Rash419** [comment]
> please rebase, cypress should be fixed now

thanks :)

**Pull request merged**
