### PR TITLE
cool#10630 doc electronic sign: implement support for redirect-based providers

### PR DESCRIPTION
**Pull request by vmiklos**
- **net: fix clang 18 -Werror,-Wvla-cxx-extension**
- **cool#10630 doc electronic sign: implement support for redirect-based providers**

### CODE REVIEW

**Comment by vmiklos** [comment]
https://cpci.cbg.collabora.co.uk:8080/job/github_online_master_debug_vs_co-24.04/3609/console failed in unit-storage, retry to see if that's persistent.

**Comment by vmiklos** [comment]
https://cpci.cbg.collabora.co.uk:8080/job/github_online_master_debug_vs_co-24.04/3610/console failed in unit-save-torture, retry.

**Comment by vmiklos** [comment]
@caolanm could you please review this? Thanks.

The JS part was more straightforward than I expected, phew. For the warnings fix, one more alloca after this and I'm done.

**Review by caolanm — APPROVED** [review]
thankfully small

**Pull request merged**
