### PR TITLE
fix:formulabar_spec failing

### PR DESCRIPTION
**Pull request by Rash419**
Change-Id: I4b5eaa5294177b116d793ed8fc0d8925ee29f447
Signed-off-by: Rash419 <rashesh.padia@collabora.com>

### CODE REVIEW

**Review by lpranam — APPROVED** [review]

**Comment by lpranam** [comment]
this is a regression from a41ab8f. let's wait for a while this is not the correct solution.

**Review by lpranam — CHANGES_REQUESTED** [review]
I think we should revert a41ab8f. what do you suggest @pedropintosilva

**Comment by kendy** [comment]
Let's rather use https://github.com/CollaboraOnline/online/pull/2153 if it passes :-)

**Comment by lpranam** [comment]
closing this in favour of #2153

**Pull request closed without merging**
