### PR TITLE
cool#8465 clipboard: improve handling of plain text copy, complex case

### PR DESCRIPTION
**Pull request by vmiklos**
In case the selection is complex (not simple), we used to just request
HTML, and then the browser converted that to plain text, which has the
downsides already mentioned in commit
7f9de46688a64b42ba8f65cceb9fe2c6ddab89ef (cool#8465 clipboard: improve
handling of plain text copy, simple case, 2024-03-08).

Steps to support this:

1) Clipboard.js now asks for the text/html,text/plain;charset=utf-8 MIME
   types.

2) wsd: ClientRequestDispatcher::handleClipboardRequest() now maps this
   to DocumentBroker::CLIP_REQUEST_GET_HTML_PLAIN_ONLY

3) ClientSession::handleClipboardRequest() maps this to the HTML+plain
   text MIME type list.

4) kit: ChildSession::getClipboard() is now improved to take a list of
   MIME types, not just 1 or everything.

5) kit: ChildSession::getClipboard() now emits JSON in case not all, but
   multiple MIME types are requested.

6) wsd: ClientSession::postProcessCopyPayload() now knows how to
   postprocess clipboardcontent messages, which may or may not be JSON
   (it's JSON if more formats are requested explicitly, leaving the 1
   format or all format cases unchanged)

7) Control.DownloadProgress.js now handles the case when we get JSON and
   sets the core-provided plain text next to the HTML.

   Leave the handling of non-JSON case in, because this means we can
   copy from an old COOL server to a new one.

Note that this approach has the benefit that once the clipboard marker
is inserted, the length of the text/html format would change, which
means we can't parse the clipboard data till the marker is removed.
Emitting JSON for html+text means adding the marker keeps the ability to
parse the HTML and the plain text part of the clipboard in JS.

Signed-off-by: Miklos Vajna <vmiklos@collabora.com>
Change-Id: I67a1f669e8a638d34cc25a2f288a7b30884b9892

### CODE REVIEW

**Comment by vmiklos** [comment]
CI failed to full disk, also use the opportunity to remove some unused includes.

**Comment by vmiklos** [comment]
> https://cpci.cbg.collabora.co.uk:8080/job/github_online_master_debug_vs_co-24.04/198/console

calc/annotation_spec.js failed, retry.

**Review by mmeeks — APPROVED** [review]
Looks sensible to me - and improving =)
Thanks!

**Comment by vmiklos** [comment]
OK, then just need to get cypress to pass and can merge.

> https://cpci.cbg.collabora.co.uk:8080/job/github_online_master_debug_vs_co-24.04/202/console

Fails in writer/invalidations_spec.js

> https://cpci.cbg.collabora.co.uk:8080/job/github_online_master_debug_vs_co-24.04/207/console

Fails in writer/invalidations_spec.js

> https://cpci.cbg.collabora.co.uk:8080/job/github_online_master_debug_vs_co-24.04/214/console

Here writer/invalidations_spec.js passes, but then later unit-wopi-save-on-exit fails, and unit-wopi-save-on-exit passes for me locally. I noticed some hanging processes on the builder (hanging since 12th March), I've killed those, perhaps that'll help.

**Pull request merged**
