### PR TITLE
private/pedro/fix vex for mobile

### PR DESCRIPTION
**Pull request by pedropintosilva**
- Mobile: Fix vex dialogs that still need vex-close
- Mobile: Fix vex dialogs: Insert comment missing class
- Mobile: Fix vex dialogs: add missing flex direction and grow

### CODE REVIEW

**Comment by pedropintosilva** [comment]
Could you (one of you)  pretty please review this?

**Review by eszkadev — APPROVED** [review]

**Comment by pedropintosilva** [comment]
unrelated unit test keeps failing

**Comment by pedropintosilva** [comment]
_rebasing and pushing_

**Review by gokaysatir — APPROVED** [review]
Thanks for the fix :)

**Pull request merged**
