### PR TITLE
loleaflet: Refresh the page subject to annotation deletion.

### PR DESCRIPTION
**Pull request by yunusbulutt**
Deleted comment was only looked up on current page. Behaviour is improved.

Change-Id: Idb6d8ca3e034075434ba11fc3603da1cf2b31e88

### CODE REVIEW

**Comment by mrkara** [comment]
@yunusbulutt Thank you for the pull request!

But it seems like there is some mix-up? Is the commit 20fbc1b intentionally included in here?

**Comment by yunusbulutt** [comment]
Hi @mrkara Please ignore that commit. I think it happened accidentally.

**Comment by mrkara** [comment]
> Hi @mrkara Please ignore that commit. I think it happened accidentally.

So do you need help to remove it from the pull request? (You just need to remove that commit and then `git push --force-with-lease` to your forked repo again. The pull request will be automatically refreshed with the new content.)

**Comment by yunusbulutt** [comment]
@mrkara I got a little messed up here. I sent a new pull request.

**Comment by mrkara** [comment]
> @mrkara I got a little messed up here. I sent a new pull request.

Oh, I see what happened. Seems like the wrong commit was deleted. No worries. Better luck next time. ;)

**Pull request closed without merging**
