### PR TITLE
pull request for issue #482

### PR DESCRIPTION
**Pull request by kuesji**
added comma seperated author list support ( usable by `--csv file` format )
removed mail addresses from author list

Signed-off-by: kuesji koesnu <kuesji@koesnu.com>
Change-Id: I369794dfb0db978c890b7691e4101f8fdf316302

* Resolves: #482 
* Target version: master 

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [x] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [x] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by mrkara** [comment]
@kuesji Thank you for the pull request! :)

I have tried it with `scripts/extract_translator.sh --csv translator-credits.txt -o new-credits.txt` and it accepted the comma separated list, but the output is still the same as before (not comma-separated but newline-separated). Am I missing something?

**Comment by kuesji** [comment]
my bad. i thought just input formatted as comma seperated, not output.

**Comment by mrkara** [comment]
> my bad. i thought just input formatted as comma seperated, not output.

@kuesji  No worries. It looks almost perfect now. One last tiny bit: Can we have the output list with one space after each comma, just like the input? :)

**Comment by kuesji** [comment]
yes, it is done.

**Comment by mrkara** [comment]
@kuesji I'm still getting comma-separated list without space after each comma. But it's a tiny detail. Let's get this merged now. Thank you again. Great job! :+1:

**Comment by mrkara** [comment]
@kuesji Please feel free to pick up any task from the [easy hacks](https://collaboraonline.github.io/post/easyhacks/) list, or any other issue of your liking. Your contributions are highly appreciated, and we're looking forward to seeing more of that. :)

**Pull request merged**
