### PR TITLE
cool#10316 fix server version mismatch warning

### PR DESCRIPTION
**Pull request by timar**
We resized the hash to 8 characters, which incidentally worked when our repo was smaller. Now short hash is 10 chars long.

Change-Id: Ib737e9c011488fbf085cfc2be3dd2a9b6e6daa0b

* Resolves: #10316 
* Target version: master 

**Note:** this bug does not effect official CODE/COOL packages. So the impact is small, fortunately. I checked, and on the machine where we build packages, `git log -1 --format=%h` produces 8 character long hashes. Only on my dev machine I saw 10 character long hashes.

### CODE REVIEW

**Comment by timar** [comment]
@Rash419 I've been struggling with this for 2 days. See https://cpci.cbg.collabora.co.uk:8080/job/github_online_master_debug_vs_co-24.04_cypress_multi_user/1887/console
You touched this part last time, and I don't know what's wrong. Content of input field is cleared in theory. But in fact it isn't! Expected 'F6', actual 'D8F6'?! 
I do not think it's related to my change in C++...

**Comment by timar** [comment]
Well, I see that other PRs pass. So it made me wonder. Although the browser cache was forcefully set for cypress (`--forcecaching`) it was not in effect because of the bug that I fixed. 
We set it here: https://github.com/CollaboraOnline/online/blob/d10e7f5471623357ef7282891622865248e68417/wsd/FileServer.cpp#L548
Then we switch it off, if hashes mismatch, later: https://github.com/CollaboraOnline/online/blob/d10e7f5471623357ef7282891622865248e68417/wsd/FileServer.cpp#L567
So now it seems we have to check cypress tests, whether they are stable with enabled browser cache!

**Comment by Rash419** [comment]
FWIW, I tried reproducing cypress failure with your patch but I couldn't reproduce it

**Comment by timar** [comment]
```
      cy:command ✔  clear	
      cy:command ✔  get	@input
      cy:command ✔  assert	expected **<input.ui-combobox-content.addressInput.jsdialog>** to be **empty**
      cy:command ✔  get	@input
      cy:command ✔  type	F6{enter}
      cy:command ✔  get	@input
      cy:command ✘  assert	expected **<input.ui-combobox-content.addressInput.jsdialog>** to have value **F6**, but the value was **D8F6**
```
What is this? Autofill?

**Pull request merged**
