### PR TITLE
Notebookbar for Android Tablets

### PR DESCRIPTION
**Pull request by merttumer**
* Resolves: # 
* Target version: master 

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by tml1024** [comment]
Kendy told me to merge this in pieces, checking that it doesn't affect the iOS app badly, so doing that (in separate pull requests).

**Comment by kendy** [comment]
Thanks a lot @tml1024 !

**Comment by tml1024** [comment]
Mert's https://github.com/CollaboraOnline/online/commit/b9452112c58b8e0b0fd0271d8d6b09a60094028d seems to fix the sidebar issue in a much simpler way. I merged that on @kendy 's request.

**Comment by tml1024** [comment]
All commits have been merged to co-6-4 (as individual PRs) now.

**Comment by tml1024** [comment]
The branch can probably be deleted?

**Pull request closed without merging**
