### PR TITLE
loleaflet: Bump eslint version to 6.0.0

### PR DESCRIPTION
**Pull request by ayhanyalcinsoy**
* Resolves: # 
* Target version: master 

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by ayhanyalcinsoy** [comment]
20 ve 21 ekim commitlerini neden dahil etti anlamadım. git status ile kontrol ettim temiz diyordu

**Comment by mrkara** [comment]
> 20 ve 21 ekim commitlerini neden dahil etti anlamadım. git status ile kontrol ettim temiz diyordu

I think the problem is caused by the `Merge branch...` commits you have there. We don't use merge commits on main repo. We do rebases instead.

**Comment by ayhanyalcinsoy** [comment]
Are the corrections appropriate? If it is ok, I will recommit them after fixing my local branch.

**Comment by ayhanyalcinsoy** [comment]
another coder works on it

**Pull request closed without merging**
