### PR TITLE
fix(calc): Improve grid colors in dark mode

### PR DESCRIPTION
**Pull request by juliusknorr**
Change-Id: Ie379efb16f5e82de8d53203b88fdccad15e8da37

* Resolves: # 
* Target version: master 

### Summary

This allow to adjust the calc grid line color through css variables. It also sets a different value for dark mode to make the contrast ratio with the background similar to light mode.

Change might be subtle but makes calc in dark mode look much nicer as discussed at some point already with @pedropintosilva and @jancborchardt

One issue seems still that a reload is required, on switching to dark mode the grid color is not picked up again. I'm not sure what the best way would be to update the sectionProperties values in that case. Maybe someone has a pointer there?

| Before | After |
|---|---|
| image | image |
| image | image |

### Checklist

- [ ] I have run `make prettier-write` and formatted the code.
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Review by pedropintosilva — APPROVED** [review]

**Comment by pedropintosilva** [comment]
Pressed Retry test

**Comment by juliusknorr** [comment]
Could be a follow up but that would still be interesting:

> One issue seems still that a reload is required, on switching to dark mode the grid color is not picked up again. I'm not sure what the best way would be to update the sectionProperties values in that case. Maybe someone has a pointer there?

**Review by gokaysatir — APPROVED** [review]
Looks beautiful, thanks for the improvements :)

**Comment by gokaysatir** [comment]
> Could be a follow up but that would still be interesting:
> 
> > One issue seems still that a reload is required, on switching to dark mode the grid color is not picked up again.

I added one commit for the follow up, i hope that's ok:)

Re-triggered the tests.

**Comment by juliusknorr** [comment]
Great, thanks for that 👍

**Pull request merged**
