### PR TITLE
create translator list from commit log via "Translated using Weblate" text

### PR DESCRIPTION
**Pull request by kuesji**
this script search "Translated using Weblate" message in commit log and generates list of translators.

Signed-off-by: kuesji koesnu <kuesji@koesnu.com>

* Resolves: # 
* Target version: master 

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ x ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by kuesji** [comment]
i think mentioning @mrkara will be good move. idk.
i can't run `make check' on local due some c++ errors.

`depbase=`echo kit/ChildSession.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DHAVE_CONFIG_H -I.  -pthread -DLOOLWSD_DATADIR='"/usr/local/share/loolwsd"' -DLOOLWSD_CONFIGDIR='"/usr/local/etc/loolwsd"' -DDEBUG_ABSSRCDIR='"/data/home/kuesji"' -I./common -I./net -I./wsd -I./kit  -DNDEBUG   -g -O2 -std=c++11 -Wall -Wextra -Wshadow -Werror -MT kit/ChildSession.o -MD -MP -MF $depbase.Tpo -c -o kit/ChildSession.o kit/ChildSession.cpp &&\
mv -f $depbase.Tpo $depbase.Po
kit/ChildSession.cpp: 'bool ChildSession::formFieldEvent(const char*, int, const StringVector&)' üye işlevinde:
kit/ChildSession.cpp:1498:25: hata: 'using element_type = class lok::Document' {aka 'class lok::Document'} has no member named 'sendFormFieldEvent'
 1498 |     getLOKitDocument()->sendFormFieldEvent(sArguments.c_str());
      |                         ^~~~~~~~~~~~~~~~~~
kit/ChildSession.cpp: 'bool ChildSession::completeFunction(const char*, int, const StringVector&)' üye işlevinde:
kit/ChildSession.cpp:1517:25: hata: 'using element_type = class lok::Document' {aka 'class lok::Document'} has no member named 'completeFunction'
 1517 |     getLOKitDocument()->completeFunction(functionName.c_str());
      |                         ^~~~~~~~~~~~~~~~
kit/ChildSession.cpp: 'bool ChildSession::selectText(const char*, int, const StringVector&, LokEventTargetEnum)' üye işlevinde:
kit/ChildSession.cpp:1603:29: hata: 'using element_type = class lok::Document' {aka 'class lok::Document'} has no member named 'setWindowTextSelection'; did you mean 'setTextSelection'?
 1603 |         getLOKitDocument()->setWindowTextSelection(winId, swap == "true", x, y);
      |                             ^~~~~~~~~~~~~~~~~~~~~~
      |                             setTextSelection
kit/ChildSession.cpp: 'void ChildSession::rememberEventsForInactiveUser(int, const string&)' üye işlevinde:
kit/ChildSession.cpp:2331:22: hata: 'LOK_CALLBACK_INVALIDATE_SHEET_GEOMETRY' was not declared in this scope; did you mean 'LOK_CALLBACK_INVALIDATE_HEADER'?
 2331 |              type == LOK_CALLBACK_INVALIDATE_SHEET_GEOMETRY ||
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                      LOK_CALLBACK_INVALIDATE_HEADER
kit/ChildSession.cpp: 'void ChildSession::loKitCallback(int, const string&)' üye işlevinde:
kit/ChildSession.cpp:2612:10: hata: 'LOK_CALLBACK_VALIDITY_INPUT_HELP' was not declared in this scope; did you mean 'LOK_CALLBACK_VALIDITY_LIST_BUTTON'?
 2612 |     case LOK_CALLBACK_VALIDITY_INPUT_HELP:
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |          LOK_CALLBACK_VALIDITY_LIST_BUTTON
kit/ChildSession.cpp:2655:10: hata: 'LOK_CALLBACK_CALC_FUNCTION_LIST' was not declared in this scope; did you mean 'LOK_CALLBACK_CELL_SELECTION_AREA'?
 2655 |     case LOK_CALLBACK_CALC_FUNCTION_LIST:
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |          LOK_CALLBACK_CELL_SELECTION_AREA
kit/ChildSession.cpp:2658:10: hata: 'LOK_CALLBACK_TAB_STOP_LIST' bu etki alanında bildirilmemiş
 2658 |     case LOK_CALLBACK_TAB_STOP_LIST:
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
kit/ChildSession.cpp:2661:10: hata: 'LOK_CALLBACK_FORM_FIELD_BUTTON' bu etki alanında bildirilmemiş
 2661 |     case LOK_CALLBACK_FORM_FIELD_BUTTON:
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
kit/ChildSession.cpp:2664:10: hata: 'LOK_CALLBACK_INVALIDATE_SHEET_GEOMETRY' was not declared in this scope; did you mean 'LOK_CALLBACK_INVALIDATE_HEADER'?
 2664 |     case LOK_CALLBACK_INVALIDATE_SHEET_GEOMETRY:
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |          LOK_CALLBACK_INVALIDATE_HEADER
`

**Comment by mrkara** [comment]
@kuesji Hi! Thank you for the pull request! :)

`make check` isn't needed for this one as it doesn't change anything in the compiled parts. Anyway, you may follow the [build instructions](https://collaboraonline.github.io/post/build-code/) for your distro, or just [use a prebuilt GitPod container](https://forum.collaboraonline.com/t/start-developing-cool-on-any-platform-in-5-minutes/52).

However, there are 2 nitpicks that needs fixing before moving on with the review:
* License isn't compatible with the repo. We accept contributions under the terms of MPL v. 2.0. (You may check the files in the same directory to see how it is applied.)
* The commit is missing a ChangeId
  * To get the commit hook which generates ChangeIds automatically, just run `./scripts/refresh-git-hooks` and then `git commit --amend`

Could you please fix the points above, amending your commit?

**Comment by mrkara** [comment]
@kuesji I have also checked functionality for the last month, and it seems to be working like a charm. :+1: 

So if you can just fix the license, and the ChangeId, we can merge this pull request in no time. :)

**Comment by kuesji** [comment]
i fixed these issues.

**Comment by mmeeks** [comment]
Nice work - and long overdue ! =) thanks ...

**Pull request merged**
