### PR TITLE
Handle the callback for missing fonts

### PR DESCRIPTION
**Pull request by tml1024**
For now, just display it using an infobar. UI experts, feel free to
design something more appropriate.

Signed-off-by: Tor Lillqvist <tml@collabora.com>
Change-Id: I0b6e592a51441299cc08d0e42ba3b5c5087b30db

* Resolves: # 
* Target version: master 

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by tml1024** [comment]
@kendy , the corresponding pieces in core are: https://gerrit.libreoffice.org/c/core/+/138802 (master) and https://gerrit.libreoffice.org/c/core/+/138766 (co-22.05).

**Comment by tml1024** [comment]
Sore piece is now merged also in co-22.05.

**Comment by pedropintosilva** [comment]
Thank you @tml1024 let me paste here the screenshot relative to this change
Screen Shot 2022-09-07 at 13 37 29

**Review by pedropintosilva — APPROVED** [review]
Tested. It works. WRT design and the component used I think it makes sense. Probably infobar in general should be improved (it seems we lost some styling) but that is outside of the scope of this PR. Thanks!

**Pull request merged**
