### PR TITLE
Push unpremul and reorder to client

### PR DESCRIPTION
**Pull request by caolanm**
optimized build server flamegraph before:
perf-before

optimized build server flamegraph after:
perf-after

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Review by mmeeks — APPROVED** [review]
Looks great to me =)
Thanks Caolan.

**Review by mmeeks — APPROVED** [review]
Reads beautifully =) thanks !

**Comment by mmeeks** [comment]
One more minor optimization here; since we do the ==255 case and the ==0 case - we should prolly also optimize the: "is it the same as the last un-pre-multiply" case - and just copy the answer from the previous pixel - I imagine lots of times we then end up with just a slowish pixel copying operation instead of the math to un-pre-multiply which is noticably slower in the JS - would be easy as a follow-up. =)

**Comment by caolanm** [comment]
my effort of https://github.com/CollaboraOnline/online/pull/6724 seemed to make things worse rather than better

**Pull request merged**
