### PR TITLE
browser: slideshow: fix click selection image

### PR DESCRIPTION
**Pull request by hcvcastro**
Update to latest UI change adding the arrow back button

Change-Id: Ic6684f86c80c88ba834804ed3421ce5335632b2d
Signed-off-by: Henry Castro <hcastro@collabora.com>

### CODE REVIEW

**Review by Darshan-upadhyay1110 — COMMENTED** [review]
Tested and it works good. 
- One thing if you can add here is when we open slide sorter by default it should have the Current slide selected.

- I think border color should be something eye catchy, not sure but something like Red or blue section shade maybe ? @pedropintosilva can you help out here

**Comment by hcvcastro** [comment]
Changes done

**Comment by pedropintosilva** [comment]
Thanks @hcvcastro I think we can merge!

**Comment by pedropintosilva** [comment]
Please @Darshan-upadhyay1110 push a new commit on of top of those if you can (maybe you need to add hcvcastro       git@github.com:hcvcastro/online.git as a new remote etc

Issue I see:
* The dimensions change every time I click in another because we are only applying border in once preview
* The border could be better

:


/* Element | http://localhost:9980/browser/85fe110e92/cool.html?WOPISrc=http://localhost:9980/wopi/files/home%2Fpedro%2FLibreOffice%2Fonline-master%2Ftest%2Fsamples%2Fimpress-edit.fodp& */

#slides-preview > img:nth-child(2) {
  border: 3px solid #BF520F;
  padding: 1px;
  border-radius: 3px;
}

/* Inline #0 | http://localhost:9980/browser/85fe110e92/cool.html?WOPISrc=http://localhost:9980/wopi/files/home%2Fpedro%2FLibreOffice%2Fonline-master%2Ftest%2Fsamples%2Fimpress-edit.fodp& */

#slides-preview img {
  border: 1px solid transparent;
}


That orange it was just an example  we should probably take --orange1-txt-primary-color: 163, 62, 3; instead that is in our palette

**Comment by pedropintosilva** [comment]
but if this passes and Darshan didn't push nothing we can always merge and then create a new PR

**Comment by Darshan-upadhyay1110** [comment]
Thanks, Pedro, for the feedback and code for CSS change. 🙇🏼

**Review by Darshan-upadhyay1110 — APPROVED** [review]

**Pull request merged**
