### PR TITLE
Fix failing test mobile/calc/spellchecking_spec.js (forward port)

### PR DESCRIPTION
**Pull request by neilguertincollabora**
Test failed in 23.05 because of a change in .leaflet-marker-icon
Rewrite openContextMenu and remove uses of .leaflet-marker-icon

23.05 core change that caused the failure: https://gerrit.libreoffice.org/c/core/+/164701
23.05 pull request: https://github.com/CollaboraOnline/online/pull/8588

Change-Id: Iecfacdd192ea723001ed56e6c9f0c32645a6af2c

* Resolves: # 
* Target version: master 

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by gokaysatir** [comment]
This doesn't pass for me locally.

**Comment by gokaysatir** [comment]
> > This doesn't pass for me locally.
> 
> What is the failure message?

I don't know why i didn't copy the error message, assumed that it'd also fail for you i guess :)

Now i checked it again and it passes locally. Let me check the code and most probably approve in a few minutes.

**Review by gokaysatir — APPROVED** [review]
Thanks @neilguertincollabora :)

**Review by mcecchetti — APPROVED** [review]
Looks good to me.

**Comment by neilguertincollabora** [comment]
Was merged with https://github.com/CollaboraOnline/online/pull/8602

**Pull request closed without merging**
