### PR TITLE
NB add LanguageMenu to Review Tab

### PR DESCRIPTION
**Pull request by Andreas-Kainz**
The LanguageMenu from the Hamburger Menu was
now added also the Review Tab.

Signed-off-by: andreas kainz <kainz.a@gmail.com>
Change-Id: I927ec425c0e63ca4fe420369439eb96c80b41bb8

BUG: #4083 

image

### CODE REVIEW

**Comment by Andreas-Kainz** [comment]
@eszkadev I added the command from Hamburger Menu which are the same commands than for the menubar. In the Review tab where I add the command, the commands wasn't shown. Any idea how to fix it?

When the LanguageMenu was added to the NB, ALL commands from the Hamburger Menu was available so the Hamburger Menu can be removed @pedropintosilva.

**Comment by eszkadev** [comment]
`// initialize languages list
builder.map.on('commandvalues', menubar._onInitLanguagesMenu, menubar);
app.socket.sendMessage('commandvalues command=.uno:LanguageStatus');`

from browser/src/control/Control.NotebookbarBuilder.js probably is needed.

but we need to modify `_onInitLanguagesMenu` to work with new popup

I will add code to this PR

**Comment by Andreas-Kainz** [comment]
Fyi I played around but can't fix this issue myself.

**Comment by eszkadev** [comment]
I added items in the list but it doesn't work due to overflow problem (submenu is not visible)

**Comment by eszkadev** [comment]
submenu fixed - ready for review

**Comment by pedropintosilva** [comment]
thanks @eszkadev !

**Comment by pedropintosilva** [comment]
_testing_

**Comment by pedropintosilva** [comment]
_merging since cypress tests pass_

**Pull request merged**
