### PR TITLE
clipboard: introduce paste special menu entries

### PR DESCRIPTION
**Pull request by eszkadev**
It makes paste special feature more visible to the users
Also move paste special popup code to the clipboard.js so it is easiet to share the code.

What to do with notebookbar mode: to be discussed...

### CODE REVIEW

**Comment by mmeeks** [comment]
Looks lovely to me - ctrl-alt-shift-v is un-findable for anyone who doesn't look at help - which is ~95% of users =)

**Review by pedropintosilva — DISMISSED** [review]
Thanks 
image

**Comment by pedropintosilva** [comment]
I think we should probably do the same for notebookbar mode

**Comment by pedropintosilva** [comment]
have the paste bigtoolitem to be a menu (icon plus arrow down) that would show that option (so, reusing the menu contro we are already using in other places like formatting Mark etc

**Comment by eszkadev** [comment]
- hints: done
- Paste Special dialog now doesn't trigger error in the console when enabled for jsdialogs (see https://forum.collaboraonline.com/t/how-to-help-with-jsdialogs-development-porting-dialogs-to-native-html/964/2)

**Review by pedropintosilva — APPROVED** [review]

**Pull request merged**
