### PR TITLE
Hide exportpdf command in the android app

### PR DESCRIPTION
**Pull request by Minion3665**
Curently, the exportpdf command hangs in the android app. A fix is in progress, but as a stopgap solution disabling the command will avoid people getting stuck

Change-Id: Ied74c3f1fa57356542f3f71e1becbae81f5af7fc

### CODE REVIEW

**Comment by pedropintosilva** [comment]
Looks good to me but I don't have android setup to test it, added @eszkadev as reviewer

**Review by eszkadev — APPROVED** [review]
code looks good (not have android ready to test local-build)

**Comment by eszkadev** [comment]
@pedropintosilva just noticed: Draw app doesn't have grouped "Download as" in menu, is that expected?

**Comment by pedropintosilva** [comment]
> @pedropintosilva just noticed: Draw app doesn't have grouped "Download as" in menu, is that expected?

No

**Comment by Minion3665** [comment]
> > @pedropintosilva just noticed: Draw app doesn't have grouped "Download as" in menu, is that expected?
> 
> No

does this block merge here or is there a separate issue for it?

**Pull request merged**
