### PR TITLE
fix: changed "Twitter" to "𝕏 (Twitter)"

### PR DESCRIPTION
**Pull request by BandhiyaHardik**
Twitter is now known as 𝕏.

* Resolves: # https://github.com/CollaboraOnline/online/issues/7562
* Target version: master 

### Summary
It is updating Twitter to it's new name 𝕏.

### TODO

- [ ] ...

### Checklist

- [x] Code is properly formatted
- [x] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by Minion3665** [comment]
Hey there @BandhiyaHardik! Thanks for your change, it's always good to keep things up-to-date like this :)

Before we can merge, we'll need you to update your commit message a little bit...
- You need to sign-off your commit, if you're not sure how to then you can find instructions here: https://github.com/CollaboraOnline/online/pull/7563/checks?check_run_id=18163427573
- You need to have a change ID, this is a random trailer on your commit that allows us to track it even if is later amended/rebased etc. you can edit your commit to have this in only a few steps:
  - `cp .git-hooks/commit-msg .git/hooks/commit-msg`
  - `git commit --amend`
  - `git push -f `

Thanks for your diligence so far, hopefully we'll be able to get this merged soon :)

**Comment by BandhiyaHardik** [comment]
> Hey there @BandhiyaHardik! Thanks for your change, it's always good to keep things up-to-date like this :)
> 
> Before we can merge, we'll need you to update your commit message a little bit...
> 
> * You need to sign-off your commit, if you're not sure how to then you can find instructions here: https://github.com/CollaboraOnline/online/pull/7563/checks?check_run_id=18163427573
> * You need to have a change ID, this is a random trailer on your commit that allows us to track it even if is later amended/rebased etc. you can edit your commit to have this in only a few steps:
>   
>   * `cp .git-hooks/commit-msg .git/hooks/commit-msg`
>   * `git commit --amend`
>   * `git push -f `
> 
> Thanks for your diligence so far, hopefully we'll be able to get this merged soon :)

i will do it as per instructed

**Comment by BandhiyaHardik** [comment]
> Hey there @BandhiyaHardik! Thanks for your change, it's always good to keep things up-to-date like this :)
> 
> Before we can merge, we'll need you to update your commit message a little bit...
> 
> * You need to sign-off your commit, if you're not sure how to then you can find instructions here: https://github.com/CollaboraOnline/online/pull/7563/checks?check_run_id=18163427573
> * You need to have a change ID, this is a random trailer on your commit that allows us to track it even if is later amended/rebased etc. you can edit your commit to have this in only a few steps:
>   
>   * `cp .git-hooks/commit-msg .git/hooks/commit-msg`
>   * `git commit --amend`
>   * `git push -f `
> 
> Thanks for your diligence so far, hopefully we'll be able to get this merged soon :)

I followed the step in terminal it is saying everything is upto date after the last command `git push -f ` and i also added my name and mail in this `Signed-off-by: Author Name <authoremail@example.com>`

**Comment by Minion3665** [comment]
> I followed the step in terminal it is saying everything is upto date after the last command `git push -f ` and i also added my name and mail in this `Signed-off-by: Author Name <authoremail@example.com>`
> 
> i think it is not adding my name can u please help me with this ?

Sure, @BandhiyaHardik, I wonder if it would be quicker to help you on a short call? What times are you available?

**Comment by BandhiyaHardik** [comment]
I am available right now just give me 5 mins

**Comment by BandhiyaHardik** [comment]
@Minion3665 i am now availaible

**Comment by Minion3665** [comment]
> @Minion3665 i am now availaible

Awesome, please join https://meet.jit.si/co-skyler-hardik

**Comment by BandhiyaHardik** [comment]
@Minion3665 I Opened  another PR https://github.com/CollaboraOnline/online/pull/7584 and closing this one

**Pull request closed without merging**
