### PR TITLE
colibre-dark icons

### PR DESCRIPTION
**Pull request by Andreas-Kainz**
as subfolder at images/dark

Signed-off-by: andreas kainz <kainz.a@gmail.com>
Change-Id: I720cb82715760661faa74b7a9acb96ad97808ab5

* Resolves: #4736
* Target version: master

### CODE REVIEW

**Comment by Andreas-Kainz** [comment]
This are only the dark icons. 

The coding part when user use dark theme, the icons from the dark subfolder should be used, isn't part of this PR. Therefore a separate PR has to be done. But with this PR the "design" part was done.

**Comment by Rash419** [comment]
@Andreas-Kainz  lets wait to @pedropintosilva 's review : )

**Review by pedropintosilva — APPROVED** [review]
Thanks @Andreas-Kainz !

**Comment by pedropintosilva** [comment]
@Andreas-Kainz just note that might be useful, in some places we already have a icon alias so to avoid to have duplicated SVG files just because they have different ids/commands [see Control.JSDialogBuilder.js#L2324](https://github.com/CollaboraOnline/online/blob/master/browser/src/control/Control.JSDialogBuilder.js#L2324)

**Pull request merged**
