### PR TITLE
admin: handle errors while decoding URLs

### PR DESCRIPTION
**Pull request by vmiklos**
#9 0x7f1fb8b06ee7 in __cxa_throw (/usr/lib64/libstdc++.so.6+0xb7ee7) (BuildId: c74eca671e2dd0f063706372d103f8acef88f1e3)
    #10 0x7f1fb808645b in Poco::URI::decode(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>&, bool) (/usr/lib64/libPocoFoundation.so.92+0x15145b) (BuildId: 32601204eb877c998d0122c4bef1c7c08c8d0285)
    #11 0x55a887e4bb8b in Util::decodeURIComponent(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&) /home/vmiklos/git/collaboraonline/online-fuzz/common/Util.cpp:830:9
    #12 0x55a8874b7547 in AdminSocketHandler::handleMessage(std::vector<char, std::allocator<char>> const&) /home/vmiklos/git/collaboraonline/online-fuzz/wsd/Admin.cpp:392:20

Signed-off-by: Miklos Vajna <vmiklos@collabora.com>
Change-Id: I87f358d218e8774d5c82f1fb12e2f56898e7581e

### CODE REVIEW

**Comment by vmiklos** [comment]
> https://cpci.cbg.collabora.co.uk:8080/job/github_online_master_debug_vs_co-23.05/9616/console

unit-bad-doc-load failed, passes locally, retry.

**Review by mmeeks — APPROVED** [review]
Looks very sensible - thanks Miklos, can you back-port to 22.05 too ? =)

**Comment by timar** [comment]
There is one more `jwtToken = Util::decodeURIComponent(jwtToken);` line in Admin.cpp with slightly different error handling.

**Comment by vmiklos** [comment]
> There is one more `jwtToken = Util::decodeURIComponent(jwtToken);` line in Admin.cpp with slightly different error handling.

Thanks for pointing that out. Seeing that authAgent.verify() fails for an empty input properly, it's just a matter of style, it seems to me. We could move the URI decode inside the verify() to reduce duplication a bit.

**Comment by vmiklos** [comment]
> Looks very sensible - thanks Miklos, can you back-port to 22.05 too ? =)

https://github.com/CollaboraOnline/online/pull/8040

**Pull request merged**
