### PR TITLE
Sidebar fix Style and Character dropdown dialog width

### PR DESCRIPTION
**Pull request by Andreas-Kainz**
Signed-off-by: andreas kainz <kainz.a@gmail.com>
Change-Id: I6df2656c215d85fe31907fa73e063b45ef8522f5

image

fix min/max width settings from https://github.com/CollaboraOnline/online/commit/74811df14ae89c73943187eb98f783ca967bb315

### CODE REVIEW

**Comment by pedropintosilva** [comment]
I have changed your commit to have just the things related to the width fix (if you want you can simply git pull -r; do some changes; and just push to the some branch [without --force] and that will appear here as new additional commit.

**Comment by pedropintosilva** [comment]
I have tested as well you other changes:
```diff
```diff
diff --git a/browser/css/jssidebar.css b/browser/css/jssidebar.css
index 7a30fc004..e93ee198e 100644
--- a/browser/css/jssidebar.css
+++ b/browser/css/jssidebar.css
@@ -87,6 +87,9 @@
 #applystyle > .sidebar.jsdialog.ui-listbox {
        min-width: 186px;
 }
+
+#table-style {
+       padding-left: 4px;
 }
 
 #gradientstyle > .sidebar.jsdialog.ui-listbox {
@@ -104,6 +107,10 @@
 #fontsizecombobox > .sidebar.jsdialog.ui-listbox {
        min-width: 86px;
 }
+
+#fontheight {
+       position: relative;
+       left: -8px;
 }
 
 .sidebar.ui-expander {
```
The left padding seems ok, so you can add that

**Comment by pedropintosilva** [comment]
but the #fontheight changes was giving me weird results:

https://user-images.githubusercontent.com/65948705/152817016-3f34838b-9062-4557-ac69-4f5c59786c77.mp4

**Comment by Andreas-Kainz** [comment]
I moved the widget to the left but it's of for me if you don't want to have hard coded spaces.

**Pull request merged**
