### PR TITLE
Idle status postmessages

### PR DESCRIPTION
**Pull request by eszkadev**
postmessage: handle Get_User_State
    
Get_User_State postmessage is used to query user status.
If user is active or idle and how many seconds ago there
was registered last activity.
    
{
    state: 'idle',
    elapsed: 2.3
}

-------------------------

postmessage: send User_Active when become active again
    
We send User_Idle when user become idle, but there was no
similar message when user become active again.

### CODE REVIEW

**Review by juliushaertl — APPROVED** [review]
Code looks good, but haven't tested yet 👍

**Comment by pedropintosilva** [comment]
Waiting for @Rash419 to be merged

**Review by Rash419 — APPROVED** [review]
Works as expected : )

**Comment by Rash419** [comment]
Should we also add button for 'Get_User_State' in our framed.doc.html ?

**Comment by juliushaertl** [comment]
@eszkadev Quick followup question for integrating:

> Get_User_State postmessage is used to query user status.
> If user is active or idle and how many seconds ago there
> was registered last activity.

Can you tell what exactly last activity means in this case? Is it bound to mouse/keyboard events and is it also sent back if the user is still considered active?

**Comment by eszkadev** [comment]
Yes, it is bound to mouse / keyboard activity. Timer is always reset on any activity and Get_User_State_Resp returns time elapsed between that time and Date.now()

**Comment by hfiguiere** [comment]
> Should we also add button for 'Get_User_State' in our framed.doc.html ?

Done in https://github.com/CollaboraOnline/online/pull/7876

**Pull request merged**
