### PR TITLE
Update Colibre icons as tdf#133268

### PR DESCRIPTION
**Pull request by rizmut**
Update icons to match newest Colibre color scheme as LibreOffice's desktop 7.0 version.

For bug report, see https://bugs.documentfoundation.org/show_bug.cgi?id=133268

### CODE REVIEW

**Comment by pedropintosilva** [comment]
Thanks @rizmut !!
I didn't due a deep test but as far as I can, overall, we can merge it after we fix / clarify these:

On mobile : Impress (select a list; go to properties; lists) : these are meant to signify Outline Right/L/Down/Top and right now I see arrows. Is this expected?
mobile-impress-lists

On Impress sidebar icon for slide transition: The second icon looks quite different in terms of occupied size and alignment
impress-slide-transition

On Writer: increase indent is a simple arrow
writer-increase-indent

**Comment by fitojb** [comment]
I would drop from this commit the changes to the files:
* loleaflet/images/x-office-document.svg 
* loleaflet/images/x-office-presentation.svg 
* loleaflet/images/x-office-spreadsheet.svg

As they reflect LibreOffice’s, and not Collabora’s, branding.

**Comment by rizmut** [comment]
> Thanks @rizmut !!
> I didn't due a deep test but as far as I can, overall, we can merge it after we fix / clarify these:
> 
> On mobile : Impress (select a list; go to properties; lists) : these are meant to signify Outline Right/L/Down/Top and right now I see arrows. Is this expected?
> mobile-impress-lists
> 

Yes, this is expected. I have updated this icon to follow Galaxy icon. See it in desktop version:

gambar

> On Impress sidebar icon for slide transition: The second icon looks quite different in terms of occupied size and alignment
> impress-slide-transition
> 

I don't see this is a problem in desktop version.

gambar


> On Writer: increase indent is a simple arrow
> writer-increase-indent
OK, will update the toolbar.css along with Impress sidebar icons

**Comment by rizmut** [comment]
> I would drop from this commit the changes to the files:
> 
>     * loleaflet/images/x-office-document.svg
> 
>     * loleaflet/images/x-office-presentation.svg
> 
>     * loleaflet/images/x-office-spreadsheet.svg
> 
> 
> As they reflect LibreOffice’s, and not Collabora’s, branding.

I would like to hear what Collabora's view about this one.

**Comment by pedropintosilva** [comment]
> I would drop from this commit the changes to the files:
> 
>     * loleaflet/images/x-office-document.svg
> 
>     * loleaflet/images/x-office-presentation.svg
> 
>     * loleaflet/images/x-office-spreadsheet.svg
> 
> 
> As they reflect LibreOffice’s, and not Collabora’s, branding.

Thanks @fitojb for the heads up I completely missed that : p Nevertheless I think it would be wise to just accept this pull request as it is because:

- Then more people can test it and give feedback 
- The other icons were reminiscent from older theme I think
- We can always iterate afterwards : ) if needed

**Comment by pedropintosilva** [comment]
> > Thanks @rizmut !!
> > I didn't due a deep test but as far as I can, overall, we can merge it after we fix / clarify these:
> > On mobile : Impress (select a list; go to properties; lists) : these are meant to signify Outline Right/L/Down/Top and right now I see arrows. Is this expected?
> > mobile-impress-lists
> 
> Yes, this is expected. I have updated this icon to follow Galaxy icon. See it in desktop version:
> 
> gambar
> 
> > On Impress sidebar icon for slide transition: The second icon looks quite different in terms of occupied size and alignment
> > impress-slide-transition
> 
> I don't see this is a problem in desktop version.
> 
> gambar
> 
> > On Writer: increase indent is a simple arrow
> > writer-increase-indent
> 
> OK, will update the toolbar.css along with Impress sidebar icons

Thanks, I appreciate that! : )

**Comment by mrkara** [comment]
Stuff here got merged in #248 

So let's close this. @rizmut Thanks!

**Pull request closed without merging**
