### PR TITLE
annotation: comments: allow comment operation in read only mobile view

### PR DESCRIPTION
**Pull request by lpranam**
Signed-off-by: Pranam Lashkari <lpranam@collabora.com>
Change-Id: I91e631549545696c573ed873126e225947a1ad18

* Target version: master 

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Review by eszkadev — CHANGES_REQUESTED** [review]
I think it allows to add comment in read-only file

**Review by eszkadev — COMMENTED** [review]
ok, it is only for calling the command... but there should be protection in ui to not show these commands in read-only file

**Review by eszkadev — APPROVED** [review]

**Review by eszkadev — CHANGES_REQUESTED** [review]
tested again, it allows to add comment (open the dialog) in read-only file but after modal is closed no comment appears. it should be blocked

**Comment by lpranam** [comment]
closed in favour of #5410

**Pull request closed without merging**
