### PR TITLE
Private/mmeeks/zstd

### PR DESCRIPTION
**Pull request by mmeeks**
* Resolves: # 
* Target version: master 

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Review by timar — CHANGES_REQUESTED** [review]
ZSTD_minCLevel() function is not available on all target platforms, e.g. on Ubuntu 18.04 where we only have libzstd 1.3.3.

**Comment by mmeeks** [comment]
Thanks Andras - you rock =) so we can hard-code the level from minCLevel as a number I believe instead.

**Comment by timar** [comment]
> Thanks Andras - you rock =) so we can hard-code the level from minCLevel as a number I believe instead.

If you can use the lowest version API, then it'd be the easiest, otherwise we could try to build latest libzstd everywhere and link statically. 
Android and iOS may be problematic, too.

**Comment by timar** [comment]
Wrt. failure with "Fast Build against Core co-22.05" on Ubuntu 18.04, order of libraries matter, see below. But it's not a problem e.g. on Debian 9!

<pre><font color="#26A269"><b>collabora@ubuntu1804</b></font>:<font color="#12488B"><b>~/jenkins/workspace/github_online_master_vs_co-22.05</b></font>$ /bin/bash ./libtool  --tag=CXX   --mode=link g++  -g -O2 -Wall -Wextra -Wshadow -Wundef -Werror -std=c++17 -pthread -Wl,-E -lpam -lz -L/usr/local/lib -lzstd -lssl -lcrypto -L/opt/poco/lib -o lokitclient common/Log.o common/DummyTraceEventEmitter.o tools/KitClient.o common/Protocol.o common/StringVector.o common/TraceEvent.o common/Util.o  -lpam -lcap -lpng -ldl  -lstdc++fs -lPocoNetSSL -lPocoNet -lPocoUtil -lPocoJSON -lPocoXML -lPocoFoundation -lPocoCrypto -lssl -lcrypto
libtool: link: g++ -g -O2 -Wall -Wextra -Wshadow -Wundef -Werror -std=c++17 -pthread -Wl,-E -o lokitclient common/Log.o common/DummyTraceEventEmitter.o tools/KitClient.o common/Protocol.o common/StringVector.o common/TraceEvent.o common/Util.o  -lz -L/usr/local/lib -lzstd -L/opt/poco/lib -lpam -lcap -lpng -ldl -lstdc++fs -lPocoNetSSL -lPocoNet -lPocoUtil -lPocoJSON -lPocoXML -lPocoFoundation -lPocoCrypto -lssl -lcrypto -pthread
common/Log.o: In function `Log::initialize(std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt; const&amp;, std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt; const&amp;, bool, bool, std::map&lt;std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt;, std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt;, std::less&lt;std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt; &gt;, std::allocator&lt;std::pair&lt;std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt; const, std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt; &gt; &gt; &gt; const&amp;)&apos;:
/home/collabora/jenkins/workspace/github_online_master_vs_co-22.05/common/Log.cpp:311: undefined reference to `Poco::Logger::create(std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt; const&amp;, Poco::AutoPtr&lt;Poco::Channel&gt;, int)&apos;
common/Log.o: In function `Log::setThreadLocalLogLevel(std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt; const&amp;)&apos;:
/home/collabora/jenkins/workspace/github_online_master_vs_co-22.05/common/Log.cpp:374: undefined reference to `Poco::Logger::create(std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt; const&amp;, Poco::AutoPtr&lt;Poco::Channel&gt;, int)&apos;
common/Util.o: In function `Util::JsonToMap(std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt; const&amp;)&apos;:
/home/collabora/jenkins/workspace/github_online_master_vs_co-22.05/common/Util.cpp:657: undefined reference to `Poco::JSON::Parser::Parser(Poco::SharedPtr&lt;Poco::JSON::Handler, Poco::ReferenceCounter, Poco::ReleasePolicy&lt;Poco::JSON::Handler&gt; &gt; const&amp;)&apos;
common/Util.o: In function `std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt; Poco::format&lt;std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt;, std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt; &gt;(char const*, std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt;, std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt;)&apos;:
/opt/poco/include/Poco/Format.h:172: undefined reference to `Poco::format(std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt;&amp;, char const*, std::vector&lt;Poco::Any, std::allocator&lt;Poco::Any&gt; &gt; const&amp;)&apos;
collect2: error: ld returned 1 exit status
<font color="#26A269"><b>collabora@ubuntu1804</b></font>:<font color="#12488B"><b>~/jenkins/workspace/github_online_master_vs_co-22.05</b></font>$ /bin/bash ./libtool  --tag=CXX   --mode=link g++  -g -O2 -Wall -Wextra -Wshadow -Wundef -Werror -std=c++17 -pthread -Wl,-E -lpam -lz -lssl -lcrypto -L/opt/poco/lib -o lokitclient common/Log.o common/DummyTraceEventEmitter.o tools/KitClient.o common/Protocol.o common/StringVector.o common/TraceEvent.o common/Util.o  -lpam -lcap -lpng -ldl  -lstdc++fs -lPocoNetSSL -lPocoNet -lPocoUtil -lPocoJSON -lPocoXML -lPocoFoundation -lPocoCrypto -lssl -lcrypto -L/usr/local/lib -lzstd
libtool: link: g++ -g -O2 -Wall -Wextra -Wshadow -Wundef -Werror -std=c++17 -pthread -Wl,-E -o lokitclient common/Log.o common/DummyTraceEventEmitter.o tools/KitClient.o common/Protocol.o common/StringVector.o common/TraceEvent.o common/Util.o  -lz -L/opt/poco/lib -lpam -lcap -lpng -ldl -lstdc++fs -lPocoNetSSL -lPocoNet -lPocoUtil -lPocoJSON -lPocoXML -lPocoFoundation -lPocoCrypto -lssl -lcrypto -L/usr/local/lib -lzstd -pthread
<font color="#26A269"><b>collabora@ubuntu1804</b></font>:<font color="#12488B"><b>~/jenkins/workspace/github_online_master_vs_co-22.05</b></font>$ ls -l lokitclient 
-rwxrwxr-x 1 collabora collabora 7013304 Oct  7 19:10 <font color="#26A269"><b>lokitclient</b></font>
</pre>

**Comment by timar** [comment]
I fixed the link issue, the reason was that we had stray poco libs in /usr/local/libs and they messed up the linking when we introduced /usr/local/lib patch for libzstd. 
That leaves us with 1 unit test failure with make check:
wsd-54795-54795 2022-10-12 20:28:04.711327 +0000 [ coolwsd ] ERR  Failed to inflate zimage| kit/Delta.hpp:623
then segfault

**Review by timar — APPROVED** [review]

**Comment by timar** [comment]
iOS against Core co-22.05 — SUCCESS

**Pull request merged**
