### PR TITLE
notebookbar: enable currency dropdown

### PR DESCRIPTION
**Pull request by eszkadev**
It is request from user that currency icon has no dropdown to select something else than USD.

To enable that we need widget from core be enabled + restructure notebookbar so we use correct id's in the communication with core.

To get this done I simplified notebookbar by using CSS grid and removing old cell/row containers structure.
So similar to sidebar we will have plain structure of widgets.

### CODE REVIEW

**Comment by eszkadev** [comment]
related: https://gerrit.libreoffice.org/c/core/+/161829

**Comment by pedropintosilva** [comment]
I have tested multiple times and using different browsers (hopefully I didn't miss nothing :crossed_fingers: )
I have found 2 issues and added additional commits for that.

Additionally the zoomreset should be a bigtoolitem but then the "this._map.setZoom(this._map.options.zoom);" doesn't work as it probably need to be fired from uimanager: 
<details>

```diff
diff --git a/browser/src/control/Control.JSDialogBuilder.js b/browser/src/control/Control.JSDialogBuilder.js
index a74ba2d97f..47acd55b96 100644
--- a/browser/src/control/Control.JSDialogBuilder.js
+++ b/browser/src/control/Control.JSDialogBuilder.js
@@ -2159,6 +2159,7 @@ L.Control.JSDialogBuilder = L.Control.extend({
 		}
 
 		var iconURLAliases = {
+			'reset20zoom': 'zoomreset',
 			'file-saveas': 'saveas',
 			'home-search': 'recsearch',
 			'addmb-menu': 'ok',
diff --git a/browser/src/control/Control.NotebookbarCalc.js b/browser/src/control/Control.NotebookbarCalc.js
index d314bd8a97..e0bebb9e76 100644
--- a/browser/src/control/Control.NotebookbarCalc.js
+++ b/browser/src/control/Control.NotebookbarCalc.js
@@ -1217,7 +1217,7 @@ L.Control.NotebookbarCalc = L.Control.NotebookbarWriter.extend({
 			{
 				'id': 'zoomreset',
 				'class': 'unozoomreset',
-				'type': 'menubartoolitem',
+				'type': 'bigtoolitem',
 				'text': _('Reset zoom'),
 				'command': _('Reset zoom'),
 				'accessibility': { focusBack: true,	combination: 'J', de: null }
diff --git a/browser/src/control/Control.NotebookbarDraw.js b/browser/src/control/Control.NotebookbarDraw.js
index 5a0c8175f1..f345514a51 100644
--- a/browser/src/control/Control.NotebookbarDraw.js
+++ b/browser/src/control/Control.NotebookbarDraw.js
@@ -344,7 +344,7 @@ L.Control.NotebookbarDraw = L.Control.NotebookbarImpress.extend({
 			{
 				'id': 'zoomreset',
 				'class': 'unozoomreset',
-				'type': 'menubartoolitem',
+				'type': 'bigtoolitem',
 				'text': _('Reset zoom'),
 				'command': _('Reset zoom'),
 				'accessibility': { focusBack: true, combination: 'RZ', de: null }
diff --git a/browser/src/control/Control.NotebookbarImpress.js b/browser/src/control/Control.NotebookbarImpress.js
index 6ca26a4eb8..3ec943709f 100644
--- a/browser/src/control/Control.NotebookbarImpress.js
+++ b/browser/src/control/Control.NotebookbarImpress.js
@@ -453,7 +453,7 @@ L.Control.NotebookbarImpress = L.Control.NotebookbarWriter.extend({
 			{
 				'id': 'zoomreset',
 				'class': 'unozoomreset',
-				'type': 'menubartoolitem',
+				'type': 'bigtoolitem',
 				'text': _('Reset zoom'),
 				'command': _('Reset zoom'),
 				'accessibility': { focusBack: true, combination: 'ZR', de: null }
diff --git a/browser/src/control/Control.NotebookbarWriter.js b/browser/src/control/Control.NotebookbarWriter.js
index f0a7405ffe..0e7a49facd 100644
--- a/browser/src/control/Control.NotebookbarWriter.js
+++ b/browser/src/control/Control.NotebookbarWriter.js
@@ -1410,7 +1410,7 @@ L.Control.NotebookbarWriter = L.Control.Notebookbar.extend({
 			{
 				'id': 'zoomreset',
 				'class': 'unozoomreset',
-				'type': 'menubartoolitem',
+				'type': 'bigtoolitem',
 				'text': _('Reset zoom'),
 				'command': _('Reset zoom'),
 				'accessibility': { focusBack: true, combination: 'J', de: 'O' }
```

</details>

**Comment by eszkadev** [comment]
Conversion of `menubutton` to `custombutton` is required. It is not that simple, we need to move some code. This is refactor I have in plans. I will create ticket, someone will have time to do it maybe.

**Comment by eszkadev** [comment]
> Conversion of `menubartoolitem` to `(big)customtoolitem` is required. It is not that simple, we need to move some code. This is refactor I have in plans. I will create ticket, someone will have time to do it maybe.

https://github.com/CollaboraOnline/online/issues/8029

**Review by quikee — APPROVED** [review]
Looks good

**Pull request merged**
