### PR TITLE
Save icon use text color and primary-color for feedback

### PR DESCRIPTION
**Pull request by Andreas-Kainz**
All save icons are now gray,
like the print icon or the hamburger menu icon.

The gray color is the color-main-text as the icon
is next to text, it's not so visible.

Indicators like saveas or modified use color-primary
in the icons and in the .css file

Signed-off-by: andreas kainz <kainz.a@gmail.com>
Change-Id: I7311b71dff356d2c9aaf9d03d97f33a8ae9fb830

* Resolves: #4215

#### Classic Toolbar
Screenshot_20220217_234942

Screenshot_20220217_235028

#### Notebookbar
Screenshot_20220218_000506

### CODE REVIEW

**Comment by Andreas-Kainz** [comment]
fyi the document-icon will have the same size than the hamburger and save icon in the shortcuts list. See #4224

**Comment by rizmut** [comment]
As additional info, Colibre in LibreOffice has been updated. It's up to you whether to sync up or not.

**Comment by Andreas-Kainz** [comment]
@pedropintosilva your prefernce for gray or colourful?

**Comment by pedropintosilva** [comment]
I think a neutral colour like gray would be better, specially because we then use colourful indicator on top (dot)

**Comment by pedropintosilva** [comment]
I would prefer to avoid that purple, specially because we use a different colour on top via the dot indicator. So either app colour or a neutral colour would be fine by me. Thanks _merging_

**Comment by rizmut** [comment]
> > As additional info, Colibre in LibreOffice has been updated. It's up to you whether to sync up or not.
> 
> good point, will update to the save icons to the new ones https://github.com/LibreOffice/core/blob/master/icon-themes/colibre_svg/cmd/lc_save.svg
So you did not update it, did you?

**Pull request merged**
