### PR TITLE
svg cleanup

### PR DESCRIPTION
**Pull request by DarkknightAK**
Change-Id: I203751dc44ad072cfd709ff72370ef492c23c50f

### CODE REVIEW

**Comment by DarkknightAK** [comment]
I think the iOS Failure isn't related to this patch, how can I restart the check?

**Comment by yunusem** [comment]
@DarkknightAK You can ask any Collabora Productivity collaborator to rebuild any failed build step, if you are sure it is false positive.

**Comment by DarkknightAK** [comment]
It look like I don't have access to push the request myself, so I think the request can be pushed to master.

**Comment by pedropintosilva** [comment]
@DarkknightAK I just resolved the persistent conflicts

**Comment by DarkknightAK** [comment]
Thanks next time I talk first mit rizal.

**Pull request closed without merging**
