### PR TITLE
Remove template list URL from application settings

### PR DESCRIPTION
**Pull request by plubius**
Change-Id: I72cfbde2a0a062d49e89ce81999785b2bffc0d1f

* Resolves: # 
* Target version: master 

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by plubius** [comment]
@tml1024 @timar Is this what you were expecting to see after removal of the template list URL setting?:

Screenshot 2023-02-22 at 9 03 50 PM

**Comment by tml1024** [comment]
Yes, and then also all the newly dead code related to that can be removed. The download(), downloadTemplate(), updateTemplates() functions. But maybe we first should ponder how to figure out if any user actually is using that feature... Oh well, if we remove it, and somebody complains, we just revert the removal;)

**Comment by plubius** [comment]
> Oh well, if we remove it, and somebody complains, we just revert the removal;)

I would vote leaving commented out code in for at least a few more TestFlight releases so that it can quickly be reverted if someone is still using that feature. If someone is still using it, I wouldn't be surprised if we won't hear about it until after we release it through the regular App Store.

**Comment by tml1024** [comment]
Well, experience has shown that code just left in #if 0 or commented out tends to stay that way for long. That is one reason why we use version control, so that we don't need to comment out code, but can simply remove it. It is trivial to find. Code that is commented out or ifdeffed out is not compiled anyway, so it might bit-rot because of changing APIs, and restoring it is not any more trivial than restoring it from the commit that removed it. But if you *promise* to remove it for real later this year, OK... ;)

**Comment by plubius** [comment]
> Well, experience has shown that code just left in #if 0 or commented out tends to stay that way for long. That is one reason why we use version control, so that we don't need to comment out code, but can simply remove it. It is trivial to find.

I get your point. My concern in this case is that this requirement to purge this feature is very sudden and I don't see any compelling reason to remove a feature that doesn't seem to be causing anyone any harm.

Maybe there are good reasons to remove this feature but I do not know what they are. I am trusting your judgement that this is a desirable change to make.  But since I will likely be on the sharp point of any user pushback, I would like to hedge my bets.

**Comment by nikslor** [comment]
I'm in favor of removing it as well.

**Comment by plubius** [comment]
@tml1024 @nikslor OK. How about we do this:

1. Commit this pull request and include it in the next TestFlight build
2. I submit a separate pull request to the master branch that completely removes the disabled code

Sound good?

**Pull request merged**
