### PR TITLE
private/pedro/no btn matroska

### PR DESCRIPTION
**Pull request by pedropintosilva**
- Tabs: Don't create button inside of a button when one element suffices
- Remove unnecessary !important from ui-tab

### CODE REVIEW

**Review by eszkadev — APPROVED** [review]

**Comment by pedropintosilva** [comment]
failing in unrelated tests

**Comment by pedropintosilva** [comment]
now failing on make -C cypress_test run-desktop spec=calc/undo_redo_spec.js, retriggered

**Comment by pedropintosilva** [comment]
aborted with no failed results, retriggered

**Comment by pedropintosilva** [comment]
so I think I should just merge this because:
* There is no mention of the removed ".ui-tab-content" in cy[ress anyway

**Comment by pedropintosilva** [comment]
this was merged

**Pull request closed without merging**
