### PR TITLE
OnScrollBy: Fix bug.

### PR DESCRIPTION
**Pull request by gokaysatir**
Code from old implementation was forgotten to update.

Signed-off-by: Gökay ŞATIR <gokaysatir@gmail.com>
Change-Id: I4d5090ebf6ac5fa0e9746e542c47c0e682160ba5

* Resolves: # 
* Target version: master 

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by kendy** [comment]
@gokaysatir: Unfortunately cannot merge it in the current form - when you start selecting in cell eg. H100, and leave the mouse pointer at the top (so that it scrolls towards the first row), when it hits the 1st row, the scrolling does not stop at the 1st row; instead it continues scrolling and the 1st row grows vertically.

**Review by kendy — CHANGES_REQUESTED** [review]
See the comment. wrt. the problematic behavior.

**Review by eszkadev — APPROVED** [review]
I tested, now it works correctly

**Comment by kendy** [comment]
@gokaysatir: So this improves the situation for me, but still does not fix the issue completely - when you let it scroll upwards, it scrolls, but does not extend the selection; only when you move the mouse pointer back into the sheet, it finally grows the selection.

**Comment by merttumer** [comment]
It still needs some but certainly improves the issue. We need these patches for another problem, so merging them.

**Pull request merged**
