### PR TITLE
Fix build with libc++: std::min() parameters should be of the same type.

### PR DESCRIPTION
**Pull request by arrowd**
Signed-off-by: Gleb Popov <6yearold@gmail.com>
Change-Id: Icdb67f0576992cd54c8e15c85fbaf2745aba218c

- [X] Code is properly formatted
- [X] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [X] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by arrowd** [comment]
Bump.

**Comment by arrowd** [comment]
Another bump.

**Comment by mrkara** [comment]
@arrowd Thank you for your contribution! Looking forward to your next PR. ;)

**Review by Ashod — COMMENTED** [review]
Thanks @arrowd for the patch. I wonder if we should remove the `.count()`. Can you please try and see if it compiles (and without the cast, of course) ?

**Comment by arrowd** [comment]
Nope, doesn't work too:

```
./net/WebSocketHandler.hpp:436:19: error: no matching function for call to 'min'
                = std::min(timeoutMaxMicroS, PingFrequencyMicroS - timeSincePingMicroS);
                  ^~~~~~~~
/usr/include/c++/v1/algorithm:2560:1: note: candidate template ignored: deduced conflicting types for parameter '_Tp' ('long' vs. 'std::__1::chrono::duration<long long, std::__1::ratio<1, 1000000> >')
min(const _Tp& __a, const _Tp& __b)
```

**Comment by Ashod** [comment]
> Nope, doesn't work too:

Thanks for trying!

**Pull request merged**
