### PR TITLE
Replace magic numbers with keycode constants #4929

### PR DESCRIPTION
**Pull request by callmetushar123**
* Resolves: # 
* Target version: master 

### Summary
This is my demo pull request. I just want to make sure if I am going in the right direction, no need to merge it, I will work on it

### TODO

- [ ] ...

### Checklist

- [x] Code is properly formatted
- [x] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by callmetushar123** [comment]
@eszkadev Hello can you please have a look if I am going in the right direction or not?

**Comment by callmetushar123** [comment]
@pedropintosilva Hello. Please don't merge anything I have just changed a few aspects of the code to check if I am going in the right direction.

I have already added changed ID in the commit message, why is it showing error?

**Comment by pedropintosilva** [comment]
because you have commits without it, that's why I recommended to clean up the commits (you have multiple) Also to avoid merge commits to ever sneak in you can https://forum.collaboraonline.com/t/how-to-keep-your-fork-in-sync/49#bonus-4

**Comment by callmetushar123** [comment]
squash
rebase

I am getting an error, I tried to `drop` line 3 but it couldn't be done, I don't understand what's causing the error. @pedropintosilva

**Pull request closed without merging**
