### PR TITLE
draw: Added Grid

### PR DESCRIPTION
**Pull request by hfiguiere**
* Resolves: #7406 
* Also see: #4556
* Target version: master 

### Summary

This provide Grid visibility in both draw and impress, as well as enable snap to grid.

### TODO

- [x] Figure out how the have the action state report to the UI - this need a core patch
  - TBD
- [ ] Snap to grid doesn't seem to be implemented and maybe need to be done first
- [ ] Validate the location of the various UI items

### Checklist

- [x] Code is properly formatted
- [x] All commits have Change-Id
- [ ] I have run tests with `make check`
- [x] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by eszkadev** [comment]
cc : @gokaysatir    it something from this PR useful now? I think we have competing solution merged already.
If not - can we close the PR? @hfiguiere

**Comment by hfiguiere** [comment]
I don't see where the "GridVisible" command is made available beside the Shift F9 shortcut.

Also, it should be noted #9019 called for disabling it in LOKit as a workaround. 

So it remain relevant but #9019 should be fixed first.

**Comment by gokaysatir** [comment]
I think we could use a section for the task? Also we can use simplePoint class instead of point i think.

I think i'd prefer to position the Path.Constraints.ts file as a section inside canvas->sections directory. If it cannot be the section itself but a helper, then we have "app" folder for middlewares. But it seems we need a section, either as a base class or with the content of Constraints.ts file.

If we can solve this without touching Path.Drag.js file, that'd be awesome.

All above should be possible. Can you check CanvasSectionContainer and a few sections if you are new to structure and share your comments? That's the new way we use and if you use too much of old structures, we may need to refactor your code in the future.

**Comment by hfiguiere** [comment]
oh so you are actually talking about this PR https://github.com/CollaboraOnline/online/pull/7958

(this one is currently on top of it)

**Comment by gokaysatir** [comment]
> oh so you are actually talking about this PR #7958 - "draw: constrain object move with Shift "
> 
> (this one is currently on top of it)

Ah, yes it seems, they seem to share code.

**Comment by hfiguiere** [comment]
Note that #7958 is now broken since some of the front-end code got re-architectured.

**Comment by eszkadev** [comment]
closing, we just merged: https://github.com/CollaboraOnline/online/pull/10147

**Pull request closed without merging**
