### PR TITLE
Android: Insert Cells Menu Misaligned Radio Buttons

### PR DESCRIPTION
**Pull request by codewithvk**
Change-Id: Ie6bdb2423f92b5959a2233ee0dccc6f8e2e5dc35

* Resolves: #7701
* Target version: master

### CODE REVIEW

**Review by Darshan-upadhyay1110 — COMMENTED** [review]
image
image


Now it looks good in mobile.

A small nit pick please make sure we are consistent with element that has checkboxes.

here if you could change margin to  'margin: 10px 20px 10px 0px !important;` ( in the new css property as you have added)
Same as previous case.

**Comment by Darshan-upadhyay1110** [comment]
@codewithvk i won't mind if you will add more consistency in element margin and padding in mobile view that will be great 😉 

For example: - make sure starting or ending of any element  in mobile wizard should be same. Either it is `radioButton` or `checkbox`

**Comment by codewithvk** [comment]
> @codewithvk i won't mind if you will add more consistency in element margin and padding in mobile view that will be great 😉
> 
> For example: - make sure starting or ending of any element in mobile wizard should be same. Either it is `radioButton` or `checkbox`

That's a great suggestion! I will consider it and try to create a follow-up PR if needed.

**Review by Darshan-upadhyay1110 — APPROVED** [review]

**Comment by codewithvk** [comment]
@Darshan-upadhyay1110 Found another interesting approach. It is much more consistent and better than the older ones. Could you please review it again? : )

**Review by Darshan-upadhyay1110 — APPROVED** [review]

**Review by gokaysatir — APPROVED** [review]
Checked, thanks for the fix :)

**Pull request merged**
