### PR TITLE
avoid rendering for execution of ~every message

### PR DESCRIPTION
**Pull request by dennisfrancis**
Send the canvas container into a paused state just before a batch of
queued messages are going to be executed. During this state the
container dirties itself for every requestRedraw() call. After all
messages in the current slurp batch is executed, resume rendering
starting with a re-render if necessary based on dirty flag.

Signed-off-by: Dennis Francis <dennis.francis@collabora.com>
Change-Id: Ice5347aac78f4f19642b96edb929836b15c55599

* Resolves: # 
* Target version: master 

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Review by mmeeks — APPROVED** [review]
Looks great I think we prolly need it for the tile event slurping too.
Thanks!

**Comment by mmeeks** [comment]
Performs very nicely =) good stuff.

**Comment by dennisfrancis** [comment]
@mmeeks I've added the same for tile event slurping. I tried to use the same timer for both but it needs a periodic cleanup timer to do the left over tile events in the tile slurp queue. Without the periodic cleanup using setInterval, I see the final few tile updates not getting rendered (tile sitting in the queue till next message arrives :) ). This is very visible in multi user editing - when the other user is editing and stops typing, the first user do not see the last (few?) character(s) they typed until some message is sent to the first user.

**Comment by mmeeks** [comment]
Hmm - I'm not a fan of the second commit here, the random 30ms delay is unhelpful I think =) - can we get just the first patch in - I'll sketch / implement what I was thinking about for merging the slurping - I think we can simplify the asynchronicity here for the core.

**Comment by dennisfrancis** [comment]
@mmeeks I've removed the original second commit and added one for the scroll section fix. This avoids any scrolling till the end of msg slurping and it repaints the canvas only once.

**Comment by mmeeks** [comment]
Looks lovely to me - thanks Dennis =)

**Pull request merged**
