### PR TITLE
endless keyboard android backport

### PR DESCRIPTION
**Pull request by merttumer**
* Resolves: # 
* Target version: master 

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Review by eszkadev — COMMENTED** [review]
this triggers for me both: context menu and keyboard at the same time. on master it was ok

**Comment by timar** [comment]
We won't release Android app from co-6-4 any more.

**Comment by merttumer** [comment]
> We won't release Android app from co-6-4 any more.

this is not for the app but the mobile browser acutally.

**Review by eszkadev — APPROVED** [review]
now works as expected

**Pull request merged**
