### PR TITLE
fix: add missing operator overloading of '!='

### PR DESCRIPTION
**Pull request by Mor1arty**
* Resolves: #10345
* Target version: master 

### Summary

Implement the operator overloading of !=

### TODO

- [ ] ...

### Checklist

- [x] I have run `make prettier-write` and formatted the code.
- [x] All commits have Change-Id
- [  ] I have run tests with `make check`
- [x] I have issued `make run` and manually verified that everything looks okay
- [x] Documentation (manuals or wiki) has been updated or is not required

I could run the application after `make run`, however there was one FAILED task when I ran `make check`, I'm not sure if this was caused by me. I'm sorry that I found no way to get the test-suite.log due to my horrible network. Apologize for that again.

@Darshan-upadhyay1110

### CODE REVIEW

**Comment by Darshan-upadhyay1110** [comment]
Thanks and welcome @Mor1arty  ! But please after looking and proceed according to my notes do sign- off your commits and Add Change -id.

### Sign-off
(DCO)

You should only do this if:

To add your Signed-off-by line to every commit in this branch:

* Ensure you have a local copy of your branch by [checking out the pull request locally via command line](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally).
  * In your local branch, run: git rebase HEAD~1 --signoff
  * Force push your changes to overwrite the branch: git push --force-with-lease origin Mor1arty:master

### Change-id


How to obtain Change-Id in commit message :

copy commit hook :
cp .git-hooks/commit-msg .git/hooks/commit-msg

And then amend your commit message :
git commit --amend
git push -f

**Comment by Darshan-upadhyay1110** [comment]
Please run following command to add your signature 

`git rebase HEAD~1 --signoff`
Then force push :)

**Review by eszkadev — APPROVED** [review]

**Comment by Darshan-upadhyay1110** [comment]
Thanks so much, @Mor1arty, for this important fix—much appreciated!

There are plenty of fun, easy hacks waiting to be tackled, which can help you dive into Collabora Online’s codebase and discover its features. We’d love to see you join our community meetings and our lively Matrix channel, where you’re welcome to ask questions, discuss ideas, or just hang out. It would be great to have you there!

Matrix link: https://app.element.io/#/room/#cool-dev:matrix.org

More ways to connect: https://collaboraonline.github.io/post/communicate/

**Comment by Mor1arty** [comment]
> Thanks so much, @Mor1arty, for this important fix—much appreciated!
> 
> There are plenty of fun, easy hacks waiting to be tackled, which can help you dive into Collabora Online’s codebase and discover its features. We’d love to see you join our community meetings and our lively Matrix channel, where you’re welcome to ask questions, discuss ideas, or just hang out. It would be great to have you there!
> 
> Matrix link: https://app.element.io/#/room/#cool-dev:matrix.org
> 
> More ways to connect: https://collaboraonline.github.io/post/communicate/

@Darshan-upadhyay1110 Thank you so much for your recognition and invitation!

I'm delighted to contribute to Collabora Online. I'll definitely join the community meetings and participate in discussions on the Matrix channel - it's a great opportunity for learning and collaboration.

Looking forward to growing together with the community!

**Pull request closed without merging**
