### PR TITLE
private/pedro/doc status saveicon n statusbar

### PR DESCRIPTION
**Pull request by pedropintosilva**
- **Fix save icon not changing properly the image**
- **Status bar: last modification: remove icon and extra text**

### CODE REVIEW

**Comment by pedropintosilva** [comment]
@eszkadev please review the status bar
@Darshan-upadhyay1110 please the commit related to icon on the toolbox (topbar)

**Review by eszkadev — APPROVED** [review]
ok for me

**Review by Darshan-upadhyay1110 — APPROVED** [review]
Saving animation is fixed and works well, Thanks Pedro 🙇🏼

**Comment by Darshan-upadhyay1110** [comment]
This PR is the fix for regression created by : https://github.com/CollaboraOnline/online/pull/10027

**Pull request merged**
