### PR TITLE
Display the name of the document more completely

### PR DESCRIPTION
**Pull request by bayramcicek**
- use available space for document name.
- make the title bold for more visibility.

Change-Id: Ia3513708ac831ab4eca6cc8f11a0694c2651a07a

* Resolves: # 
* Target version: master 

### TODO

- [ ] ...

### Checklist

- [ ] I have run `make prettier-write` and formatted the code.
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by bayramcicek** [comment]
https://github.com/user-attachments/assets/159b1b2d-e207-4a5e-bcc8-bb4a8aee0ba7

When I shrink the window size `sidebar` and `navigator` buttons float to the left side.

**Review by pedropintosilva — APPROVED** [review]
@bayramcicek Looks awesome! and thanks for not only making it more visible but also following what we have discussed WRT the flex box. Much appreciated :) 

I haven;t tested on the tablet. did you? If not let me first do that before we merge it

**Comment by bayramcicek** [comment]
> @bayramcicek Looks awesome! and thanks for not only making it more visible but also following what we have discussed WRT the flex box. Much appreciated :)
> 
> I haven;t tested on the tablet. did you? If not let me first do that before we merge it

Thanks for the review :)
No, I haven't tested on the tablet.

**Comment by pedropintosilva** [comment]
I have tested on Desktop and iPad. Everything seems good. Both on Notebookbar and compact view. These are just CSS changes with green cypress tests and thus safe to get in.

**Comment by pedropintosilva** [comment]
just one last check and I will press the button

**Pull request merged**
